

 
 
STATE_MAGE_CHASERCLUSTER         <- 242    
STATE_MAGE_AVATARDANCE         <- 243    
STATE_MAGE_AVATAR          <- 245    
STATE_MAGE_RETURNTOBM         <- 246    
STATE_MAGE_QUASAREXPLOSION        <- 247    
STATE_MAGE_DRAGONDANCE         <- 248    
STATE_MAGE_ELEMENTALCURTAIN        <- 249    
STATE_MAGE_ELEMENTALQUAKE        <- 250    
STATE_MAGE_CRYSTALOFOVERMIND        <- 251    
STATE_MAGE_THEGATE          <- 252    
STATE_MAGE_SESTOELEMENTO         <- 253    
STATE_MAGE_ELECTRICRABBIT        <- 131    
STATE_MAGE_JACKFROSTICEWATER        <- 132    
STATE_MAGE_LOLLIPOPCRUSH         <- 133    
STATE_MAGE_UROBOROS          <- 134    
STATE_MAGE_MOONSHADOW         <- 135    
STATE_MAGE_SUMMONKRUTA         <- 136    
STATE_MAGE_REPEATEDSMASHOFRAGE       <- 137    
STATE_MAGE_SUMMONHEILROM         <- 138    
STATE_MAGE_SUMMONRAMOS         <- 139    
STATE_MAGE_BUGFALL          <- 126    

STATE_FAVORITE <- 209
STATE_RELIVE <- 244
STATE_TAILOR <- 210
STATE_JUMPDOTQUAKE <- 211
STATE_MADBIGBREAK <- 212
STATE_MADDEFANCE <- 213
STATE_MADDOTSHOOT <- 214
STATE_CIRRUSAREA <- 215
STATE_CIRRUSCUT <- 216
STATE_DOLL <- 217
STATE_ROSECIRRUS <- 218

STATE_BLOCKFORESTCIRRUS <- 219
STATE_FATESLAVE <- 220
STATE_HOTLOVE <- 221
STATE_SPRLITMAGIC <- 222

STATE_SORCERESSBUFF <- 223

STATE_MADBIGDOG <- 224
STATE_PAINFUGRADEN <- 225
STATE_TERRIBLEDOT <- 226
STATE_DOLLFOREST <- 227
STATE_CURSEOFDOT <- 228
STATE_KEEPOUT <- 229

 
 
SKILL_MAGE_CHASERCLUSTER         <- 242    
SKILL_MAGE_AVATARDANCE         <- 243    
SKILL_MAGE_AVATAR          <- 245    
SKILL_MAGE_RETURNTOBM         <- 246    
SKILL_MAGE_QUASAREXPLOSION        <- 247    
SKILL_MAGE_DRAGONDANCE         <- 248    
SKILL_MAGE_ELEMENTALCURTAIN        <- 249    
SKILL_MAGE_ELEMENTALQUAKE        <- 250    
SKILL_MAGE_CRYSTALOFOVERMIND        <- 251    
SKILL_MAGE_THEGATE          <- 252    
SKILL_MAGE_SESTOELEMENTO         <- 253    
SKILL_MAGE_ELECTRICRABBIT        <- 131    
SKILL_MAGE_JACKFROSTICEWATER        <- 132    
SKILL_MAGE_LOLLIPOPCRUSH         <- 133    
SKILL_MAGE_UROBOROS          <- 134    
SKILL_MAGE_MOONSHADOW         <- 135    
SKILL_MAGE_SUMMONKRUTA         <- 136    
SKILL_MAGE_REPEATEDSMASHOFRAGE       <- 137    
SKILL_MAGE_SUMMONHEILROM         <- 138    
SKILL_MAGE_SUMMONRAMOS         <- 139    
SKILL_MAGE_BUGFALL          <- 126    
SKILL_ZHAN_LING_QIAN_NENG			<- 96
SKILL_LATENTABILITY				<- 254

SKILL_BOBYBOX <- 208
SKILL_BESTOMASTER <- 209
SKILL_EVILCURIOSITY <- 34
SKILL_CONTROLDOLL <- 70
SKILL_TAILOR <- 71
SKILL_JUMPDOTQUAKE <- 72
SKILL_MADBIGBREAK <- 232
SKILL_MADDEFANCE <- 237
SKILL_MADDOTSHOOT <- 238
SKILL_CIRRUSAREA <- 144
SKILL_CIRRUSCUT <- 145
SKILL_DOLL <- 147
SKILL_ROSECIRRUS <- 141
SKILL_BLOCKFORESTCIRRUS <- 199
SKILL_FATESLAVE <- 222
SKILL_HOTLOVE <- 150
SKILL_SPRLITMAGIC <- 212
SKILL_SORCERESSBUFF <- 128
SKILL_MADBIGDOG <- 236
SKILL_PAINFUGRADEN <- 239
SKILL_TERRIBLEDOT <- 220
SKILL_DOLLFOREST <- 213
SKILL_CIRRUSINDARK <- 33
SKILL_SMALLEVIL <- 32
SKILL_CURSEOFDOT <- 211
SKILL_KEEPOUT <- 225
SKILL_FAVORITE <- 94
SKILL_RELIVE <- 244
 
 
CUSTOM_ANI_MAGE_CHASERCLUSTERBODYSTART_09        <-  82   
CUSTOM_ANI_MAGE_CHASERCLUSTERBODYEND_06         <-  83   
CUSTOM_ANI_MAGE_AVATARDANCE_A           <-  84   
CUSTOM_ANI_MAGE_AVATARDANCE_B           <-  85   
CUSTOM_ANI_MAGE_AVATARDANCE_C           <-  86   
CUSTOM_ANI_MAGE_AVATARDANCE_D           <-  87   
CUSTOM_ANI_MAGE_AVATARDANCE_E01           <-  88   
CUSTOM_ANI_MAGE_AVATARDANCE_E02           <-  89   
CUSTOM_ANI_MAGE_AVATARDANCE_F01           <-  90   
CUSTOM_ANI_MAGE_AVATARDANCE_F02           <-  91   
CUSTOM_ANI_MAGE_NNNEWSWING_BODY           <-  92   
CUSTOM_ANI_MAGE_AVATARREADYA_BODY          <-  93   
CUSTOM_ANI_MAGE_AVATARFINISH_BODY          <-  94   
CUSTOM_ANI_MAGE_AVATAREND_BODY           <-  95   
CUSTOM_ANI_MAGE_BELLANEWCHANGE           <-  96   
CUSTOM_ANI_MAGE_AVATARREADYB_BODY          <-  97   
CUSTOM_ANI_MAGE_QUASAREXPLOSIONCBODY_BODY        <-  98   
CUSTOM_ANI_MAGE_DRAGONSPEARNEW_BODY          <-  99   
    
CUSTOM_ANI_MAGE_ELEMENTALCURTAIN_CAST_BODY     <-  111   
CUSTOM_ANI_MAGE_ELEMENTALCURTAIN_SHOOT_BODY     <-  112   
CUSTOM_ANI_MAGE_ELEMENTALQUAKE_CASTINGSTART_BODY     <-  113   
CUSTOM_ANI_MAGE_ELEMENTALQUAKE_CASTINGLOOPA_BODY     <-  114   
CUSTOM_ANI_MAGE_ELEMENTALQUAKE_CASTINGLOOPB_BODY     <-  115   
CUSTOM_ANI_MAGE_ELEMENTALQUAKE_CASTINGEND_BODY     <-  116   
CUSTOM_ANI_MAGE_CRYSTALOFOVERMIND_SUMMON_BODY     <-  117   
CUSTOM_ANI_MAGE_THEGATECAST_BODY      <-  118   
CUSTOM_ANI_MAGE_SESTOELEMENTOCAST     <-  119   
CUSTOM_ANI_MAGE_SESTOELEMENTOCHARGE     <-  120   
CUSTOM_ANI_MAGE_SESTOELEMENTOREADY     <-  121   
CUSTOM_ANI_MAGE_SESTOELEMENTOEXP      <-  122   
CUSTOM_ANI_MAGE_ELECRABBITSTART      <-  123   
CUSTOM_ANI_MAGE_ELECRABBITLOOP      <-  124   
CUSTOM_ANI_MAGE_ELECRABBITLOOPFAIL     <-  125   
CUSTOM_ANI_MAGE_ELECRABBITEND      <-  126   
CUSTOM_ANI_MAGE_ELECRABBITENDFAIL     <-  127   
CUSTOM_ANI_MAGE_LOLLIPOPCRUSH      <-  128   
CUSTOM_ANI_MAGE_LOLLIPOPCRUSHAIRCAST_BODY     <-  129   
CUSTOM_ANI_MAGE_UROBOROSSTART      <-  130   
CUSTOM_ANI_MAGE_UROBOROSREADY      <-  131   
CUSTOM_ANI_MAGE_UROBOROSIDLE       <-  132   
CUSTOM_ANI_MAGE_JACKFROSTICEWATERCAST_BODY     <-  133   
CUSTOM_ANI_MAGE_JACKFROSTICEWATERSTARTBACK_BODY     <-  134   
CUSTOM_ANI_MAGE_JACKFROSTICEWATERLOOPBACK_BODY     <-  135   
CUSTOM_ANI_MAGE_JACKFROSTICEWATERLOOPBACKBOUNCE01A_BODY        <-  136
CUSTOM_ANI_MAGE_JACKFROSTICEWATERLOOPBACKBOUNCE02_BODY     <-  137   
CUSTOM_ANI_MAGE_MOONSHADOWLAUNCH_BODY     <-  138   
CUSTOM_ANI_MAGE_REPEATEDSMASHOFRAGECHARGE     <-  139   
CUSTOM_ANI_MAGE_REPEATEDSMASHOFRAGESHOOT     <-  140   
CUSTOM_ANI_MAGE_SUMMONRAMOSCAST      <-  141   
CUSTOM_ANI_MAGE_BUGFALLCASTBODYCAST     <-  142   
CUSTOM_ANI_MAGE_BUGFALLCASTBODYSHOOT     <-  143   
CUSTOM_ANI_MAGE_CHAREMOVE     <-  144   
CUSTOM_ANI_MAGE_CHAREDASH     <-  145   
CUSTOM_ANI_MAGE_CHARESTAY     <-  146   
    
CUSTOM_ANI_ELEMENTQUAKE_BOBY0     <- 147
CUSTOM_ANI_ELEMENTQUAKE_BOBY1     <- 148
CUSTOM_ANI_ELEMENTQUAKE_BOBY2     <- 149
CUSTOM_ANI_ELEMENTQUAKE_BOBY3     <- 150
CUSTOM_ANI_DARKSHADOW_CASTING_BOBY     <- 151
CUSTOM_ANI_DARKSHADOW_OUT_BOBY     <- 152
CUSTOM_ANI_AVATARDANCE0     <- 153
CUSTOM_ANI_AVATARDANCE1     <- 154
CUSTOM_ANI_AVATARDANCE2     <- 155
CUSTOM_ANI_AVATARDANCE3     <- 156
CUSTOM_ANI_AVATARDANCE4     <- 157
CUSTOM_ANI_AVATARDANCE5     <- 158
CUSTOM_ANI_AVATARDANCE6     <- 159
CUSTOM_ANI_AVATARDANCE7     <- 160
CUSTOM_ANI_AVATARREADY0     <- 161
CUSTOM_ANI_AVATARREADY1     <- 162
CUSTOM_ANI_AVATARREADY2     <- 163
CUSTOM_ANI_SUPERLOLLY_CASTING     <- 164
CUSTOM_ANI_SUPERLOLLY_ATTACK     <- 165
CUSTOM_ANI_JUMPDOTQUAKE     <- 166
CUSTOM_ANI_MADBIGBREAK     <- 167
CUSTOM_ANI_MADDOTSHOOT     <- 168
CUSTOM_ANI_CIRRUSAREA     <- 169
CUSTOM_ANI_CIRRUSCUT     <- 170
CUSTOM_ANI_ROSECIRRUS     <- 171
CUSTOM_ANI_DOLL     <- 172
CUSTOM_ANI_DOLL_BOBY_START     <- 173
CUSTOM_ANI_DOLL_BOBY_END     <- 174
CUSTOM_ANI_DOLL_MAD_STAY     <- 175
CUSTOM_ANI_DOLL_MAD_MOVE     <- 176
CUSTOM_ANI_DOLL_MAD_DASH     <- 177
CUSTOM_ANI_DOLL_MAD_JUMP     <- 178
CUSTOM_ANI_DOLL_MAD_BUFF     <- 179
CUSTOM_ANI_DOLL_MAD_ATK     <- 180
CUSTOM_ANI_DOLL_MAD_ATK2     <- 181
CUSTOM_ANI_DOLL_MAD_DAM     <- 182
CUSTOM_ANI_DOLL_MAD_DAM2     <- 183
CUSTOM_ANI_DOLL_MAD_DASHATK     <- 184
CUSTOM_ANI_DOLL_MAD_JUMPATK     <- 185
CUSTOM_ANI_DOLL_MAD_THROW     <- 186
CUSTOM_ANI_DOLL_MAD_THROW2     <- 187
CUSTOM_ANI_DOLL_MAD_DOWN     <- 188
CUSTOM_ANI_DOLL_MAD_SIT     <- 189
CUSTOM_ANI_DOLL_BOBY_END0     <- 190
CUSTOM_ANI_DOLL_BOBY_LAST     <- 191
CUSTOM_ANI_BLOCKFORESTCIRRUS_BOBY     <- 192
CUSTOM_ANI_SORCERESSBUFF_CASTING2     <- 193
CUSTOM_ANI_SORCERESSBUFF_START2     <- 194
CUSTOM_ANI_HOTLOVE_BODY     <- 195
CUSTOM_ANI_SPRLITMAGIC_START     <- 196
CUSTOM_ANI_SPRLITMAGIC_LOOP     <- 197
CUSTOM_ANI_SPRLITMAGIC_END     <- 198
CUSTOM_ANI_MADBIGDOG_START     <- 199
CUSTOM_ANI_MADBIGDOG_LOOP     <- 200
CUSTOM_ANI_MADBIGDOG_END     <- 201
CUSTOM_ANI_TERRIBLEDOT_READY     <- 202
CUSTOM_ANI_TERRIBLEDOT_LOOP     <- 203
CUSTOM_PAINFUGRADE_BODY     <- 204
CUSTOM_DOLLFOREST_READY     <- 205
CUSTOM_DOLLFOREST_WAIT      <- 206
CUSTOM_ANI_TAILOR_CASTING     <- 207
CUSTOM_ANI_TAILOR_LOOP     <- 208
CUSTOM_ANI_TAILOR_INMADBIGDOT     <- 209
CUSTOM_ANI_CURSEOFDOT_BOBY     <- 210
CUSTOM_ANI_DOLLFOREST_ATTACKBOX     <- 211
CUSTOM_ANI_DOLLFOREST_FINISH     <- 212
CUSTOM_FATESLAVE_BOBY     <- 213
CUSTOM_KEEPOUT_READY     <- 214
CUSTOM_KEEPOUT_SUCCESS     <- 215
CUSTOM_KEEPOUT_FAIL     <- 216
CUSTOM_KEEPOUT_LAST      <- 217
CUSTOM_FAVORITE_CASTING  <- 218
CUSTOM_FAVORITE_AFTER  <- 219
CUSTOM_ANI_REST_SORICE_BODY  <- 220
CUSTON_ANI_RELIVE_START_BODY  <- 221
CUSTOM_ANI_RELIVE_LOOP_BODY  <- 222
CUSTOM_ANI_RELIVE_END_A  <- 223
CUSTOM_ANI_RELIVE_END_B  <- 224
CUSTOM_ANI_RELIVE_END_C  <- 225
CUSTOM_ANI_JUMP_THROW  <- 226


 
 
CUSTOM_ATTACK_MAGE_CHASERCLUSTERPUSH      <- 38    
CUSTOM_ATTACK_MAGE_AVATARDANCERIGHTSLASH     <- 39    
CUSTOM_ATTACK_MAGE_AVATARDANCELEFTSLASH     <- 40    
CUSTOM_ATTACK_MAGE_AVATARDANCEPUSHATTACK     <- 41    
CUSTOM_ATTACK_MAGE_AVATARDANCEJUMPUPPER     <- 42    
CUSTOM_ATTACK_MAGE_AVATARDANCEDUNKSLASH     <- 43    
CUSTOM_ATTACK_MAGE_AVATARCAST       <- 44    
CUSTOM_ATTACK_MAGE_DRAGONDANCEATTACK      <- 45    
CUSTOM_ATTACK_MAGE_DRAGONDANCEATTACKFINISH    <- 46    
CUSTOM_ATTACK_MAGE_RANDOMPIERCESTRIKELOOPBELLATRIX  <- 47    
CUSTOM_ATTACK_MAGE_RANDOMPIERCESTRIKEFINISHBELLATRIX  <- 48    
CUSTOM_ATTACK_MAGE_LOLLIPOPCRUSH       <- 49    
CUSTOM_ATTACK_MAGE_UROBOROSMULTIHIT      <- 50    
ATTACKINFO_AVATARDANCE0 <- 51
ATTACKINFO_AVATARDANCE1 <- 52
ATTACKINFO_AVATARDANCE2 <- 53
ATTACKINFO_AVATARDANCE3 <- 54
ATTACKINFO_AVATARDANCE4 <- 55
ATTACKINFO_SUPERLLLY <- 56
ATTACKINFO_DOLL_MAD_ATK <- 57
ATTACKINFO_DOLL_MAD_ATK2 <- 58
ATTACKINFO_DOLL_MAD_DASHATK <- 59
ATTACKINFO_DOLL_MAD_JUMPATK <- 60
ATTACKINFO_DOLL_LASTATK <- 61
ATTACKINFO_SPRLITMAGIC <- 62
ATTACKINFO_PAINFUGRADEN <- 63
ATTACKINFO_DOLLFOREST_FIRE <- 64
ATTACKINFO_DOLLFOREST_ONEHAND <- 65
ATTACKINFO_DOLLFOREST_TWOHAND <- 66
ATTACKINFO_KEEPOUT_READY <- 67



 


 
 
PASSIVEOBJ_SUB_STATE_0   <- 10
PASSIVEOBJ_SUB_STATE_1   <- 11
PASSIVEOBJ_SUB_STATE_2   <- 12
PASSIVEOBJ_SUB_STATE_3   <- 13
PASSIVEOBJ_SUB_STATE_4   <- 14
PASSIVEOBJ_SUB_STATE_5   <- 15
PASSIVEOBJ_SUB_STATE_6   <- 16
PASSIVEOBJ_SUB_STATE_7   <- 17
PASSIVEOBJ_SUB_STATE_8   <- 18
PASSIVEOBJ_SUB_STATE_9   <- 19
 


 
 
APID_MAGE_AVATAR_ICON       <- 245    
APID_MAGE_AVATAR         <- 246    
APID_MAGE_SUMMONHEILROM       <- 138    
 


 
 
SOUND_ID_MAGE_AVATAR        <- 9001    
SOUND_ID_MAGE_RAIDP_CHARGE_LOOP     <- 9002    
SOUND_ID_MAGE_WZ_ELEMENTALCURTAIN_01_1   <- 9003    
SOUND_ID_MAGE_WZ_ELEMENTALQUAKE_02_1    <- 9004    
SOUND_ID_MAGE_WZ_CRYSTALOVERMIND_01_1   <- 9005    
SOUND_ID_MAGE_UROBOROS_ROTATE_LOOP    <- 9006    
SOUND_ID_MAGE_JACKFROST_ICEWATER_ROLL_LOOP  <- 9007    

 
 
MONSTER_INDEX_MAGE_SUMMONKRUTA  <- 50680731  
MONSTER_INDEX_MAGE_SUMMONRAMOS  <- 50680732  
MONSTER_INDEX_MAGE_SUMMONHEILROM <- 50680733  

MONSTER_ZPOS_MAGE_SUMMONKRUTA  <- 1111  
MONSTER_ZPOS_MAGE_SUMMONRAMOS  <- 1112  
MONSTER_ZPOS_MAGE_SUMMONHEILROM  <- 1113  
 

MONSTER_ID_RAMOS      <- 77600
MONSTER_ID_KRUTA      <- 77601  
MONSTER_ID_HEILROM      <- 77602    
MONSTER_ID_ECHEVERRA      <- 77603    
MONSTER_ID_SANDOR      <- 77604    
MONSTER_ID_AUXO      <- 77605    
MONSTER_ID_AUXOOLD      <- 77606    
MONSTER_ID_LIGHTHIGHERSPIRIT      <- 77607  
MONSTER_ID_FIREHIGHERSPIRIT      <- 77608    
MONSTER_ID_DARKHIGHERSPIRIT      <- 77609
MONSTER_ID_WATERHIGHERSPIRIT      <- 77610  
MONSTER_ID_LUIS      <- 77612    
MONSTER_ID_BABYDRAGON      <- 77611    
MONSTER_ID_CASILLAS      <- 77613   