
STATE_SAN_DUAN_ZHAN 				<- 22
STATE_GRABBLASTBLOOD				<- 26

STATE_SWORDMAN1					<- 100	
STATE_SWORDMAN2					<- 101	
STATE_SWORDMAN3					<- 102	
STATE_SWORDMAN4					<- 103	
STATE_SWORDMAN5					<- 104	
 
STATE_SWORD_GHOST_1				<- 105	//??????
STATE_SWORD_GHOST_2				<- 106	//????
STATE_SWORD_GHOST_3				<- 107	//?????
STATE_SWORD_GHOST_4				<- 108	//?????
STATE_SWORD_GHOST_5				<- 109	//?????_????
STATE_SWORD_GHOST_6				<- 110	//???????????
STATE_SWORD_GHOST_7				<- 111	//????????
STATE_SWORD_GHOST_8				<- 112	//????????
STATE_SWORD_GHOST_9				<- 113	//???????B
STATE_SWORD_GHOST_10				<- 114	//?????????
STATE_SWORD_GHOST_11				<- 115	//?????
STATE_SWORD_GHOST_12				<- 116	//??????????
STATE_SWORD_GHOST_13				<- 117	//??????@???
STATE_SWORD_GHOST_14				<- 118	//?????:????????
STATE_SWORD_GHOST_15				<- 119	//???z???
STATE_SWORD_GHOST_16				<- 120	//?????:????????
STATE_SWORD_GHOST_17				<- 121	//???:?????
STATE_SWORD_GHOST_18				<- 122	//?????????
STATE_SWORD_GHOST_19				<- 123	//???
STATE_SWORD_GHOST_20				<- 124	//???????????
STATE_SWORD_GHOST_21				<- 125	//???????????
STATE_SWORD_GHOST_22				<- 126	//???
STATE_SWORD_GHOST_23				<- 127	//?????????
STATE_SWORD_GHOST_28				<- 128	//?????
STATE_SWORD_GHOST_29				<- 129	//
STATE_SWORD_GHOST_30				<- 130	//
STATE_TRIPLESLASH_BLADESPIRIT			<- 138
 
STATE_SWORDMAN_BLOODBOOM			<- 229    
STATE_SWORDMAN_BLOODMARBLE			<- 230    
STATE_SWORDMAN_BLOODRIVEN			<- 231    
STATE_SWORDMAN_RAGE					<- 232    
STATE_SWORDMAN_BLOODSNATCH			<- 233    
STATE_SWORDMAN_SWORDOFMIND			<- 234    
STATE_SWORDMAN_METEORSWORD			<- 235    
STATE_SWORDMAN_FLASHCUT				<- 236    
STATE_SWORDMAN_SLASHOFBOOM			<- 237    
STATE_SWORDMAN_SLASHOFHELL			<- 238    
STATE_SWORDMAN_BLADEPHANTOM			<- 239    
STATE_SWORDMAN_BLADEPHANTOMEX		<- 240    
STATE_SWORDMAN_ZIGADVENT				<- 241    
STATE_SWORDMAN_INDARAMANG			<- 242    
STATE_SWORDMAN_VAJRA					<- 243    
STATE_SWORDMAN_LIGHTNINGGOD			<- 244    
STATE_SWORDMAN_FATALBLOOD				<- 245    
STATE_SWORDMAN_HANDLINGSWORD		<- 246    
STATE_SWORDMAN_TOMBSTONESWAMP		<- 247    
STATE_MINGYANJIAN 							<- 249
STATE_FLOW_MIND_ONE_FALL_STATE				<- 147


SKILL_GRABBLASTBLOOD 	<- 31

SKILL_STANDALONEWAVE				<- 62	
SKILL_SWORDMAN_BLOODYVIGOROUS	<- 63  
SKILL_SWORDMAN_SACRIFICE		<- 222  
SKILL_SWORDMAN_BLOODBOOM		<- 229    
SKILL_SWORDMAN_BLOODMARBLE		<- 230    
SKILL_SWORDMAN_BLOODRIVEN		<- 231    
SKILL_SWORDMAN_RAGE				<- 232    
SKILL_SWORDMAN_BLOODSNATCH		<- 233    
SKILL_SWORDMAN_SWORDOFMIND		<- 234    
SKILL_SWORDMAN_METEORSWORD		<- 235    
SKILL_SWORDMAN_FLASHCUT			<- 236    
SKILL_SWORDMAN_SLASHOFBOOM		<- 237    
SKILL_SWORDMAN_SLASHOFHELL		<- 238    
SKILL_SWORDMAN_BLADEPHANTOM	<- 239    
SKILL_SWORDMAN_BLADEPHANTOMEX	<- 240    
SKILL_SWORDMAN_ZIGADVENT			<- 241    
SKILL_SWORDMAN_INDARAMANG		<- 242    
SKILL_SWORDMAN_VAJRA				<- 243    
SKILL_SWORDMAN_LIGHTNINGGOD		<- 244    
SKILL_SWORDMAN_FATALBLOOD		<- 245    
SKILL_SWORDMAN_HANDLINGSWORD	<- 246    
SKILL_SWORDMAN_TOMBSTONESWAMP	<- 247    
SKILL_SWORDMAN_STATEOFLIMIT		<- 248    
SKILL_MINGYANJIAN 					<- 249
SKILL_BLOOD_INKANET					<- 117
SKILL_MYSTICEQUIP						<- 124
SKILL_FORCEOFTHUNDERER				<- 250	
SKILL_DEFANEBLOOD					<- 253
SKILL_LATENTABILITY					<- 254
SKILL_SWORD_GHOST_17				<- 26
SKILL_SWORD_GHOST_16				<- 28
SKILL_SWORD_GHOST_18				<- 45
SKILL_SWORD_GHOST_19				<- 48
SKILL_SWORD_GHOST_20				<- 54
SKILL_SWORD_GHOST_21				<- 59
SKILL_SWORD_GHOST_5					<- 66
SKILL_SWORD_GHOST_13				<- 69
SKILL_SWORD_GHOST_14				<- 70
SKILL_SWORD_GHOST_15				<- 71
SKILL_SWORD_GHOST_28				<- 78
SKILL_SWORD_GHOST_6					<- 83
SKILL_SWORD_GHOST_1					<- 120
SKILL_SWORD_GHOST_2					<- 121
SKILL_SWORD_GHOST_3					<- 122
SKILL_SWORD_GHOST_4					<- 123
SKILL_SWORD_GHOST_7					<- 126
SKILL_SWORD_GHOST_8					<- 127
SKILL_SWORD_GHOST_9					<- 128
SKILL_SWORD_GHOST_22				<- 130
SKILL_SWORD_GHOST_29				<- 132
SKILL_SWORD_GHOST_10				<- 135
SKILL_SWORD_GHOST_11				<- 136
SKILL_SWORD_GHOST_12				<- 137
SKILL_SWORD_GHOST_23				<- 170

SKILL_SWORD_GHOST_24				<- 171
SKILL_SWORD_GHOST_25				<- 209
SKILL_SWORD_GHOST_26				<- 118
SKILL_SWORD_GHOST_27				<- 119


CUSTOM_ANI_GUARD	<- 0
CUSTOM_ANI_HARDATTACK	<- 1
CUSTOM_ANI_HITBACK	<- 2
CUSTOM_ANI_TRIPLESLASH1	<- 3
CUSTOM_ANI_TRIPLESLASH2	<- 4
CUSTOM_ANI_TRIPLESLASH3	<- 5
CUSTOM_ANI_TRIPLESLASH4	<- 6
CUSTOM_ANI_TRIPLESLASH5	<- 7
CUSTOM_ANI_MOMENTARYSLASH	<- 8
CUSTOM_ANI_WAVE	<- 9
CUSTOM_ANI_SWORDMAN_GRAB	<- 10
CUSTOM_ANI_DASHATTACKMULTIHIT	<- 11
CUSTOM_ANI_SHOCKWAVEAREACAST	<- 12
CUSTOM_ANI_SHOCKWAVEAREASMASH	<- 13
CUSTOM_ANI_VANESLASHTRY	<- 14
CUSTOM_ANI_VANESLASH	<- 15
CUSTOM_ANI_UPPERSLASHAFTER	<- 16
CUSTOM_ANI_HARDATTACKCHARGEAFTER	<- 17
CUSTOM_ANI_GHOSTSTEPSLASHREADY	<- 18
CUSTOM_ANI_GHOSTSTEPSLASHMOVE	<- 19
CUSTOM_ANI_STANDALONEWAVEREADY	<- 20
CUSTOM_ANI_STANDALONEWAVEBASIC	<- 21
CUSTOM_ANI_STANDALONEWAVESTRONG	<- 22
CUSTOM_ANI_JUMPATTACKMULTISLASH1	<- 23
CUSTOM_ANI_JUMPATTACKMULTISLASH2	<- 24
CUSTOM_ANI_GORECROSS	<- 25
CUSTOM_ANI_HOPSMASHREADY	<- 26
CUSTOM_ANI_HOPSMASH	<- 27
CUSTOM_ANI_WEAPONCOMBOSHORT1	<- 28
CUSTOM_ANI_WEAPONCOMBOSHORT2	<- 29
CUSTOM_ANI_WEAPONCOMBOSHORT3	<- 30
CUSTOM_ANI_WEAPONCOMBOBLADE1	<- 31
CUSTOM_ANI_WEAPONCOMBOBLADE2	<- 32
CUSTOM_ANI_WEAPONCOMBOBLADE3	<- 33
CUSTOM_ANI_WEAPONCOMBOBLADE4	<- 34
CUSTOM_ANI_WEAPONCOMBOBLUNT1	<- 35
CUSTOM_ANI_WEAPONCOMBOBLUNT2	<- 36
CUSTOM_ANI_WEAPONCOMBOBLUNT3	<- 37
CUSTOM_ANI_WEAPONCOMBOHEAVY1	<- 38
CUSTOM_ANI_WEAPONCOMBOHEAVY2	<- 39
CUSTOM_ANI_WEAPONCOMBOLIGHT1	<- 40
CUSTOM_ANI_WEAPONCOMBOLIGHT2	<- 41
CUSTOM_ANI_WEAPONCOMBOLIGHT3	<- 42
CUSTOM_ANI_CHARGECRASHDASH	<- 43
CUSTOM_ANI_CHARGECRASHUPPER	<- 44
CUSTOM_ANI_CHARGECRASHFINISH	<- 45
CUSTOM_ANI_REFLECTGUARD	<- 46
CUSTOM_ANI_RAPIDMOVESLASHREADY1	<- 47
CUSTOM_ANI_RAPIDMOVESLASHREADY2	<- 48
CUSTOM_ANI_RAPIDMOVESLASHMOVE1	<- 49
CUSTOM_ANI_RAPIDMOVESLASHMOVE2	<- 50
CUSTOM_ANI_ILLUSIONSLASH1	<- 51
CUSTOM_ANI_ILLUSIONSLASH2	<- 52
CUSTOM_ANI_ILLUSIONSLASH3	<- 53
CUSTOM_ANI_ILLUSIONSLASH4	<- 54
CUSTOM_ANI_ILLUSIONSLASHFINAL	<- 55
CUSTOM_ANI_WAVESPINAREABOMB	<- 56
CUSTOM_ANI_FRENZY1	<- 57
CUSTOM_ANI_FRENZY2	<- 58
CUSTOM_ANI_FRENZY3	<- 59
CUSTOM_ANI_FRENZY4	<- 60
CUSTOM_ANI_MOONLIGHTSLASH1	<- 61
CUSTOM_ANI_MOONLIGHTSLASH2	<- 62
CUSTOM_ANI_BLOODYRAVEINHALE	<- 63
CUSTOM_ANI_BLOODYRAVESLASH	<- 64
CUSTOM_ANI_MOONLIGHTSLASHFULL	<- 65
CUSTOM_ANI_OUTRAGEBREAKREADY	<- 66
CUSTOM_ANI_OUTRAGEBREAKSLASH	<- 67
CUSTOM_ANI_KALLALAND	<- 68
CUSTOM_ANI_KALLAAIR	<- 69
CUSTOM_ANI_KALLAFINISHREADY	<- 70
CUSTOM_ANI_KALLAFINISH1	<- 71
CUSTOM_ANI_KALLAFINISH2	<- 72
CUSTOM_ANI_KALLAFINISH3	<- 73
CUSTOM_ANI_HELLBENTERFINISH	<- 74
CUSTOM_ANI_HUNDREDSWORDREADY	<- 75
CUSTOM_ANI_HUNDREDSWORDMOVEREADY1	<- 76
CUSTOM_ANI_HUNDREDSWORDMOVEREADY2	<- 77
CUSTOM_ANI_HUNDREDSWORDMOVEREADY3	<- 78
CUSTOM_ANI_HUNDREDSWORDMOVEREADY4	<- 79
CUSTOM_ANI_HUNDREDSWORDMOVEREADY5	<- 80
CUSTOM_ANI_HUNDREDSWORDMOVESLASH1	<- 81
CUSTOM_ANI_HUNDREDSWORDMOVESLASH2	<- 82
CUSTOM_ANI_HUNDREDSWORDMOVESLASH3	<- 83
CUSTOM_ANI_HUNDREDSWORDMOVESLASH4	<- 84
CUSTOM_ANI_HUNDREDSWORDMOVESLASH5	<- 85
CUSTOM_ANI_HUNDREDSWORDFINISH	<- 86
CUSTOM_ANI_BLACHECAST	<- 87
CUSTOM_ANI_BLACHESMASH	<- 88
CUSTOM_ANI_WAVEEYECAST	<- 89
CUSTOM_ANI_WAVEEYESTART	<- 90
CUSTOM_ANI_WAVEEYEATTACK1	<- 91
CUSTOM_ANI_WAVEEYEATTACK2	<- 92
CUSTOM_ANI_WAVEEYEATTACK3	<- 93
CUSTOM_ANI_WAVEEYECLAW	<- 94
CUSTOM_ANI_WAVEEYEWING	<- 95
CUSTOM_ANI_WAVEEYESPEAR	<- 96
CUSTOM_ANI_TOMBSTONEEX	<- 97
CUSTOM_ANI_MOMENTARYSLASHEX	<- 98
CUSTOM_ANI_CHARGECRASHEXSHOULDER	<- 99
CUSTOM_ANI_CHARGECRASHEXPICK	<- 100
CUSTOM_ANI_CHARGECRASHEXUPPER	<- 101
CUSTOM_ANI_BLOODSWORDMAKE	<- 102
CUSTOM_ANI_BLOODSWORDCHARGE	<- 103
CUSTOM_ANI_FLOWMINDSTART	<- 104
CUSTOM_ANI_FLOWMINDSTAY	<- 105
CUSTOM_ANI_FLOWMINDONE	<- 106
CUSTOM_ANI_FLOWMINDONEADD	<- 107
CUSTOM_ANI_FLOWMINDTWOJUMP	<- 108
CUSTOM_ANI_FLOWMINDTWOLANDING	<- 109
CUSTOM_ANI_FLOWMINDTWOATTACK1	<- 110
CUSTOM_ANI_FLOWMINDTWOATTACK2	<- 111
CUSTOM_ANI_FLOWMINDTHREEREADY	<- 112
CUSTOM_ANI_FLOWMINDTHREEATTACK	<- 113
CUSTOM_ANI_STAYSACRIFICE	<- 114
CUSTOM_ANI_SPIRITATTACK1	<- 115
CUSTOM_ANI_SPIRITATTACK2	<- 116
CUSTOM_ANI_SPIRITATTACK3	<- 117
CUSTOM_ANI_SPIRITATTACK4	<- 118
CUSTOM_ANI_SPIRITDASHATTACK	<- 119
CUSTOM_ANI_GHOSTSIDEWIND	<- 120
CUSTOM_ANI_TRIPLESTAB	<- 121
CUSTOM_ANI_SWORDMAN_BLOODBOOM	<- 122
CUSTOM_ANI_SWORDMAN_BLOODRIVENCAST	<- 123
CUSTOM_ANI_SWORDMAN_BLOODRIVENCHARGE	<- 124
CUSTOM_ANI_SWORDMAN_BLOODRIVENCHANGE	<- 125
CUSTOM_ANI_SWORDMAN_BLOODRIVENJUMP	<- 126
CUSTOM_ANI_SWORDMAN_BLOODRIVENFINISH	<- 127
CUSTOM_ANI_SWORDMAN_BLOODMARBLEEXTRACTREADY_BODY	<- 128
CUSTOM_ANI_SWORDMAN_RAGESTARTBODY_BODY	<- 129
CUSTOM_ANI_SWORDMAN_RAGELOOP01BODY_BODY	<- 130
CUSTOM_ANI_SWORDMAN_RAGELOOP02BODY_BODY	<- 131
CUSTOM_ANI_SWORDMAN_RAGELOOP03BODY_BODY	<- 132
CUSTOM_ANI_SWORDMAN_RAGELOOP04BODY_BODY	<- 133
CUSTOM_ANI_SWORDMAN_RAGEENDBODY_BODY	<- 134
CUSTOM_ANI_SWORDMAN_BLOODSNATCHCAST_BODY  	<- 135
CUSTOM_ANI_SWORDMAN_BLOODSNATCHDASH_BODY  	<- 136
CUSTOM_ANI_SWORDMAN_BLOODSNATCHCATCH_BODY  	<- 137
CUSTOM_ANI_SWORDMAN_BLOODSNATCHDASHCATCH_BODY 	<- 138
CUSTOM_ANI_SWORDMAN_BLOODSNATCHSPIN_BODY  	<- 139
CUSTOM_ANI_SWORDMAN_BLOODSNATCHFINISH_BODY  	<- 140
CUSTOM_ANI_SWORDMAN_SWORDOFMINDCHARGE	<- 141
CUSTOM_ANI_SWORDMAN_SWORDOFMINDCHARGEATTRACT 	<- 142
CUSTOM_ANI_SWORDMAN_SWORDOFMINDCHARGEATTACK  	<- 143
CUSTOM_ANI_SWORDMAN_METEORSWORDSTART	<- 144
CUSTOM_ANI_SWORDMAN_METEORSWORDCHARGE	<- 145
CUSTOM_ANI_SWORDMAN_METEORSWORDCHARGEFINISH  	<- 146
CUSTOM_ANI_SWORDMAN_METEORSWORDUP	<- 147
CUSTOM_ANI_SWORDMAN_METEORSWORDDROP	<- 148
CUSTOM_ANI_SWORDMAN_METEORSWORDEXPLOSION  	<- 149
CUSTOM_ANI_SWORDMAN_FLASHCUTREADY_BODY	<- 150
CUSTOM_ANI_SWORDMAN_FLASHCUTATK_BODY	<- 151
CUSTOM_ANI_SWORDMAN_FLASHCUTEND_BODY	<- 152
CUSTOM_ANI_SWORDMAN_SLASHOFBOOM_READY	<- 153
CUSTOM_ANI_SWORDMAN_SLASHOFBOOM_ATTACK	<- 154
CUSTOM_ANI_SWORDMAN_SLASHOFHELL	<- 155
CUSTOM_ANI_SWORDMAN_BLADEPHANTOMEX_CAST_BODY 	<- 156
CUSTOM_ANI_SWORDMAN_BLADEPHANTOMEX_JUMP_BODY 	<- 157
CUSTOM_ANI_SWORDMAN_BLADEPHANTOMEX_SLASH_BODY 	<- 158
CUSTOM_ANI_SWORDMAN_ZIGADVENT_NEW	<- 159
CUSTOM_ANI_SWORDMAN_INDARAMANG	<- 160
CUSTOM_ANI_SWORDMAN_VAJRACAST	<- 161
CUSTOM_ANI_SWORDMAN_VAJRAFINISH	<- 162
CUSTOM_ANI_SWORDMAN_LIGHTNINGGOD	<- 163
CUSTOM_ANI_SWORDMAN_FATALBLOOD1HIT_BODY	<- 164
CUSTOM_ANI_SWORDMAN_FATALBLOOD2HIT_BODY	<- 165
CUSTOM_ANI_SWORDMAN_FATALBLOOD3HIT_BODY	<- 166
CUSTOM_ANI_SWORDMAN_FATALBLOOD3HITFAIL_BODY  	<- 167
CUSTOM_ANI_SWORDMAN_HANDLINGSWORD_SRART_BODY 	<- 168
CUSTOM_ANI_SWORDMAN_TOMBSTONESWAMP_BODY	<- 169

CUSTOM_ANI_MINGYANJIAN_READY	<- 171
CUSTOM_ANI_MINGYANJIAN_ONE	<- 172
CUSTOM_ANI_MINGYANJIAN_TWO	<- 173
CUSTOM_ANI_MINGYANJIAN_THREE	<- 174
CUSTOM_ANI_MINGYANJIAN_END	<- 175
CUSTOM_ANI_FLOW_MIND_ONE_FALL_STATE	<- 176
CUSTOM_ANI_FLOW_MIND_ONE_FALL_ONE	<- 177
CUSTOM_ANI_FLOW_MIND_ONE_FALL_TWO	<- 178
CUSTOM_ANI_FLOW_MIND_ONE_FALL_STATE_END	<- 188
CUSTOM_ANI_ZIGADVENT_NEW	<- 179

CUSTOM_ANI_SWORD_GHOST_12_YG_MANY_ATTACK	<- 126

CUSTOM_ANI_THROW	<- 182
CUSTOM_ANI_THROW2	<- 183
CUSTOM_ANI_YIN_READY	<- 184
CUSTOM_ANI_YIN_ATTACK_0	<- 185
CUSTOM_ANI_YIN_ATTACK_1	<- 186
CUSTOM_ANI_YIN_ATTACK_2	<- 187
CUSTOM_ANI_ATTACK1	<- 188
CUSTOM_ANI_ATTACK2	<- 189
CUSTOM_ANI_ATTACK3	<- 190
CUSTOM_ANI_SANGUANGCHONGFENG_R	<- 191
CUSTOM_ANI_SANGUANGCHONGFENG_A1	<- 192
CUSTOM_ANI_SANGUANGCHONGFENG_END	<- 193
CUSTOM_ANI_NULL	<- 194
CUSTOM_ANI_NULL	<- 195
CUSTOM_ANI_WANXIANGJIANZHEN	<- 196
CUSTOM_ANI_XUESETULI_START	<- 197
CUSTOM_ANI_XUESETULI_ATK1	<- 198
CUSTOM_ANI_XUESETULI_ATK2	<- 199
CUSTOM_ANI_XUESETULI_ATK3	<- 200
CUSTOM_ANI_XUESETULI_END	<- 201
CUSTOM_ANI_UP_ATTACK	<- 202
CUSTOM_ANI_BACK_JUMP	<- 203
CUSTOM_ANI_GHOST_CHANGE_CAST	<- 204
CUSTOM_ANI_GHOST_CHANGE_END	<- 205
CUSTOM_ANI_GHOST_CHANGE_DARK_ATTACK1	<- 206
CUSTOM_ANI_GHOST_CHANGE_DARK_ATTACK2	<- 207
CUSTOM_ANI_GHOST_CHANGE_RAD_ATTACK1	<- 208
CUSTOM_ANI_GHOST_CHANGE_RAD_ATTACK2	<- 209
CUSTOM_ANI_SWORD_GHOST_NONE_ATTACK1	<- 210
CUSTOM_ANI_SWORD_GHOST_NONE_ATTACK2	<- 211
CUSTOM_ANI_SWORD_GHOST_NONE_ATTACK3	<- 212
CUSTOM_ANI_SWORD_GHOST_NONE_ATTACK4	<- 213
CUSTOM_ANI_SWORD_GHOST_NONE_DASH	<- 214
CUSTOM_ANI_SWORD_GHOST_NONE_JUMP	<- 215
CUSTOM_ANI_SWORD_GHOST_7_GSB_START	<- 216
CUSTOM_ANI_SWORD_GHOST_7_GSB_MOVE	<- 217
CUSTOM_ANI_SWORD_GHOST_8_GLS_ATK1	<- 218
CUSTOM_ANI_SWORD_GHOST_8_GLS_ATK2	<- 219
CUSTOM_ANI_SWORD_GHOST_8_GLS_ATK3	<- 220
CUSTOM_ANI_SWORD_GHOST_8_GLS_ATK4	<- 221
CUSTOM_ANI_SWORD_GHOST_10_YG_ONE_ATTACK	<- 222
CUSTOM_ANI_SWORD_GHOST_11_LY_CAST	<- 223
CUSTOM_ANI_SWORD_GHOST_11_LY_ATTACK	<- 224
CUSTOM_ANI_SWORD_GHOST_11_LY_END	<- 225
CUSTOM_ANI_SWORD_GHOST_15_HUN_PO_CAST	<- 226
CUSTOM_ANI_SWORD_GHOST_15_HUN_PO_ATTACK	<- 227
CUSTOM_ANI_SWORD_GHOST_5_HE_JI_ONE_ATTACK_A	<- 228
CUSTOM_ANI_SWORD_GHOST_5_HE_JI_ONE_ATTACK_B	<- 229
CUSTOM_ANI_SWORD_GHOST_5_HE_JI_ONE_END	<- 230
CUSTOM_ANI_SWORD_GHOST_16_HE_JI_YUE_LIN_ATTACK1	<- 231
CUSTOM_ANI_SWORD_GHOST_16_HE_JI_YUE_LIN_ATTACK2	<- 232
CUSTOM_ANI_SWORD_GHOST_18_ER_GUI_ZHAN_SHOU_R_ATTACK	<- 233
CUSTOM_ANI_SWORD_GHOST_18_ER_GUI_ZHAN_SHOU_A_ATTACK	<- 234
CUSTOM_ANI_SWORD_GHOST_19_YI_JUE_CAST	<- 235
CUSTOM_ANI_SWORD_GHOST_19_YI_JUE_ATTACK	<- 236
CUSTOM_ANI_SWORD_GHOST_14_NAI_LUO_ATTACK	<- 237
CUSTOM_ANI_SWORD_GHOST_22_ER_JUE_START	<- 238
CUSTOM_ANI_SWORD_GHOST_22_ER_JUE_ATTACK	<- 239
CUSTOM_ANI_SWORD_GHOST_23_LIAN_WU_ATTACK1	<- 240
CUSTOM_ANI_SWORD_GHOST_23_LIAN_WU_ATTACK2	<- 241
CUSTOM_ANI_SWORD_GHOST_23_LIAN_WU_ATTACK3	<- 242
CUSTOM_ANI_SWORD_GHOST_23_LIAN_WU_ATTACK4	<- 243
CUSTOM_ANI_SWORD_GHOST_13_BUFF	<- 244
CUSTOM_ANI_SWORD_BACK_JUMP_START	<- 245
CUSTOM_ANI_SWORD_BACK_JUMP_RUN	<- 246
CUSTOM_ANI_SWORD_BACK_JUMP_END	<- 247
CUSTOM_ANI_SWORD_GHOST_18_ER_GUI_ZHAN_SHOU_EX_MOVE	<- 248
CUSTOM_ANI_SWORD_GHOST_18_ER_GUI_ZHAN_SHOU_EX_ATTACK	<- 249
CUSTOM_ANI_SWORD_GHOST_28_GHOST_REN_1	<- 250
CUSTOM_ANI_SWORD_GHOST_28_GHOST_REN_2	<- 251
CUSTOM_ANI_SWORD_GHOST_29_GHOST_KUANGHUAN_00_START	<- 252
CUSTOM_ANI_SWORD_GHOST_29_GHOST_KUANGHUAN_01_JUMP	<- 253
CUSTOM_ANI_SWORD_GHOST_29_GHOST_KUANGHUAN_02_DASH	<- 254
CUSTOM_ANI_SWORD_GHOST_29_GHOST_KUANGHUAN_03_ATTACK2	<- 255
CUSTOM_ANI_SWORD_GHOST_29_GHOST_KUANGHUAN_04_ATTACK3	<- 256
CUSTOM_ANI_SWORD_GHOST_29_GHOST_KUANGHUAN_05_ATTACK4	<- 257
CUSTOM_ANI_SWORD_GHOST_29_GHOST_KUANGHUAN_06_ATTACK5	<- 258
CUSTOM_ANI_SWORD_GHOST_29_GHOST_KUANGHUAN_06_ATTACK6	<- 259
CUSTOM_ANI_SWORD_GHOST_29_GHOST_KUANGHUAN_06_ATTACK7	<- 260
CUSTOM_ANI_SWORD_GHOST_30_YASUO_Q_ATTACK	<- 261
CUSTOM_ANI_TRIPLESLASH_BLADESPIRIT1						<- 262
CUSTOM_ANI_TRIPLESLASH_BLADESPIRIT2						<- 263
CUSTOM_ANI_TRIPLESLASH_BLADESPIRIT3						<- 264

//CUSTOM_ATK??????????????????-------------------------------------------------------
CUSTOM_ATK_YIN_READY				<- 105
CUSTOM_ATK_YIN_END				<- 106
CUSTOM_ATK_SWORD_GHOST_NONE_ATTACK1				<- 107
CUSTOM_ATK_SWORD_GHOST_NONE_ATTACK2				<- 108
CUSTOM_ATK_SWORD_GHOST_NONE_ATTACK3				<- 109
CUSTOM_ATK_SWORD_GHOST_NONE_ATTACK4				<- 110
CUSTOM_ATK_GHOST_CHANGE_DARK_ATTACK1				<- 111
CUSTOM_ATK_GHOST_CHANGE_DARK_ATTACK2				<- 112
CUSTOM_ATK_GHOST_CHANGE_RAD_ATTACK1				<- 113
CUSTOM_ATK_GHOST_CHANGE_RAD_ATTACK2				<- 114
CUSTOM_ATK_SWORD_GHOST_7_GSB_MOVE_ATTACK				<- 115
CUSTOM_ATK_SWORD_GHOST_8_GLS_ATK1				<- 116
CUSTOM_ATK_SWORD_GHOST_8_GLS_ATK2				<- 117
CUSTOM_ATK_SWORD_GHOST_8_GLS_ATK3				<- 118
CUSTOM_ATK_SWORD_GHOST_8_GLS_ATK4				<- 119
CUSTOM_ATK_SWORD_GHOST_11_LY_ATK				<- 120
CUSTOM_ATK_SWORD_GHOST_15_HUN_PO_ATTACK				<- 121
CUSTOM_ATK_SWORD_GHOST_5_HE_JI_ONE_ATTACK1				<- 122
CUSTOM_ATK_SWORD_GHOST_5_HE_JI_ONE_ATTACK2				<- 123
CUSTOM_ATK_SWORD_GHOST_5_HE_JI_ONE_ATTACK3				<- 124
CUSTOM_ATK_SWORD_GHOST_16_HE_JI_YUE_LIN_ATTACK1				<- 125
CUSTOM_ATK_SWORD_GHOST_16_HE_JI_YUE_LIN_ATTACK2				<- 126
CUSTOM_ATK_SWORD_GHOST_18_ER_GUI_ZHAN_SHOU_R_ATTACK				<- 127
CUSTOM_ATK_SWORD_GHOST_18_ER_GUI_ZHAN_SHOU_A_ATTACK				<- 128
CUSTOM_ATK_SWORD_GHOST_19_YI_JUE_ATTACK				<- 129
CUSTOM_ATK_SWORD_GHOST_14_NAI_LUO_ATTACK				<- 130
CUSTOM_ATK_SWORD_GHOST_22_ER_JUE_ATTACK1				<- 131
CUSTOM_ATK_SWORD_GHOST_22_ER_JUE_ATTACK2				<- 132
CUSTOM_ATK_SWORD_GHOST_22_ER_JUE_ATTACK3				<- 133
CUSTOM_ATK_SWORD_GHOST_22_ER_JUE_ATTACK4				<- 134
CUSTOM_ATK_SWORD_GHOST_22_ER_JUE_ATTACK5				<- 135
CUSTOM_ATK_SWORD_GHOST_23_LIAN_WU_ATTACK1				<- 136
CUSTOM_ATK_SWORD_GHOST_23_LIAN_WU_ATTACK2				<- 137
CUSTOM_ATK_SWORD_GHOST_23_LIAN_WU_ATTACK3				<- 138
CUSTOM_ATK_SWORD_GHOST_23_LIAN_WU_ATTACK4				<- 139
CUSTOM_ATK_SWORD_GHOST_28_GHOST_REN_1				<- 140
CUSTOM_ATK_SWORD_GHOST_30_YASUO_ATTACK				<- 141
CUSTOM_ATTACK_INFO_TRIPLESLASH_BLADESPIRIT1				<- 142
CUSTOM_ATTACK_INFO_TRIPLESLASH_BLADESPIRIT2				<- 143
CUSTOM_ATTACK_INFO_TRIPLESLASH_BLADESPIRIT3				<- 144
 
CUSTOM_ATTACK_SWORDMAN_BLOODRIVENMULTIHIT     <- 87    
CUSTOM_ATTACK_SWORDMAN_BLOODRIVENCHARGEHIT     <- 88    
CUSTOM_ATTACK_SWORDMAN_RAGE_ATK3       <- 89    
CUSTOM_ATTACK_SWORDMAN_BLOODSNATCH       <- 90    
CUSTOM_ATTACK_SWORDMAN_SWORDOFMINDATTACK     <- 91    
CUSTOM_ATTACK_SWORDMAN_METEORSWORDEXPLOSION     <- 92    
CUSTOM_ATTACK_SWORDMAN_FLASHCUTDELAYATTACK     <- 93    
CUSTOM_ATTACK_SWORDMAN_FLASHCUTDELAYATTACKFINISH   <- 94    
CUSTOM_ATTACK_SWORDMAN_SLASHOFHELL       <- 95    
CUSTOM_ATTACK_SWORDMAN_FATALBLOOD1HIT      <- 96    
CUSTOM_ATTACK_SWORDMAN_FATALBLOOD2HIT      <- 97    
CUSTOM_ATTACK_SWORDMAN_FATALBLOOD3HIT      <- 98    
CUSTOM_ATTACK_SWORDMAN_FATALBLOOD4HIT      <- 99    
ATTACKINFO_MINGYANJIAN_ONE <- 101
ATTACKINFO_MINGYANJIAN_TWO <- 102
ATTACKINFO_MINGYANJIAN_THREE <- 103
ATTACKINFO_MINGYANJIAN_END <- 104
 

//?????????????-------------------------------------------------------
VECTOR_FLAG_0	<- 0
VECTOR_FLAG_1	<- 1
VECTOR_FLAG_2	<- 2
VECTOR_FLAG_3	<- 3
VECTOR_FLAG_4	<- 4
VECTOR_FLAG_5	<- 5

SKL_STATIC_INT_IDX_0	<- 0
SKL_STATIC_INT_IDX_1	<- 1
SKL_STATIC_INT_IDX_2	<- 2
SKL_STATIC_INT_IDX_3	<- 3
SKL_STATIC_INT_IDX_4	<- 4
SKL_STATIC_INT_IDX_5	<- 5
SKL_STATIC_INT_IDX_6	<- 6
SKL_STATIC_INT_IDX_7	<- 7
SKL_STATIC_INT_IDX_8	<- 8

SKL_LVL_COLUMN_IDX_0	<- 0
SKL_LVL_COLUMN_IDX_1	<- 1
SKL_LVL_COLUMN_IDX_2	<- 2
SKL_LVL_COLUMN_IDX_3	<- 3
SKL_LVL_COLUMN_IDX_4	<- 4
SKL_LVL_COLUMN_IDX_5	<- 5
SKL_LVL_COLUMN_IDX_6	<- 6
 
SKL_LV_0 <- 0 
SKL_LV_1 <- 1 
SKL_LV_2 <- 2 
SKL_LV_3 <- 3 
SKL_LV_4 <- 4 
 
CREATOR_TYPE_NONE <- 0
CREATOR_TYPE_FLAME	<- 1
CREATOR_TYPE_ICE	<- 2
CREATOR_TYPE_DISTURB	<- 3
CREATOR_TYPE_GUARDIAN	<- 4
CREATOR_TYPE_WIND	<- 5
CREATOR_TYPE_MAX	<- 6


 
PASSIVEOBJ_SUB_STATE_0        <- 10
PASSIVEOBJ_SUB_STATE_1        <- 11
PASSIVEOBJ_SUB_STATE_2        <- 12
PASSIVEOBJ_SUB_STATE_3        <- 13
PASSIVEOBJ_SUB_STATE_4        <- 14
PASSIVEOBJ_SUB_STATE_5        <- 15
PASSIVEOBJ_SUB_STATE_6        <- 16
PASSIVEOBJ_SUB_STATE_7        <- 17
 


 
 
APID_SWORDMAN_HANDLINGSWORD         <- 229   
 
SKILL_GHOST_SOUL_RELEASE			<- 131
STATE_HERO							<- 132
SKILL_HERO							<- 132

STATE_ZIG			<-189
SKILL_ZIG				<-125
