

 
 

 
STATE_PRIEST_TEST   <- 60  
STATE_SPINCUTTER   <- 61    
STATE_PRIEST_SCYTHE_MASTERY <- 62  
STATE_HEDGEHOG    <- 63  
STATE_FASTMOVE    <- 64    
STATE_RIPPER    <- 65  
STATE_EARTHQUAKE   <- 66  
STATE_AVENGER_AWAKENING  <- 67  
STATE_EXECUTION    <- 68  

STATE_AWAKENING_TURN_OFF <- 69  
STATE_HIGH_SPEED_SPLASH  <- 70    
STATE_POWER_OF_DARKNESS  <- 71  
STATE_FALLING_SOUL   <- 72  

STATE_PANDEMONIUM_EX  <- 73  
STATE_EX_DISASTER   <- 74  
STATE_AVENGER_GUARD			<- 75

 
SKILL_CHANGE_HP_TO_MP  <- 10  
SKILL_SPINCUTTER   <- 113  
SKILL_SCYTHE_MASTERY  <- 114  
SKILL_FASTMOVE    <- 115  
SKILL_HEDGEHOG    <- 116  
SKILL_RIPPER    <- 117  
SKILL_EARTH_QUAKE   <- 118  
SKILL_AVENGER_AWAKENING  <- 119   
SKILL_EXECUTION    <- 120  
SKILL_HEARTHINGS   <- 121  
SKILL_NIGHTMARE     <- 122  
SKILL_DEVILSTRIKE   <- 123   
SKILL_HIGH_SPEED_SLASH  <- 124  
SKILL_POWER_OF_DARKNESS  <- 125  

SKILL_CANCEL_FASTMOVE   <- 127  
SKILL_CANCEL_HIGH_SPEED_SLASH <- 128  
SKILL_CANCEL_EARTH_QUAKE  <- 129  
SKILL_AVENGER_GUARD   <- 130  
SKILL_FALLING_SOUL    <- 131  
SKILL_CANCEL_SPINCUTTER   <- 132  

SKILL_PANDEMONIUM_EX   <- 133  

SKILL_EX_DISASTER   <- 134  

SKILL_FASTMOVE_EX   <- 164  
SKILL_RIPPER_EX    <- 165  

 
CUSTOM_ANI_SPINCUTTER1  <- 79   
CUSTOM_ANI_SPINCUTTER2  <- 80  
CUSTOM_ANI_SPINCUTTER3  <- 81   
CUSTOM_ANI_FASTMOVE1  <- 82   
CUSTOM_ANI_FASTMOVE2  <- 83   
CUSTOM_ANI_FASTMOVE3  <- 84   
CUSTOM_ANI_FASTMOVE4  <- 85   
 
CUSTOM_ANI_AVENGER_AWAKENING1 <- 86    
CUSTOM_ANI_AVENGER_AWAKENING2 <- 87    
CUSTOM_ANI_AVENGER_AWAKENING3 <- 88    
CUSTOM_ANI_AVENGER_AWAKENING4 <- 89    
CUSTOM_ANI_HEDGEHOG    <- 90    
CUSTOM_ANI_RIPPER     <- 91    
CUSTOM_ANI_EARTH_QUAKE    <- 92    

CUSTOM_ANI_EXC_GRAB    <- 93    
CUSTOM_ANI_EXC_GRAB_EX   <- 94    
CUSTOM_ANI_EXC_TURNOVER   <- 95    
CUSTOM_ANI_EXC_RUN     <- 96    
CUSTOM_ANI_EXC_LAST    <- 97    
CUSTOM_ANI_EXC_FAILED    <- 98    

CUSTOM_ANI_AWAKENING_TURN_OFF <- 99    

CUSTOM_ANI_HIGH_SPEED_READY  <- 100    
CUSTOM_ANI_HIGH_SPEED_ATTACK_1 <- 101    
CUSTOM_ANI_HIGH_SPEED_ATTACK_2 <- 102    
CUSTOM_ANI_HIGH_SPEED_ATTACK_3 <- 103    
CUSTOM_ANI_HIGH_SPEED_ATTACK_4 <- 104    
CUSTOM_ANI_HIGH_SPEED_LAST  <- 105    

CUSTOM_ANI_AVENGER_ATTACK_1  <- 106    
CUSTOM_ANI_AVENGER_ATTACK_2  <- 107    
CUSTOM_ANI_AVENGER_ATTACK_3  <- 108    
CUSTOM_ANI_AVENGER_ATTACK_4_SCYTHE  <- 109    
CUSTOM_ANI_AVENGER_ATTACK_4_ROSARY  <- 110    

CUSTOM_ANI_POWER_OF_DARKNESS_START <- 111    
CUSTOM_ANI_POWER_OF_DARKNESS_STAY <- 112    
CUSTOM_ANI_POWER_OF_DARKNESS_END <- 113    

CUSTOM_ANI_AWAKENING_TURN_OFF_2  <- 114    

CUSTOM_ANI_PANDEMONIUM_START  <- 115    
CUSTOM_ANI_PANDEMONIUM_END  <- 116    

CUSTOM_ANI_EX_DISASTER_1  <- 117    
CUSTOM_ANI_EX_DISASTER_2  <- 118    
CUSTOM_ANI_EX_DISASTER_3  <- 119    
CUSTOM_ANI_EX_DISASTER_4  <- 120    
CUSTOM_ANI_EX_DISASTER_5  <- 121    



 
CUSTOM_ATTACKINFO_SPINCUTTER   <- 70    
CUSTOM_ATTACKINFO_FASTMOVE  <- 71    
CUSTOM_ATTACKINFO_HEDGEHOG  <- 72    
CUSTOM_ATTACKINFO_RIPPER  <- 73    

CUSTOM_ATTACKINFO_EXCUTION_1  <- 74     
CUSTOM_ATTACKINFO_EXCUTION_2  <- 75    
CUSTOM_ATTACKINFO_EXCUTION_3  <- 76    
CUSTOM_ATTACKINFO_EXCUTION_4  <- 77    
CUSTOM_ATTACKINFO_EXCUTION_5  <- 78    
CUSTOM_ATTACKINFO_EXCUTION_6  <- 79    

CUSTOM_ATTACKINFO_AW_ATTACK1  <- 80    
CUSTOM_ATTACKINFO_AW_ATTACK2  <- 81    
CUSTOM_ATTACKINFO_AW_ATTACK3  <- 82    
CUSTOM_ATTACKINFO_AW_ATTACK4  <- 83    


CUSTOM_ATTACKINFO_AW_DASHATTACK  <- 84    
CUSTOM_ATTACKINFO_RIPPER_EXPLOSION <-85
CUSTOM_ATTACKINFO_HIGH_SPEED_SLASH <-86    

CUSTOM_ATTACKINFO_AVENGER_ATTACK_1 <-87
CUSTOM_ATTACKINFO_AVENGER_ATTACK_2 <-88
CUSTOM_ATTACKINFO_AVENGER_ATTACK_3 <-89
CUSTOM_ATTACKINFO_AVENGER_ATTACK_4 <-90

CUSTOM_ATTACKINFO_HIGH_SPEED_SLASH_LAST <-91    
CUSTOM_ATTACKINFO_POWER_OF_DARKNESS <- 92

CUSTOM_ATTACKINFO_AVENGER_ATTACK_3_2 <-93  
CUSTOM_ATTACKINFO_AVENGER_ATTACK_4_2 <-94  

CUSTOM_ATTACKINFO_DISASTER <-95  

CUSTOM_ATTACKINFO_PANDEMONIUM_EX_ON_START <- 96   
CUSTOM_ATTACKINFO_AWAKENING_PANDEMONIUM_START <- 97  


E_ATTACK_COMMAND <- 0
E_JUMP_COMMAND <- 1
E_DASH_COMMANDS_1 <- 2
E_DASH_COMMANDS_2 <- 3
E_CREATURE_COMMAND <- 4
E_BUFF_COMMAND <- 5
E_SKILL_COMMAND <- 6
E_COMMAND_COUNT <- 7

 
SI_DS_MAX_DEVIL_GAUGE <- 0  
 
SI_DS_ATTACK <- 1  
SI_DS_JUMP_ATTACK <- 2  
SI_DS_DASH_ATTACK <- 3  
SI_DS_DG_ATTACK <- 4  
SI_DS_DG_DASH_ATTACK <- 5  
SI_DS_DG_JUMP_ATTACK <- 6  
SI_DS_HIGH_SPEED_SLASH <- 7  
SI_DS_GRASP_HANDOFANGER <- 8  
SI_DS_CHANGE_HPTOMP <- 9  
SI_DS_EARTH_QUAKE <- 10  
SI_DS_SPINCUTTER <- 11  
SI_DS_HEDGEHOG <- 12  
SI_DS_FASTMOVE <- 13  
SI_DS_RIPPER <- 14  
SI_DS_EXECUTION <- 15  
SI_DS_DARK <- 16  
SI_DS_COOLTIME <- 17  
SI_DS_ANTIAIR_UPPER <- 18  
SI_DS_SMASHER <- 19 
SI_DS_SLOW_HEAL <- 20  
SI_DS_LUCKY_STRAIGHT <- 21  
SI_DS_STRIKING <- 22  
SI_DS_CURE <- 23  
SI_DS_SKILL_SECOND_UPPER <- 24  
SI_DS_BLESS <- 25  
SI_DS_QUAKE_AREA <- 26  
SI_DS_RISING_AREA <- 27  
SI_DS_DISASTER <- 28  
SI_DS_PANDEMONI <- 29  
 


 
I_AVENGER_AWAKENING_TIME <- 0  
I_DOOMS_HP <- 1  
I_AVENGER_AWAKENING_VALID <- 2 
 
 
 
 
