


 
 
STATE_SUPPRESS <- 211 //��޺ : ���
STATE_AIMSHOOT <- 212 //?����̪
STATE_BASHSTOCK <- 213 //����?̪
STATE_BURSTBOMB <- 214 //����״��
STATE_BODYBUNKER <- 215 //��޺ : ��������
STATE_NEODYMIUMFUSEE <- 216 //�������
STATE_TRIPLEGUNSHOT <- 217 //߲֧߬��
STATE_MCPICE <- 218 //��֮ޫ?
STATE_BREACHINGDOWN <- 219 //��޺ : Ѧ������
STATE_SCORCHTACTICS <- 220 //��������
STATE_DIRECTFEEDBACK <- 221 //��ӹ���
STATE_DYNAMITEKICK <- 222 //��޺ : �׵��?
STATE_FORTRESSBLITZ <- 223 //��פ��̪
STATE_AT_SOWALKER <- 224 //AT-SO ������
STATE_RAYTHEONCIRT <- 225 //��������?
STATE_SONICCOLLIDE <- 226 //��޺ : ������߯
STATE_DEATHFIELD <- 227 //��޺ : �������̪
STATE_EQUALISMR <- 228 //��޺ : �Х����-MR
STATE_FINALDESPERATION <- 229 //��޺ : �����̿����
STATE_ASSAULTATTACK <- 230 //������������
STATE_ACTIVATION <- 231 //��������
STATE_GUNNER_MSC7         <- 232    
STATE_GUNNER_SEISMICWAVE       <- 233    
STATE_GUNNER_PLASMABOOST       <- 234    
STATE_GUNNER_BURSTERBEAMNEW      <- 235    
STATE_GUNNER_DEADLYAPPROACH      <- 236    
STATE_GUNNER_WIPEOUT        <- 237    
STATE_GUNNER_SUPPRESSINGFIRE      <- 238    
STATE_GUNNER_FASTDRAW        <- 239    
STATE_SEVENTHFLOW<- 240
STATE_GUNNER_PISTOLCARBINE       <- 241    
STATE_GUNNER_GRAVITYGRENADE      <- 242    
STATE_GUNNER_DANGERCLOSE       <- 243    
STATE_GUNNER_G38ARG        <- 244    
STATE_GUNNER_SUPERNOVA        <- 245    
STATE_GUNNER_DIMENSIONRUNNER      <- 246    
STATE_GUNNER_HELLMARCH        <- 247    
STATE_DANGERCLOSE       <- 251    
STATE_OVERCHARGE				<- 252
STATE_TRIPLETAB					<- 253



SKILL_AIMSHOOT   <- 17
SKILL_BURSTBOMB   <- 19
SKILL_BODYBUNKER   <- 24
SKILL_NEODYMIUMFUSEE   <- 25
SKILL_TRIPLEGUNSHOT   <- 84
SKILL_MCPICE   <- 85
SKILL_BREACHINGDOWN   <- 86
SKILL_SCORCHTACTICS   <- 87
SKILL_DIRECTFEEDBACK   <- 88
SKILL_DYNAMITEKICK   <- 89
SKILL_FORTRESSBLITZ   <- 90
SKILL_RAYTHEONCIRT   <- 94
SKILL_ALTERATION   <- 99
SKILL_ARMORMASTERYLIGHT_ASSAULT   <- 172
SKILL_SENSIBILITY   <- 111
SKILL_ACTIVATION   <- 112
SKILL_RETROFIT   <- 113
SKILL_RECONSTRUCTIONBODY   <- 114
SKILL_AUTOMATICPISTOLMASTERY_ASSAULT   <- 116
SKILL_ARCDISCHARGE   <- 117
SKILL_DEATHFIELD   <- 118
SKILL_AT_SOWALKER   <- 130
SKILL_BASHSTOCK   <- 132
SKILL_EQUALISMR   <- 133
SKILL_SUPPRESS   <- 165

SKILL_TRIPLETAB	<- 16
SKILL_HEADSHOTMASTERY	<- 129
SKILL_GUNNER_MSC7         <- 232    
SKILL_GUNNER_SEISMICWAVE       <- 233    
SKILL_GUNNER_PLASMABOOST       <- 234    
SKILL_GUNNER_BURSTERBEAMNEW      <- 235    
SKILL_GUNNER_DEADLYAPPROACH      <- 236    
SKILL_GUNNER_WIPEOUT        <- 237    
SKILL_GUNNER_SUPPRESSINGFIRE      <- 238    
SKILL_GUNNER_FASTDRAW        <- 239    
SKILL_SEVENTHFLOW<- 240
SKILL_GUNNER_PISTOLCARBINE       <- 241    
SKILL_GUNNER_GRAVITYGRENADE      <- 242    
SKILL_GUNNER_DANGERCLOSE       <- 243    
SKILL_GUNNER_G38ARG        <- 244    
SKILL_GUNNER_SUPERNOVA        <- 245    
SKILL_GUNNER_DIMENSIONRUNNER      <- 246    
SKILL_GUNNER_HELLMARCH        <- 247    
SKILL_GUNNER_STYLISH      <- 248    
SKILL_ZUO_LUN_AO_YI			<- 126
SKILL_ZHAN_DI_GONG_XUN			<- 128
SKILL_DANGERCLOSE       <- 251
SKILL_OVERCHARGE				<- 252
SKILL_LATENTABILITY				<- 254


CUSTOM_ANI_GUNNER_MSC7MOTIONA_BODY     <- 103   
CUSTOM_ANI_GUNNER_MSC7MOTIONB_BODY     <- 104   
CUSTOM_ANI_GUNNER_SEISMICWAVECASTING    <- 105   
CUSTOM_ANI_GUNNER_SEISMICWAVECASTINGFINISH   <- 106   
CUSTOM_ANI_GUNNER_PLASMABOOSTSTART_BODY   <- 107   
CUSTOM_ANI_GUNNER_PLASMABOOSTLOOP_BODY    <- 108   
CUSTOM_ANI_GUNNER_PLASMABOOSTEND_BODY    <- 109   
CUSTOM_ANI_GUNNER_BB2NDREADY_BODY     <- 110   
CUSTOM_ANI_GUNNER_BB2NDATKA_BODY     <- 111   
CUSTOM_ANI_GUNNER_BB2NDATKB_BODY     <- 112   
CUSTOM_ANI_GUNNER_BB3RDATTACTEND_BODY    <- 113   
CUSTOM_ANI_GUNNER_DEADLYAPPROACH_START_BODY  <- 114   
CUSTOM_ANI_GUNNER_DEADLYAPPROACH_AIR_BODY   <- 115   
CUSTOM_ANI_GUNNER_DEADLYAPPROACH_FALL_BODY   <- 116   
CUSTOM_ANI_GUNNER_DEADLYAPPROACH_END_BODY   <- 117   
CUSTOM_ANI_GUNNER_WIPEOUTBODY_BODY     <- 118   
CUSTOM_ANI_GUNNER_SUPPRESSINGFIRE_START_BODY  <- 119   
CUSTOM_ANI_GUNNER_SUPPRESSINGFIRE_LOOP_BODY  <- 120   
CUSTOM_ANI_GUNNER_SUPPRESSINGFIRE_FINISH_BODY  <- 121   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_LEFTHANDSTART  <- 122   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_LEFTHANDTURN  <- 123   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_LEFTHANDSHOT  <- 124   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_LEFTHANDEND  <- 125   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_RIGHTHANDTRUN  <- 126   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_RIGHTHANDSHOT  <- 127   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_RIGHTHANDEND  <- 128   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_LEFTHANDSTART_LOW <- 129   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_LEFTHANDTURN_LOW <- 130   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_LEFTHANDSHOT_LOW <- 131   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_LEFTHANDEND_LOW <- 132   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_RIGHTHANDTRUN_LOW <- 133   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_RIGHTHANDSHOT_LOW <- 134   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_RIGHTHANDEND_LOW <- 135   
CUSTOM_ANI_SEVENTHFLOW1DASH<- 136
CUSTOM_ANI_SEVENTHFLOW1SHOOT<- 137
CUSTOM_ANI_SEVENTHFLOW2DASH<- 138
CUSTOM_ANI_SEVENTHFLOW2SHOOT<- 139
CUSTOM_ANI_SEVENTHFLOW3DASH<- 140
CUSTOM_ANI_SEVENTHFLOW3SHOOT<- 141
CUSTOM_ANI_SEVENTHFLOW4DASH<- 142
CUSTOM_ANI_SEVENTHFLOW4SHOOT<- 143
CUSTOM_ANI_SEVENTHFLOW5DASH<- 144
CUSTOM_ANI_SEVENTHFLOW5SHOOT<- 145
CUSTOM_ANI_SEVENTHFLOW6DASH<- 146
CUSTOM_ANI_SEVENTHFLOW6SHOOT<- 147
CUSTOM_ANI_SEVENTHFLOWLAST<- 148
CUSTOM_ANI_SEVENTHFLOWCAST<- 149
CUSTOM_ANI_GUNNER_PISTOLCARBINESTART_BODY   <- 150   
CUSTOM_ANI_GUNNER_PISTOLCARBINELOOP_BODY   <- 151   
CUSTOM_ANI_GUNNER_PISTOLCARBINEEND_BODY   <- 152   
CUSTOM_ANI_GUNNER_GRENADEGRAVITY_BODY    <- 153   
CUSTOM_ANI_GUNNER_DANGERCLOSE      <- 154   
CUSTOM_ANI_GUNNER_SUPERNOVA      <- 155   
CUSTOM_ANI_GUNNER_DIMENSIONRUNNERCAST    <- 156   
CUSTOM_ANI_GUNNER_HELLMARCH      <- 157   
CUSTOM_ANI_OVERCHARGE     <- 158    

CUSTOM_ANI_tripletaba_01_body	<- 160
CUSTOM_ANI_tripletaba_02_body	<- 161
CUSTOM_ANI_tripletaba_03_body	<- 162
CUSTOM_ANI_tripletaba_04_body	<- 163
CUSTOM_ANI_tripletabb_01_body	<- 164
CUSTOM_ANI_tripletabb_02_body	<- 165
CUSTOM_ANI_tripletabb_03_body	<- 166
CUSTOM_ANI_tripletabb_04_body	<- 167
CUSTOM_ANI_SUPPRESSCASTING 	<-	168
CUSTOM_ANI_SUPPRESSEND 	<-	169
CUSTOM_ANI_SUPPRESSENDSHORTDASH 	<-	170
CUSTOM_ANI_AIMSHOOTCAST 	<-	171
CUSTOM_ANI_AIMSHOOTSTART 	<-	172
CUSTOM_ANI_BASHSTOCKSTART 	<-	173
CUSTOM_ANI_BASHSTOCKATTACK 	<-	174
CUSTOM_ANI_BURSTBOMBCAST 	<-	175
CUSTOM_ANI_BURSTBOMBSTART 	<-	176
CUSTOM_ANI_BODYBUNKERCAST 	<-	177
CUSTOM_ANI_BODYBUNKERSTART 	<-	178
CUSTOM_ANI_NEODYMIUMFUSEECASTING 	<-	179
CUSTOM_ANI_NEODYMIUMFUSEESTART 	<-	180
CUSTOM_ANI_PROJECTNOVELPARTSTRIPLEGUNSHOTBODY 	<-	181
CUSTOM_ANI_TRIPLEGUNSHOTCAST 	<-	182
CUSTOM_ANI_TRIPLEGUNSHOTATTACK1 	<-	183
CUSTOM_ANI_TRIPLEGUNSHOTATTACK2 	<-	184
CUSTOM_ANI_TRIPLEGUNSHOTATTACK3 	<-	185
CUSTOM_ANI_MCPICE_START 	<-	186
CUSTOM_ANI_MCPICE_ATTACK 	<-	187
CUSTOM_ANI_BREACHINGDOWNCAST 	<-	188
CUSTOM_ANI_BREACHINGDOWNSTART01 	<-	189
CUSTOM_ANI_BREACHINGDOWNSTART02 	<-	190
CUSTOM_ANI_BREACHINGDOWNEND 	<-	191
CUSTOM_ANI_SCORCHTACTICS_START 	<-	192
CUSTOM_ANI_SCORCHTACTICS_START_MOVE 	<-	193
CUSTOM_ANI_SCORCHTACTICS_ATTACK1 	<-	194
CUSTOM_ANI_SCORCHTACTICS_ATTACK2 	<-	195
CUSTOM_ANI_SCORCHTACTICS_END 	<-	196
CUSTOM_ANI_SCORCHTACTICSREADYTALISMAN 	<-	197
CUSTOM_ANI_SCORCHTACTICSATTACK1TALISMAN 	<-	198
CUSTOM_ANI_SCORCHTACTICSATTACK2TALISMAN 	<-	199
CUSTOM_ANI_SCORCHTACTICSREADYJUMPTALISMAN 	<-	200
CUSTOM_ANI_SCORCHTACTICSATTACK1JUMPTALISMAN 	<-	201
CUSTOM_ANI_SCORCHTACTICSATTACK2JUMPTALISMAN 	<-	202
CUSTOM_ANI_SCORCHTACTICSFALLTALISMAN 	<-	203
CUSTOM_ANI_SCORCHTACTICSLANDTALISMAN 	<-	204
CUSTOM_ANI_DIRECTFEEDBACK_START 	<-	205
CUSTOM_ANI_DIRECTFEEDBACK_SCAN 	<-	206
CUSTOM_ANI_DIRECTFEEDBACK_SHOTLOOP 	<-	207
CUSTOM_ANI_DIRECTFEEDBACK_TURN 	<-	208
CUSTOM_ANI_DIRECTFEEDBACK_SHOTLOOPEND 	<-	209
CUSTOM_ANI_DYNAMITEKICK_START 	<-	210
CUSTOM_ANI_DYNAMITEKICK_ATTACK 	<-	211
CUSTOM_ANI_FORTRESSBLITZ_START 	<-	212
CUSTOM_ANI_FORTRESSBLITZ_FIRE 	<-	213
CUSTOM_ANI_RAYTHEONCIRT 	<-	214
CUSTOM_ANI_DEATHFIELDST1 	<-	215
CUSTOM_ANI_DEATHFIELDST2 	<-	216
CUSTOM_ANI_DEATHFIELDST3 	<-	217
CUSTOM_ANI_EQUALISMR 	<-	218
CUSTOM_ANI_ATSOWALKERANEODYMIUMFUSEEBODY 	<-	219
CUSTOM_ANI_ATSOWALKERSTARTBODY 	<-	220
CUSTOM_ANI_ATSOWALKERONBODY 	<-	221
CUSTOM_ANI_ATSOWALKERASTAND 	<-	222
CUSTOM_ANI_ATSOWALKERAWALK 	<-	223
CUSTOM_ANI_ATSOWALKERADASHLOOP 	<-	224
CUSTOM_ANI_ATSOWALKERANORMALATTACK 	<-	225
CUSTOM_ANI_ATSOWALKERAJUMP 	<-	226
CUSTOM_ANI_ATSOWALKERAJUMPATTACK 	<-	227
CUSTOM_ANI_ATSOWALKERASKILLBODY 	<-	228
CUSTOM_ANI_ATSOWALKERATRIPLEGUNSHOTBODY 	<-	229
CUSTOM_ANI_ATSOWALKERAJUMPATTACKREADY 	<-	230
CUSTOM_ANI_ATSOWALKEROFF 	<-	231
CUSTOM_ANI_ATSOWALKERTALISMANOFF 	<-	232
CUSTOM_ANI_ATSOWALKERAAIMSHOOT 	<-	233
CUSTOM_ANI_ATSOWALKERADIRECTFEEDBACK_SCAN 	<-	234
CUSTOM_ANI_ATSOWALKERADIRECTFEEDBACK 	<-	235
CUSTOM_ANI_ATSOWALKERAGETITEM 	<-	236
CUSTOM_ANI_ATSOWALKERADOWN 	<-	237
CUSTOM_ANI_ATSOWALKERASIT 	<-	238
CUSTOM_ANI_ASSAULTATTACKUP 	<-	239
CUSTOM_ANI_ASSAULTATTACKDOWN 	<-	240
CUSTOM_ANI_ASSAULTATTACKSTART 	<-	241
CUSTOM_ANI_ASSAULTEXPLOSION 	<-	242
CUSTOM_ANI_ACTIVATIONCAST 	<-	243
CUSTOM_ANI_ACTIVATIONSTART 	<-	244


CUSTOM_ATTACK_GUNNER_BURSTERBEAMFINISHMULTIHIT  <- 27    
CUSTOM_ATTACK_GUNNER_SUPPRESSINGFIRELOOPATTACK  <- 28    
CUSTOM_ATTACK_GUNNER_SUPPRESSINGFINISHFIRE   <- 29    
CUSTOM_ATTACK_GUNNER_FASTDRAWBODYATTACK   <- 30    
ATTACKINFO_THREESHOOT_HIT_DOWN	<- 31
ATTACKINFO_THREESHOOT_HIT_UP	<- 32
CUSTOM_ATTACK_SUPPRESSATTACK 	<-	33
CUSTOM_ATTACK_AIMSHOOTPUSH 	<-	34
CUSTOM_ATTACK_BASHSTOCKATTACK 	<-	35
CUSTOM_ATTACK_BURSTBOMBKNOCKBACK	<-	36
CUSTOM_ATTACK_TRIPLEGUNSHOTPUSH 	<-	37
CUSTOM_ATTACK_RAYTHEONCIRTARROW 	<-	38
CUSTOM_ATTACK_RAYTHEONCIRTBODY 	<-	39
CUSTOM_ATTACK_EQUALISMR 	<-	40
CUSTOM_ATTACK_DIRECTFEEDBACK	<-	41
CUSTOM_ATTACK_ASSAULTATTACKSTART	<-	42
 
PASSIVEOBJ_SUB_STATE_0 <- 10
PASSIVEOBJ_SUB_STATE_1 <- 11
PASSIVEOBJ_SUB_STATE_2 <- 12
PASSIVEOBJ_SUB_STATE_3 <- 13
PASSIVEOBJ_SUB_STATE_4 <- 14
PASSIVEOBJ_SUB_STATE_5 <- 15
PASSIVEOBJ_SUB_STATE_6 <- 16
PASSIVEOBJ_SUB_STATE_7 <- 17
PASSIVEOBJ_SUB_STATE_8 <- 18
PASSIVEOBJ_SUB_STATE_9 <- 19


PASSIVEOBJ_CUSTOM_ATTACK_AIMSHOOTDUMMY <- 0 //?����̪
PASSIVEOBJ_CUSTOM_ATTACK_BURSTBOMB <- 1 //����״������
PASSIVEOBJ_CUSTOM_ATTACK_BURSTBOMBEXPLOSION <- 2 //����״������
PASSIVEOBJ_CUSTOM_ATTACK_BODYBUNKER <- 3 //��޺ : ��������
PASSIVEOBJ_CUSTOM_ATTACK_NEODYMIUMFUSEE <- 4 //�������
PASSIVEOBJ_CUSTOM_ATTACK_TRIPLEGUNSHOTDUMMY1 <- 5 //߲֧߬��
PASSIVEOBJ_CUSTOM_ATTACK_TRIPLEGUNSHOTDUMMY1_NOVELPARTS <- 6 //߲֧߬��
PASSIVEOBJ_CUSTOM_ATTACK_TRIPLEGUNSHOTDUMMY2 <- 7 //߲֧߬��
PASSIVEOBJ_CUSTOM_ATTACK_TRIPLEGUNSHOTDUMMY2_NOVELPARTS <- 8 //߲֧߬��
PASSIVEOBJ_CUSTOM_ATTACK_TRIPLEGUNSHOTDUMMY3 <- 9 //߲֧߬��
PASSIVEOBJ_CUSTOM_ATTACK_TRIPLEGUNSHOTDUMMY3_NOVELPARTS <- 10 //߲֧߬��
PASSIVEOBJ_CUSTOM_ATTACK_MCPICEATTACK <- 11 //��֮ޫ?
PASSIVEOBJ_CUSTOM_ATTACK_MCPICEEXPLOSION <- 12 //��֮ޫ?
PASSIVEOBJ_CUSTOM_ATTACK_BREACHINGDOWNIMPACT <- 13 //��޺ : Ѧ������
PASSIVEOBJ_CUSTOM_ATTACK_BREACHINGDOWNIMPACTTALISMAN <- 14 //��޺ : Ѧ������
PASSIVEOBJ_CUSTOM_ATTACK_SCORCHTACTICSATTACK1 <- 15 //��������
PASSIVEOBJ_CUSTOM_ATTACK_SCORCHTACTICSATTACK2 <- 16 //��������
PASSIVEOBJ_CUSTOM_ATTACK_DIRECTFEEDBACK <- 17 //��ӹ���
PASSIVEOBJ_CUSTOM_ATTACK_DYNAMITEKICK <- 18 //��޺ : �׵��?
PASSIVEOBJ_CUSTOM_ATTACK_FORTRESSBLITZPUSH <- 19 //��פ��̪ ժ��
PASSIVEOBJ_CUSTOM_ATTACK_FORTRESSBLITZ <- 20 //��פ��̪ ��̪
PASSIVEOBJ_CUSTOM_ATTACK_FORTRESSBLITZEXPLOSION <- 21 //��פ��̪ ����
PASSIVEOBJ_CUSTOM_ATTACK_RAYTHEONCIRTEXP <- 22 //��������? ����
PASSIVEOBJ_CUSTOM_ATTACK_RAYTHEONCIRTEXPTALISMAN <- 23 //��������? ���� ��ݬ
PASSIVEOBJ_CUSTOM_ATTACK_DEATHFIELDGRENADELAUNCHER <- 24 //��޺ : �������̪ ״��
PASSIVEOBJ_CUSTOM_ATTACK_DEATHFIELDSHOTGUN <- 25 //��޺ : �������̪ �״��
PASSIVEOBJ_CUSTOM_ATTACK_DEATHFIELDFINISH <- 26 //��޺ : �������̪ ߤ��
PASSIVEOBJ_CUSTOM_ATTACK_DEATHFIELDGRENADE <- 27 //��޺ : �������̪ �������
PASSIVEOBJ_CUSTOM_ATTACK_EQUALISMRPUSH <- 28 //��޺ : �Х����-MR
PASSIVEOBJ_CUSTOM_ATTACK_AT_SOWALKERNORMALATTACK <- 29 //AT-SO ������
PASSIVEOBJ_CUSTOM_ATTACK_AT_SOWALKERAIATTACK <- 30 //AT-SO ������
PASSIVEOBJ_CUSTOM_ATTACK_AT_SOWALKERJUMPSHOCKWAVE <- 31 //AT-SO ������
PASSIVEOBJ_CUSTOM_ATTACK_AT_SOWALKERBODYHITWALL <- 32 //AT-SO ������
PASSIVEOBJ_CUSTOM_ATTACK_AT_SOWALKERBODYHITFLOOR <- 33 //AT-SO ������
PASSIVEOBJ_CUSTOM_ATTACK_AT_SOWALKERTALISMANDRAGDUMMY <- 34 //AT-SO ������
PASSIVEOBJ_CUSTOM_ATTACK_AT_SOWALKERTALISMANSELFBOOM <- 35 //AT-SO ������
PASSIVEOBJ_CUSTOM_ATTACK_AT_SOWALKERTRIPLEGUNSHOT <- 36 //AT-SO ������
PASSIVEOBJ_CUSTOM_ATTACK_AT_SOWALKERTRIPLEGUNSHOTNOVELPARTS <- 37 //AT-SO ������
PASSIVEOBJ_CUSTOM_ATTACK_TRIPLEGUNSHOTDUMMY3_NOVELPARTS <- 38 //AT-SO ������
PASSIVEOBJ_CUSTOM_ATTACK_ALTERATIONBULLETUP <- 39 //�������� ���� ߾
PASSIVEOBJ_CUSTOM_ATTACK_ALTERATIONBULLETDOWN <- 40 //�������� ���� ��
PASSIVEOBJ_CUSTOM_ATTACK_ALTERATIONDIEEXP <- 41 //�������� ���� ��������
PASSIVEOBJ_CUSTOM_ATTACK_ARCDISCHARGE <- 42 //��������ۯ����
 
 
 