//NUT内getFieldXPos等与屏幕宽度有关的偏移
CFG_SCREEN_WIDTH_OFFSETX <- 0
//长青训练场菜单X轴
CFG_UI_TRAINROOM_MENU_OFFSETX <- 0
//右侧二觉插画X轴
CFG_UI_AWAKE2_CUTIN_OFFSETX <- 266
//右侧一觉插画X轴
CFG_UI_ULTIMATE_CUTIN_OFFSETX <- 0
//NUT新版评分开关
CFG_FUNC_NUTNEWSCORE <- 1
//NUT新版评分坐标
CFG_UI_NUTNEWSCORE_POS_X <- 795
CFG_UI_NUTNEWSCORE_POS_Y <- 340
//NUT技能冷却提示开关
CFG_FUNC_NUTCOOLTIME <- 1
//NUT技能冷却提示坐标
CFG_UI_NUTCOOLTIME_POS_X <- 286
CFG_UI_NUTCOOLTIME_POS_Y <- 496
CFG_UI_NUTCOOLTIME_BAR_OFFSETX <- 0
CFG_UI_NUTCOOLTIME_BAR_OFFSETY <- 0
CFG_UI_NUTCOOLTIME_EXBAR_OFFSETX <- 0
CFG_UI_NUTCOOLTIME_EXBAR_OFFSETY <- 0
//拓展技能栏开关
CFG_FUNC_NUTNEWSKILLSLOT <- 1
//拓展技能栏坐标
CFG_UI_NUTNEWSKILLCTRL_POS_X <- 486
CFG_UI_NUTNEWSKILLCTRL_POS_Y <- 534
CFG_UI_NUTNEWSKILLALT_POS_X <- 486
CFG_UI_NUTNEWSKILLALT_POS_Y <- 565
CFG_UI_NUTNEWSKILLICON_ALPHA <- 255
//血法师能量坐标
CFG_UI_BLOODMAGEGAUGE_POS_X <- 513
CFG_UI_BLOODMAGEGAUGE_POS_Y <- 537
CFG_UI_BLOODMAGEGAUGE_CLIP_OFFSETX <- 34
CFG_UI_BLOODMAGEGAUGE_HEIGHT <- 64
CFG_UI_BLOODMAGEGAUGEFRAME_POS_X <- 541
CFG_UI_BLOODMAGEGAUGEFRAME_POS_Y <- 536
//血法师能量数值显示开关
CFG_FUNC_BLOODMAGEGAUGE_NUM <- 1


ENUM_EQUIPMENTTYPE_MAXS <- "aajisaohsfopasfiasjf!@$!*$fjaosf"
CHECK_KEY <- "aajisaohsfopasfiasjf!@$!*$fjaosf"

LANDTYPE_GRASS <- 0 		  //  
LANDTYPE_WETGRASS <- 1 		  //  ? ? 
LANDTYPE_SWAMP <- 2 		  //   ??
LANDTYPE_POISONSWAMP <- 3 		  //  ?? ??
LANDTYPE_BROWNDIRT <- 4 		  //  ? 
LANDTYPE_BLUEDIRT <- 5 		  //   
LANDTYPE_BONEYARD <- 6 		  //  ? ??
LANDTYPE_WATER <- 7 		  //  ?
LANDTYPE_MAGMA <- 8 		  //  ??
LANDTYPE_SNOW <- 9 		  //  ?? ??
LANDTYPE_RED_SWAMP <- 10 
LANDTYPE_PURPLE_POISONSWAMP <- 11 		  //  
LANDPARTICLE_DOWNLARGE <- 0 
LANDPARTICLE_DOWNSMALL <- 1 
LANDPARTICLE_MOVE <- 2 
LANDSOUND_JUMPSTART <- 0 
LANDSOUND_JUMPLAND <- 1 
LANDSOUND_MOVE <- 2 
LANDSOUND_DASH <- 3 
LANDSOUND_BACKSTEP <- 4 
LANDSOUND_FASTTHROUGH <- 5 

CATEGORY_TRIBE_HUMAN <- 0 		  //  ??
CATEGORY_TRIBE_BEAST <- 1 		  //  
CATEGORY_TRIBE_PLANT <- 2 		  //  
CATEGORY_TRIBE_INSECT <- 3 		  //  ?
CATEGORY_TRIBE_MACHINE <- 4 		  //  
CATEGORY_TRIBE_ORGANIC <- 5 		  //  ??
CATEGORY_TRIBE_HYBRID <- 6 		  //  ??
CATEGORY_TRIBE_UNDEAD <- 7 		  //  ?
CATEGORY_TRIBE_DEVIL <- 8 		  //  
CATEGORY_TRIBE_SPIRIT <- 9 		  //  ?
CATEGORY_TRIBE_DRAGON <- 10 		  //  ?
CATEGORY_AI_MELEE_ATTACK <- 11 		  //  ?? ?
CATEGORY_AI_RANGE_ATTACK <- 12 		  //  ??
CATEGORY_AI_NEGATIVE <- 13 		  //  ? ?
CATEGORY_AI_CAREFUL <- 14 		  //  ? ?
CATEGORY_AI_FULLSUPERARMOR <- 15 		  //  ?AI ?,? ? ? (? ??AI category?? ??) `08. 02, 20 ?
CATEGORY_AI_RASH <- 16 		  //  ?? ?
CATEGORY_AI_MANACE <- 17 		  //  ?? ?
CATEGORY_ARMOR_HUMAN <- 18 		  //    ( ?)
CATEGORY_ARMOR_FORT <- 19 		  //    (  ?)
CATEGORY_ARMOR_DIVINE <- 20 		  //  ?  (? )
CATEGORY_ETC_GOBLIN <- 21 		  //  ?
CATEGORY_ETC_TAU <- 22 		  //  
CATEGORY_ETC_LUGARU <- 23 		  //  ?
CATEGORY_ETC_FIXTURE <- 24 		  //  ? ( ?? ?? ? ?? ?)
CATEGORY_ETC_STAY <- 25 		  //   ? ?? ?
CATEGORY_PASSIVEOBJECT_TYPE_MELEE <- 26 
CATEGORY_PASSIVEOBJECT_TYPE_MISSILE <- 27 
CATEGORY_PASSIVEOBJECT_TYPE_ENERGY <- 28 
CATEGORY_PASSIVEOBJECT_TYPE_PHYSICAL <- 29 
CATEGORY_PASSIVEOBJECT_TYPE_MAGICAL <- 30 
CATEGORY_PASSIVEOBJECT_TYPE_BULLET <- 31 
CATEGORY_PASSIVEOBJECT_TYPE_CANON <- 32 
CATEGORY_PASSIVEOBJECT_TYPE_EXPLOSION <- 33 
CATEGORY_PASSIVEOBJECT_TYPE_INFLAME <- 34 
CATEGORY_PASSIVEOBJECT_TYPE_NONINFLAME <- 35 
CATEGORY_PASSIVEOBJECT_TYPE_LIGHT <- 36 
CATEGORY_PASSIVEOBJECT_TYPE_DARK <- 37 
CATEGORY_PASSIVEOBJECT_TYPE_WATER <- 38 
CATEGORY_PASSIVEOBJECT_TYPE_FIRE <- 39 
CATEGORY_PASSIVEOBJECT_TYPE_FORT <- 40 
CATEGORY_ETC_UNBEATABLE <- 41 		  //  ?, ??  ?  ?? ?
CATEGORY_TRIBE_ANGEL <- 42 		  //  
CATEGORY_MAX <- 43 

DOWN_PARAM_TYPE_VALUE <- 0 		  //   ??  ?? ?.
DOWN_PARAM_TYPE_FORCE <- 1 		  //  ? ?.
DOWN_PARAM_TYPE_BOUNCE_VALUE <- 2 		  //  . ?   ?  ?  ?? ?.
DOWN_PARAM_TYPE_BOUNCE_FORCE <- 3 		  //  . ?   ?  ?  ?? ?.
DOWN_PARAM_TYPE_BOUNCE <- 4 		  //  . ?   ?  ?  ?? ?.

ENUM_DIRECTION_LEFT <- 0 
ENUM_DIRECTION_RIGHT <- 1 
ENUM_DIRECTION_UP <- 2 
ENUM_DIRECTION_DOWN <- 3 
ENUM_DIRECTION_NEUTRAL <- 4 
ENUM_DIRECTION_MAX <- 5 

GRAPHICEFFECT_NONE <- 0 		  //  ?
GRAPHICEFFECT_DODGE <- 1 		  //  ?
GRAPHICEFFECT_LINEARDODGE <- 2 		  //  ?? ?
GRAPHICEFFECT_DARK <- 3 		  //  
GRAPHICEFFECT_XOR <- 4 		  //  XOR
GRAPHICEFFECT_MONOCHROME <- 5 		  //  
GRAPHICEFFECT_SPACE_DISTORT <- 6 		  //  ?
GRAPHICEFFECT_MAX <- 7 

ENUM_DRAWLAYER_CONTACT <- 0 		  //  ? ??
ENUM_DRAWLAYER_NORMAL <- 1 		  //   ??
ENUM_DRAWLAYER_BOTTOM <- 2 		  //   ??
ENUM_DRAWLAYER_CLOSEBACK <- 3 		  //   ??
ENUM_DRAWLAYER_MIDDLEBACK <- 4 		  //   ??
ENUM_DRAWLAYER_DISTANTBACK <- 5 		  //  ? ??
ENUM_DRAWLAYER_COVER <- 6 		  //  ?? ? ?? ex : Blind
ENUM_DRAWLAYER_MAX <- 7 


STATE_STAND <- 0 		  //  ??, 
STATE_SIT <- 1 		  //   (?? ??)
STATE_SIT_FOREVER <- 2 		  //  
STATE_DAMAGE <- 3 		  //  
STATE_DOWN <- 4 		  //   
STATE_DIE <- 5 		  //  
STATE_JUMP <- 6 		  //  ?
STATE_JUMP_ATTACK <- 7 		  //  ?
STATE_ATTACK <- 8 		  //  ?
STATE_HOLD <- 9 		  //  ?  ?
STATE_SUMMONSTART <- 10 		  //   ?
STATE_SUMMONEND <- 11 		  //   
STATE_UNSUMMON <- 12 		  //  ?? ??
STATE_THROW <- 13 		  //  
STATE_DASH <- 14 		  //  ?? 
STATE_DASH_ATTACK <- 15 		  //  ?? ?
STATE_GET_ITEM <- 16 		  //   
STATE_BUFF <- 17 		  //  ?
STATE_QUICK_STANDING <- 18 		  //  ?							
STATE_CROUCH <- 19 		  //  ??
STATE_CROUCH_ATTACK <- 20 		  //  ?
STATE_LOW_KICK <- 21 		  //  , ?? ??, ?
STATE_TRY_GRAB <- 22 		  //  
STATE_SUPLEX <- 23 		  //  ?
STATE_JUMP_SUPLEX <- 24 		  //  ?
STATE_JUMP_SUPLEX_LARIAT <- 25 		  //  ?  ?
STATE_MOUNT_TRY <- 26 		  //  ?? 
STATE_MOUNT <- 27 		  //  ??
STATE_STOMP <- 28 		  //  
STATE_CLOSE_PUNCH <- 29 		  //  ?? 
STATE_LIFT_UPPER <- 30 		  //  ? ?
STATE_GRAB_EXPLOSION <- 31 		  //  
STATE_VIRTUAL_ATTACK <- 32 		  //   ? -> ? ? ? ? STATE
STATE_SHOULDER_TACKLE <- 33 		  //  
STATE_WHIRL_WIND_KICK <- 34 		  //  ??
STATE_BLOCK_BUSTER <- 35 		  //  
STATE_TRY_LEG_SUPLEX <- 36 		  //  ?? 
STATE_LEG_SUPLEX <- 37 		  //  ?? ?
STATE_LIGHTNING_DANCE <- 38 		  //  ? 
STATE_THROW_WEB <- 39 		  //  ?
STATE_HIDDEN_STING <- 40 		  //   ?()
STATE_VENOM_MINE <- 41 		  //  
STATE_JUNK_SPIN <- 42 		  //  ?
STATE_SHOULDER_CHARGE <- 43 		  //  ?
STATE_SINGLE_KICK <- 44 		  //  ?
STATE_NEN_FLOWER <- 45 		  //  
STATE_THROW_ENEMY <- 46 		  //  ??
STATE_DASH_PUNCH <- 47 		  //  ? ?
STATE_PUNCH_AFTER_RETURN <- 48 		  //  ?? ??
STATE_RANDOM_KICK <- 49 		  //  ? 
STATE_RISING_UPPER <- 50 		  //  ?
STATE_DASH_AFTER_DASH <- 51 		  //  
STATE_EARTH_BREAK <- 52 		  //  ??
STATE_HOLD_UP <- 53 		  //  ?
STATE_WILD_CANNON_SPIKE <- 54 		  //  ??  ?
STATE_SUPLEX_CYCLONE <- 55 		  //  ? ?
STATE_LIGHTNING_DRAGON <- 56 		  //  ??
STATE_STRONGEST_LOW_KICK <- 57 		  //  ?? 
STATE_GROUND_KICK <- 58 		  //  
STATE_FAST_DASH <- 59 		  //  ?
STATE_DESTROY_EARTH_SKY_DROP <- 60 		  //     - ?
STATE_TYPHOON <- 61 		  //   
STATE_FLAME_LEGS <- 62 		  //  ??  - 
STATE_THROW_SAND <- 63 		  //  ??
STATE_ENCHANT_POISON <- 64 		  //  
STATE_SPIRAL_NEN_SHOOT <- 65 		  //   ?? : ??
STATE_NEN_SPEAR_EX <- 66 		  //  ?? ??() proc? ??1?? ?? ??, ??    ??2 ??  ? 
STATE_HURRICANE_SPEAR <- 67 		  //   ?? ()
STATE_CRASH_ROPE <- 68 		  //  ?? ()
STATE_CHARGE_SPEAR_EX <- 69 		  //  ? ??()
STATE_SPIRAL_COLUMN_EX <- 70 		  //  ??()
STATE_GLUEY_FRUIT_EX <- 71 		  //  ?? ?()
STATE_CHAIN_KICK_EX <- 72 		  //  ?? ()
STATE_108_STAIRS_EX <- 73 		  //  108()
STATE_INHERIT_START <- 74 
STATE_MAX <- 75 

SKILL_SHOULDER_CHARGE <- 1 		  //  001.?
SKILL_CROUCH <- 2 		  //  002.??
SKILL_GRAB_EXPLOSION <- 3 		  //  003.
SKILL_CRASH_LOW_KICK <- 4 		  //  004.?? ??
SKILL_LIFT_UPPER <- 5 		  //  005.? ?
SKILL_DAMAGE_LOW_KICK <- 6 		  //  006.
SKILL_PHYSICAL_DEFENSE_UP <- 7 		  //  007.?
SKILL_CREATE_ILLUSION <- 8 		  //  008.
SKILL_SUPLEX <- 9 		  //  009.?
SKILL_BACK_SUPLEX <- 10 		  //  010.
SKILL_THUNDER_SUPLEX <- 11 		  //  011.? 
SKILL_ENERGY_BALL <- 12 		  //  012.
SKILL_THROW_SAND <- 13 		  //  013.? 
SKILL_MOUNT <- 14 		  //  014.??
SKILL_ROAR_STUN <- 15 		  //  015.
SKILL_ENERGY_FIELD <- 16 		  //  016.??
SKILL_STOMP <- 17 		  //  017.? 
SKILL_JUMP_SUPLEX <- 18 		  //  018.?
SKILL_CLOSE_PUNCH <- 19 		  //  019.?? 
SKILL_SUPER_ARMOR <- 20 		  //  020.
SKILL_CANCEL_ENERGY_BALL <- 21 		  //  021. 
SKILL_SUPLEX_SUB_POWER_UP <- 22 		  //  022. ?? 
SKILL_CANCEL_LIFT_UPPER <- 23 		  //  023. ? ?
SKILL_CANCEL_LOW_KICK <- 24 		  //  024. 
SKILL_CANCEL_THROW_SAND <- 25 		  //  025. ? 
SKILL_CANCEL_CLOSE_PUNCH <- 26 		  //  026. ?? 
SKILL_CANCEL_SUPLEX <- 27 		  //  027. ?
SKILL_CANCEL_JUMP_SUPLEX <- 28 		  //  028. ?
SKILL_LIGHT_FRIENDSHIP <- 29 		  //  029.? ??
SKILL_LIGHT_ENCHANT_WEAPON <- 30 		  //  030.
SKILL_ATTACK_SPEED_UP <- 31 		  //  031.? ?
SKILL_POISON_TOLERANCE_UP <- 32 		  //  032.? ??
SKILL_STUN_ON_USE_SKILL <- 33 		  //  033.
SKILL_EQUIP_BOXING_GLOVE <- 34 		  //  034. ?
SKILL_BLIND_TOLERANCE_UP <- 35 		  //  035. 
SKILL_LIGHT_TOLERANCE_UP <- 36 		  //  036.?? ??
SKILL_SLOW_DOWN_POWER_UP <- 37 		  //  037.?
SKILL_ENCHANT_POISON <- 38 		  //  038.?? ?(?)
SKILL_AIM_VITAL_POINT <- 39 		  //  039. ?
SKILL_SPIRAL_NEN <- 40 		  //  040. ??
SKILL_FLAME_LEGS <- 41 		  //  041.??  - 
SKILL_NEN_GUARD <- 42 		  //  042.??
SKILL_DOUBLE_THROW <- 43 		  //  043.? 
SKILL_PROVOCATION <- 44 		  //  044.?
SKILL_CLAW_MASTERY <- 45 		  //  045. ?
SKILL_SINGLE_KICK <- 46 		  //  046. ?
SKILL_CANCEL_SINGLE_KICK <- 47 		  //  047.  ?
SKILL_CANCEL_GRAB_EXPLOSION <- 48 		  //  048. 
SKILL_THROW_ENEMY <- 49 		  //  049.??
SKILL_DEFINITE_GRAB <- 50 		  //  050.??
SKILL_SLIDE_GRAB <- 51 		  //  051.? 
SKILL_THROW_WEB <- 52 		  //  052.?
SKILL_CANCEL_THROW_ENEMY <- 53 		  //  053. ??
SKILL_SHOULDER_TACKLE <- 54 		  //  054.
SKILL_GRAB_CANNON <- 55 		  //  055. 
SKILL_ARMOR_MASTERY_LIGHT_SK <- 56 		  //  056.?? ? ?? ?
SKILL_ARMOR_MASTERY_LIGHT_GP <- 57 		  //  057. ?? ?? ?
SKILL_WHIRL_WIND_KICK <- 58 		  //  058.??
SKILL_CANCEL_WHIRL_WIND_KICK <- 59 		  //  059. ??
SKILL_BLOCK_BUSTER <- 60 		  //  060.
SKILL_CANCEL_THROW <- 61 		  //  061. 
SKILL_LEG_SUPLEX <- 62 		  //  062.??
SKILL_TYPHOON <- 63 		  //  063. 
SKILL_DUMMY <- 64 		  //  064.??.
SKILL_EFFICIENT_BURN <- 65 		  //  065. ? ? - ? ?
SKILL_GRAB_MASTERY <- 66 		  //  066.?
SKILL_NEN_FLOWER <- 67 		  //  067.
SKILL_LIGHTNING_DANCE <- 68 		  //  068.? 
SKILL_ILLUSION_BOMB <- 69 		  //  069.?
SKILL_POWER_UP_ON_DASH <- 70 		  //  070.?
SKILL_STRONGEST_LOW_KICK <- 71 		  //  071.?ְ
SKILL_NEN_SHIELD <- 72 		  //  072. ?
SKILL_ARMOR_MASTERY_HEAVY_SP <- 73 		  //  073. ?
SKILL_CRAZY_MOUNT <- 74 		  //  074.? ??
SKILL_HIDDEN_STING <- 75 		  //  075.
SKILL_VENOM_MINE <- 76 		  //  076.
SKILL_JUNK_SPIN <- 77 		  //  077.?
SKILL_ENERGY_BALL_CHARGE <- 78 		  //  078. ??
SKILL_NEN_MONSTER_WHITE_TIGER <- 79 		  //  079. : 
SKILL_DASH_PUNCH <- 80 		  //  080.??
SKILL_PUNCH_AFTER_RETURN <- 81 		  //  081.?? ??
SKILL_RANDOM_KICK <- 82 		  //  082.? 
SKILL_RISING_UPPER <- 83 		  //  083.?
SKILL_DASH_AFTER_DASH <- 84 		  //  084.
SKILL_DASH_AFTER_DASH_EXTENSION <- 85 		  //  085.
SKILL_EARTH_BREAK <- 86 		  //  086.??
SKILL_HOLD_UP <- 87 		  //  087.?
SKILL_WILD_CANNON_SPIKE <- 88 		  //  088.??  ?
SKILL_SUPLEX_CYCLONE <- 89 		  //  089.? ?
SKILL_LIGHTNING_DRAGON <- 90 		  //  090.??
SKILL_MUSCLE_SHIFT <- 91 		  //  091. ??	
SKILL_CANCEL_EARTH_BREAK <- 92 		  //  092. ??
SKILL_CANCEL_DASH_PUNCH <- 93 		  //  093. 
SKILL_CANCEL_SHOULDER_CHARGE <- 94 		  //  094. ?
SKILL_CANCEL_PUNCH_AFTER_RETURN <- 95 		  //  095. ?? ??
SKILL_CANCEL_SUPLEX_CYCLONE <- 96 		  //  096. ? ?
SKILL_ARMOR_MASTERY_CLOTH_NM <- 97 		  //  097.? ?:?
SKILL_CANCEL_NEN_GUARD <- 98 		  //  098. ??
SKILL_CANCEL_ROAR_STUN <- 99 		  //  099. 
SKILL_CANCEL_ENERGY_FIELD <- 100 		  //  100. ??
SKILL_CANCEL_ENCHANT_POISON <- 101 		  //  101.??.
SKILL_CANCEL_VENOM_MINE <- 102 		  //  102. 
SKILL_CANCEL_RANDOM_KICK <- 103 		  //  103. ?̺?
SKILL_BLOCK_BUSTER_EX <- 104 		  //  104.[]
SKILL_DESTROY_EARTH_SKY_DROP <- 105 		  //  105.   - ?
SKILL_GROUND_KICK <- 106 		  //  106.
SKILL_CANCEL_GROUND_KICK <- 107 		  //  107. 
SKILL_FAST_DASH <- 108 		  //  108.?
SKILL_SMART_THROW <- 109 		  //  ?   - 
SKILL_AUTO_LOAD <- 110 		  //  110.?
SKILL_SPIRAL_NEN_SHOOT <- 111 		  //  111. ?? : ??
SKILL_SPIRAL_NEN_SPIN <- 112 		  //  112. ?? : ??
SKILL_CANCEL_SPIRAL_NEN_SHOOT <- 113 		  //  113.  ?? : ??
SKILL_NEN_POLE <- 114 		  //  114.? ?
SKILL_TYPHOON_COUNTER_STRIKE <- 115 		  //  115.? :   ?
SKILL_1000HANDS_1000EYES <- 116 		  //  116. : ?  ?
SKILL_NEN_SPEAR_EX <- 117 		  //  117.?? ??()
SKILL_CHARGE_SPEAR_EX <- 118 		  //  118.? ??()
SKILL_GLUEY_FRUIT_EX <- 119 		  //  119. ()
SKILL_SPIRAL_COLUMN_EX <- 120 		  //  120.??() 
SKILL_108_STAIRS_EX <- 121 		  //  121.108()
SKILL_HURRICANE_SPEAR <- 122 		  //  122. ?? ()
SKILL_CRASH_ROPE <- 123 		  //  123.?? ()
SKILL_CHAIN_KICK_EX <- 124 		  //  124.?? ()

CUSTOM_ANI_CROUCH <- 0 		  //  
CUSTOM_ANI_CRASH_LOW_KICK <- 1 		  //  ?? ??
CUSTOM_ANI_LIFT_UPPER <- 2 		  //  ? ?
CUSTOM_ANI_DAMAGE_LOW_KICK <- 3 		  //  
CUSTOM_ANI_TRY_SUPLEX <- 4 		  //  ? 
CUSTOM_ANI_SUPLEX <- 5 		  //  ?
CUSTOM_ANI_BACK_SUPLEX <- 6 		  //  
CUSTOM_ANI_MOUNT_TRY <- 7 		  //  ?? 
CUSTOM_ANI_MOUNT <- 8 		  //  ?? - ?    
CUSTOM_ANI_MOUNT_PUNCH <- 9 		  //  ?? - 
CUSTOM_ANI_NOT_USE <- 10 		  //  ??.
CUSTOM_ANI_STOMP <- 11 		  //  ? 
CUSTOM_ANI_TRY_JUMP_SUPLEX <- 12 		  //  ? 
CUSTOM_ANI_JUMP_SUPLEX <- 13 		  //  ?
CUSTOM_ANI_JUMP_SUPLEX_LARIAT <- 14 		  //  ?  ?
CUSTOM_ANI_CLOSE_PUNCH <- 15 		  //  ?? 
CUSTOM_ANI_GRAB_EXPLOSION <- 16 		  //  
CUSTOM_ANI_SHOULDER_TACKLE <- 17 		  //  
CUSTOM_ANI_WHIRL_WIND_KICK <- 18 		  //  ??
CUSTOM_ANI_BLOCK_BUSTER_READY <- 19 		  //   -  (  ?? ??)
CUSTOM_ANI_BLOCK_BUSTER_JUMP <- 20 		  //   - ? (  ?? ??)
CUSTOM_ANI_BLOCK_BUSTER_SHOOT <- 21 		  //   - ? (  ?? ??)
CUSTOM_ANI_BLOCK_BUSTER_NORMAL <- 22 		  //   -  ? 		
CUSTOM_ANI_TRY_LEG_SUPLEX <- 23 		  //  ?? 
CUSTOM_ANI_LEG_SUPLEX_THROW <- 24 		  //  ?? : 
CUSTOM_ANI_LEG_SUPLEX_KICK <- 25 		  //  ?? 
CUSTOM_ANI_TYPHOON_GRAB <- 26 		  //    : 
CUSTOM_ANI_TYPHOON_ATTACK1 <- 27 		  //    : 1?
CUSTOM_ANI_TYPHOON_ATTACK2 <- 28 		  //    : 2?
CUSTOM_ANI_TYPHOON_ATTACK3 <- 29 		  //    : 3?
CUSTOM_ANI_TYPHOON_KICKUP <- 30 		  //    : ?
CUSTOM_ANI_TYPHOON_JUMP <- 31 		  //    : ?
CUSTOM_ANI_TYPHOON_LAST <- 32 		  //    : 		
CUSTOM_ANI_TYPHOON_STAY <- 33 		  //    :  ?? 
CUSTOM_ANI_CRAZY_MOUNT_START <- 34 		  //  ? ??
CUSTOM_ANI_CRAZY_MOUNT_PUNCH <- 35 		  //  ? ??  
CUSTOM_ANI_CRAZY_MOUNT_NOT_USE <- 36 		  //  ??.
CUSTOM_ANI_CRAZY_MOUNT_END <- 37 		  //  ? ?? 
CUSTOM_ANI_THROW_WEB <- 38 		  //  ?
CUSTOM_ANI_HIDDEN_STING <- 39 		  //  
CUSTOM_ANI_VENOM_MINE <- 40 		  //  
CUSTOM_ANI_FLAME_LEGS_CAST <- 41 		  //  ??  - (?)
CUSTOM_ANI_JUNK_SPIN_LOOP <- 42 		  //  ?
CUSTOM_ANI_JUNK_SPIN_FINISH <- 43 
CUSTOM_ANI_MOUNT_END <- 44 		  //  ??  
CUSTOM_ANI_SHOULDER_CHARGE <- 45 		  //  ?
CUSTOM_ANI_SINGLE_KICK <- 46 		  //  ?
CUSTOM_ANI_NEN_FLOWER <- 47 		  //  
CUSTOM_ANI_TRY_THROW_ENEMY <- 48 		  //  ?? 
CUSTOM_ANI_THROW_ENEMY_HOLD <- 49 		  //  ?? ?ֱ?
CUSTOM_ANI_THROW_ENEMY_THROW <- 50 		  //  ?? 
CUSTOM_ANI_WHITE_TIGER_COMBO1 <- 51 		  //  : 1?
CUSTOM_ANI_WHITE_TIGER_COMBO2 <- 52 		  //  : 2?
CUSTOM_ANI_WHITE_TIGER_COMBO3 <- 53 		  //  : 3?
CUSTOM_ANI_WHITE_TIGER_COMBO4 <- 54 		  //  : 4?
CUSTOM_ANI_WHITE_TIGER_COMBO5 <- 55 		  //  : 5?
CUSTOM_ANI_WHITE_TIGER_DASH_ATTACK <- 56 		  //  : 
CUSTOM_ANI_WHITE_TIGER_JUMP_ATTACK <- 57 		  //  : ??
CUSTOM_ANI_DASH_PUNCH <- 58 		  //  ? ?
CUSTOM_ANI_PUNCH_AFTER_RETURN <- 59 		  //  ?? ??
CUSTOM_ANI_RANDOM_KICK1 <- 60 		  //   ?̺?1?
CUSTOM_ANI_RANDOM_KICK2 <- 61 		  //   ?̺?2?
CUSTOM_ANI_RANDOM_KICK3 <- 62 		  //   ?̺?3?
CUSTOM_ANI_RANDOM_KICK_FINISH <- 63 		  //   ?̺?
CUSTOM_ANI_RISING_UPPER_DASH <- 64 		  //  ?: ??
CUSTOM_ANI_RISING_UPPER <- 65 		  //  ?: ?
CUSTOM_ANI_DASH_AFTER_DASH_COMBO1 <- 66 		  //   : 1?
CUSTOM_ANI_DASH_AFTER_DASH_COMBO2 <- 67 		  //   : 2?
CUSTOM_ANI_DASH_AFTER_DASH_COMBO3 <- 68 		  //   : 3? - ?  3? ? 
CUSTOM_ANI_DASH_AFTER_DASH_COMBO4 <- 69 		  //   : 4? - ?  4? ? 
CUSTOM_ANI_EARTH_BREAK <- 70 		  //  ??
CUSTOM_ANI_HOLD_UP_TRY <- 71 		  //  ?: 
CUSTOM_ANI_HOLD_UP_HOLD <- 72 		  //  ?: 
CUSTOM_ANI_HOLD_UP_HIT <- 73 		  //  ?: 
CUSTOM_ANI_WILD_CANNON_SPIKE_CHARGE <- 74 		  //  ??  ? : ?
CUSTOM_ANI_WILD_CANNON_SPIKE_FALL <- 75 		  //  ??  ? : ??
CUSTOM_ANI_THROW_SAND <- 76 		  //  
CUSTOM_ANI_THROW_SAND_DOUBLE <- 77 		  //   (?)
CUSTOM_ANI_TRY_SUPLEX_CYCLONE <- 78 		  //  ? ? : 
CUSTOM_ANI_TURN_SUPLEX_CYCLONE <- 79 		  //  ? ? : 
CUSTOM_ANI_WILD_CANNON_SPIKE_EXP <- 80 		  //  ??  ? : 
CUSTOM_ANI_FINISH_SUPLEX_CYCLONE <- 81 		  //  ??.
CUSTOM_ANI_LIGHTNING_DRAGON <- 82 		  //  
CUSTOM_ANI_DESTROY_EARTH_SKY_DROP_START <- 83 		  //     - ? ?
CUSTOM_ANI_DESTROY_EARTH_SKY_DROP_ON_SKY <- 84 		  //     - ? : 
CUSTOM_ANI_DESTROY_EARTH_SKY_DROP_FINISH <- 85 		  //   ?? 1?? 
CUSTOM_ANI_TRY_LEG_SUPLEX_EX_SECOND <- 86 		  //   ?? 2??  ?
CUSTOM_ANI_LEG_SUPLEX_EX_2 <- 87 		  //   ?? 2?? 
CUSTOM_ANI_RISING_UPPER_EX_START <- 88 		  //   ??  ?
CUSTOM_ANI_RISING_UPPER_EX <- 89 		  //   ?? 
CUSTOM_ANI_RISING_UPPER_EX_FINISH <- 90 		  //   ??  
CUSTOM_ANI_BLOCK_BUSTER_EX_TRY <- 91 		  //    ?
CUSTOM_ANI_BLOCK_BUSTER_EX_JUMP <- 92 		  //    ?
CUSTOM_ANI_BLOCK_BUSTER_EX_FINISH <- 93 		  //    
CUSTOM_ANI_SUPLEX_CYCLONE_JUMP_EX <- 94 		  //   ? ? : ?
CUSTOM_ANI_SUPLEX_CYCLONE_SPIN_EX <- 95 		  //   ? ? : ?
CUSTOM_ANI_DASH_PUNCH_EX <- 96 		  //   
CUSTOM_ANI_STOMP_FINISH <- 97 		  //  
CUSTOM_ANI_GROUND_KICK_JUMP <- 98 		  //   - ?
CUSTOM_ANI_GROUND_KICK_ATTACK <- 99 		  //   - ?
CUSTOM_ANI_GROUND_KICK_FINISH <- 100 		  //   - ?
CUSTOM_ANI_FAST_DASH <- 101 		  //  ?
CUSTOM_ANI_CRASH_LOW_KICK_SECOND <- 102 		  //  ?? ?? ? 
CUSTOM_ANI_THROW_ENEMY_SIDEKICK <- 103 		  //  ? ?? 
CUSTOM_ANI_THROW_ENEMY_DOWNKICK <- 104 		  //  ? ?? ??
CUSTOM_ANI_THROW_GRAB_CANNON_ENEMY_SIDEKICK <- 105 		  //  ? ??  
CUSTOM_ANI_SUPLEX_FINAL_ATTACK <- 106 		  //  ? ?  ?
CUSTOM_ANI_SUPLEX_THROW_FINAL_ATTACK <- 107 		  //  ? ? ?? ?
CUSTOM_ANI_DOUBLE_THROW_WEB <- 108 		  //  ?  (?)
CUSTOM_ANI_LEG_SUPLEX_FIRST_KICK <- 109 		  //  ? ??  ?
CUSTOM_ANI_JUMP_SUPLEX_HOLD_IMPRESSKICK <- 110 		  //  ? ? - ? - ?? 
CUSTOM_ANI_LIGHTNING_DANCE_KICK <- 111 		  //  ? ? ?
CUSTOM_ANI_LIGHTNING_DANCE_LAST_LOW_KICK <- 112 		  //  ? ?  ?
CUSTOM_ANI_GRAB_EXPLOSION_KICK <- 113 		  //  ? 	- ? ?
CUSTOM_ANI_NEN_FLOWER_READY <- 114 		  //  ?-? ??  ?
CUSTOM_ANI_NEN_FLOWER_ATTACK <- 115 		  //  ?-? ?? ?
CUSTOM_ANI_NEN_FLOWER_FINAL <- 116 		  //  ?-? ??  ?
CUSTOM_ANI_ENCHANT_POISON <- 117 		  //   
CUSTOM_ANI_SPIRALNEN_SHOOT_PREPARE <- 118 		  //   ??:?? ?? ??
CUSTOM_ANI_SPIRALNEN_SHOOT <- 119 		  //   ??:?? ??
CUSTOM_ANI_BLOCK_BUSTER_DOUBLE <- 120 		  //   - ?
CUSTOM_ANI_ENCHANT_POISON_DOUBLE <- 121 		  //   - ?
CUSTOM_ANI_HIDDEN_STING_DOUBLE <- 122 		  //  ? - ?
CUSTOM_ANI_DEFINITE_GRAB <- 123 		  //  ??-  ?
CUSTOM_ANI_NEN_SPEAR <- 124 		  //  ?? ?? ()
CUSTOM_ANI_NEN_SPEAR_SUCCESS <- 125 		  //  ?? ??  ()
CUSTOM_ANI_HURRICANE_SPEAR <- 126 		  //  ??  -  ??
CUSTOM_ANI_CHARGE_SPEAR_RECHARGE <- 127 		  //  () ?		
CUSTOM_ANI_CHARGE_SPEAR_RUSH <- 128 		  //  () ?
CUSTOM_ANI_CHARGE_SPEAR_END <- 129 		  //  () ? ??
CUSTOM_ANI_SPIRAL_COLUMN_EX <- 130 		  //  ??()
CUSTOM_ANI_CRASH_ROPE <- 131 		  //  ?? ()
CUSTOM_ANI_GLUEY_FRUIT <- 132 		  //  ?? ?()
CUSTOM_ANI_CHAIN_KICK <- 133 		  //  ??()
CUSTOM_ANI_108_STAIRS_TRY_EX <- 134 		  //  108)
CUSTOM_ANI_108_STAIRS_KICK_EX <- 135 		  //  108)
CUSTOM_ANI_108_STAIRS_PUNCH_EX <- 136 		  //  108)
CUSTOM_ANI_108_STAIRS_BLOW_EX <- 137 		  //  108)
CUSTOM_ANI_108_STAIRS_THROW_EX <- 138 		  //  108)
CUSTOM_ANI_108_STAIRS_FINAL_EX <- 139 		  //  108)

CUSTOM_ATTACKINFO_CRASH_LOW_KICK <- 0 		  //  ?? ??
CUSTOM_ATTACKINFO_LIFT_UPPER <- 1 		  //  ? ?
CUSTOM_ATTACKINFO_DAMAGE_LOW_KICK <- 2 		  //  
CUSTOM_ATTACKINFO_TRY_GRAB <- 3 		  //  
CUSTOM_ATTACKINFO_SUPLEX <- 4 		  //   ? 
CUSTOM_ATTACKINFO_MOUNT <- 5 		  //  ?? 
CUSTOM_ATTACKINFO_STOMP <- 6 		  //  ? 
CUSTOM_ATTACKINFO_JUMP_SUPLEX <- 7 		  //  ? (? ?)
CUSTOM_ATTACKINFO_JUMP_SUPLEX_HEADING <- 8 		  //  ?  ?
CUSTOM_ATTACKINFO_JUMP_SUPLEX_LARIAT <- 9 		  //   ?  ? (?)
CUSTOM_ATTACKINFO_CLOSE_PUNCH <- 10 		  //  ?? 
CUSTOM_ATTACKINFO_SHOULDER_CHARGE <- 11 		  //  ?
CUSTOM_ATTACKINFO_SINGLE_KICK <- 12 		  //   ?
CUSTOM_ATTACKINFO_GRAB_EXPLOSION <- 13 		  //   
CUSTOM_ATTACKINFO_SHOULDER_TACKLE <- 14 		  //  
CUSTOM_ATTACKINFO_GRAB_CANNON <- 15 		  //   
CUSTOM_ATTACKINFO_WHIRL_WIND_KICK <- 16 		  //  ??
CUSTOM_ATTACKINFO_JUNK_SPIN <- 17 		  //   (?)
CUSTOM_ATTACKINFO_LEG_SUPLEX_KICK <- 18 		  //  ?? : ?
CUSTOM_ATTACKINFO_LIGHTNING_DANCE <- 19 		  //  ? 
CUSTOM_ATTACKINFO_STRONGEST_LOW_KICK <- 20 		  //  ?ְ
CUSTOM_ATTACKINFO_CRAZY_MOUNT <- 21 		  //  ? ??
CUSTOM_ATTACKINFO_THROW_WEB <- 22 		  //  ?
CUSTOM_ATTACKINFO_HIDDEN_STING <- 23 		  //  
CUSTOM_ATTACKINFO_DASH_PUNCH <- 24 		  //  ? ?
CUSTOM_ATTACKINFO_PUNCH_AFTER_RETURN <- 25 		  //  ?? ??
CUSTOM_ATTACKINFO_RANDOM_KICK_1 <- 26 		  //   ?̺?1?
CUSTOM_ATTACKINFO_RANDOM_KICK_2 <- 27 		  //   ?̺?2?
CUSTOM_ATTACKINFO_RANDOM_KICK_3 <- 28 		  //   ?̺?3?
CUSTOM_ATTACKINFO_RANDOM_KICK_FINISH <- 29 		  //   ?̺?
CUSTOM_ATTACKINFO_DUMMY_4 <- 30 		  //   ?.
CUSTOM_ATTACKINFO_RISING_UPPER <- 31 		  //  ?: ?
CUSTOM_ATTACKINFO_DASH_AFTER_DASH_COMBO1 <- 32 		  // 	 : 1?
CUSTOM_ATTACKINFO_DASH_AFTER_DASH_COMBO2 <- 33 		  // 	 : 2?
CUSTOM_ATTACKINFO_VENOM_MINE <- 34 		  // 	 ??
CUSTOM_ATTACKINFO_DUMMY_2 <- 35 		  // 	 ?
CUSTOM_ATTACKINFO_HOLD_UP_TRY <- 36 		  //  ?: 
CUSTOM_ATTACKINFO_HOLD_UP_HIT <- 37 		  //  ?: 
CUSTOM_ATTACKINFO_WILD_CANNON_SPIKE_FALL <- 38 		  //  ??  ? : ? ??
CUSTOM_ATTACKINFO_WILD_CANNON_SPIKE_HIT <- 39 		  //  ??  ? :   
CUSTOM_ATTACKINFO_WHITE_TIGER_COMBO1 <- 40 		  //  : 1?
CUSTOM_ATTACKINFO_WHITE_TIGER_COMBO2 <- 41 		  //  : 2?
CUSTOM_ATTACKINFO_WHITE_TIGER_COMBO3 <- 42 		  //  : 3?
CUSTOM_ATTACKINFO_WHITE_TIGER_COMBO4 <- 43 		  //  : 4?
CUSTOM_ATTACKINFO_WHITE_TIGER_COMBO5 <- 44 		  //  : 5?
CUSTOM_ATTACKINFO_WHITE_TIGER_DASH_ATTACK <- 45 		  //  : 
CUSTOM_ATTACKINFO_WHITE_TIGER_JUMP_ATTACK <- 46 		  //  : ??
CUSTOM_ATTACKINFO_SUPLEX_CYCLONE_CRASH <- 47 		  //  ? ? : 
CUSTOM_ATTACKINFO_SUPLEX_CYCLONE_FINISH <- 48 		  //  ? ? :  
CUSTOM_ATTACKINFO_LEG_SUPLEX_EX_SPIN <- 49 		  //   ?? ?
CUSTOM_ATTACKINFO_DASH_PUNCH_EX <- 50 		  //   
CUSTOM_ATTACKINFO_BLOCK_BUSTER_FINISH_EX <- 51 		  //    
CUSTOM_ATTACKINFO_RISING_UPPER_START_EX <- 52 		  //   ?: ?
CUSTOM_ATTACKINFO_RISING_UPPER_EX <- 53 		  //   ?: ?
CUSTOM_ATTACKINFO_RISING_UPPER_FINISH_EX <- 54 		  //   ?: ?
CUSTOM_ATTACKINFO_SUPLEX_CYCLONE_EX <- 55 		  //   ? ?
CUSTOM_ATTACKINFO_SUPLEX_CYCLONE_SPIN_EX <- 56 		  //   ? ? : 	
CUSTOM_ATTACKINFO_STOMP_FINISH <- 57 		  //  
CUSTOM_ATTACKINFO_GROUND_KICK <- 58 		  //  
CUSTOM_ATTACKINFO_LIGHTNING_DRAGON <- 59 		  //  ??
CUSTOM_ATTACKINFO_CRASH_LOW_KICK_SECOND <- 60 		  //  ?? ?? ? 
CUSTOM_ATTACKINFO_THROW_ENEMY_UPKICK <- 61 		  //  ? ?? UP?
CUSTOM_ATTACKINFO_THROW_ENEMY_SIDEKICK <- 62 		  //  ? ?? SIDE?
CUSTOM_ATTACKINFO_THROW_ENEMY_DOWNKICK <- 63 		  //  ? ?? DOWN?
CUSTOM_ATTACKINFO_TRY_GRAB_THROW_ENEMY <- 64 		  //  ?? 
CUSTOM_ATTACKINFO_THROW_WEB_DOUBLE <- 65 		  //   (?)
CUSTOM_ATTACKINFO_LIGHTNING_LOW_KICK <- 66 		  //   (?)
CUSTOM_ATTACKINFO_SUPLEX_GRABCANNON <- 67 		  //  ?  
CUSTOM_ATTACKINFO_NEN_FLOWER <- 68 		  //  ?-?
CUSTOM_ATTACKINFO_TYPHOON <- 69 		  //   
CUSTOM_ATTACKINFO_TYPHOON_LAST <- 70 		  //   
CUSTOM_ATTACKINFO_SPIRAL_NEN_SHOOT <- 71 		  //   ??:??
CUSTOM_ATTACKINFO_NEN_SPEAR <- 72 		  //  ()	
CUSTOM_ATTACKINFO_CHARGE_SPEAR <- 73 		  //  ()	
CUSTOM_ATTACKINFO_HURRICANE_SPEAR <- 74 		  // 	 ?? ()
CUSTOM_ATTACKINFO_CRASH_ROPE <- 75 		  //  ?? ()
CUSTOM_ATTACKINFO_CHAIN_KICK1 <- 76 		  //  ?? 1?()
CUSTOM_ATTACKINFO_CHAIN_KICK2 <- 77 		  //  ?? 2?()
CUSTOM_ATTACKINFO_CHAIN_KICK3 <- 78 		  //  ?? 3?()
CUSTOM_ATTACKINFO_108_STAIRS_KICK_EX <- 79 		  //  108)
CUSTOM_ATTACKINFO_108_STAIRS_PUNCH_EX <- 80 		  //  108)
CUSTOM_ATTACKINFO_108_STAIRS_BLOW_1_EX <- 81 		  //  108)
CUSTOM_ATTACKINFO_108_STAIRS_BLOW_2_EX <- 82 		  //  108)
CUSTOM_ATTACKINFO_108_STAIRS_BLOW_3_EX <- 83 		  //  108)

WEAPON_SUBTYPE_KNUCKLE <- 0 		  //  
WEAPON_SUBTYPE_GAUNTLET <- 1 		  //  ??
WEAPON_SUBTYPE_CLAW <- 2 		  //  
WEAPON_SUBTYPE_BOXING_GLOVE <- 3 		  //  
WEAPON_SUBTYPE_DUMMY <- 4 		  //  UNKNOWN
WEAPON_SUBTYPE_TONFA <- 5 		  //  ?
WEAPON_SUBTYPE_MAX <- 6 

SOUND_ID_STATIC <- 0 		  //    ? ??
SOUND_ID_MOVE <- 1 		  //   
SOUND_ID_ACTIVESTATUS_POISON <- 2 		  //   ?? ??
SOUND_ID_ACTIVESTATUS_BURN <- 3 		  //  ?? ?? ??
SOUND_ID_ACTIVESTATUS_LIGHTNING <- 4 		  //  ? ?? ??
SOUND_ID_AURA_SHIELD <- 5 		  //  Appendage : ? 
SOUND_ID_MAGICAL_TEMPO_UP <- 6 		  //  Appendage : ??
SOUND_ID_DOT_AREA <- 7 		  //  Appendage : 
SOUND_ID_DOT_AREA_DAMAGE <- 8 		  //  Appendage :  
SOUND_ID_DIVINE_LIGHT <- 9 		  //  Appendage : ?? ??
SOUND_ID_SHADOW_BOXER <- 10 		  //  Appendage :  
SOUND_ID_GUARD <- 11 		  //  ? ?
SOUND_ID_CHAKRA_OF_PASSION <- 12 		  //  Appendage :  ?
SOUND_ID_CHAKRA_OF_CALMNESS <- 13 		  //  Appendage :  ?
SOUND_ID_WAVE_MARK <- 14 		  //  Appendage : ??
SOUND_ID_KEIGA <- 15 		  //  Appendage : ?? ??
SOUND_ID_END <- 16 

STATE_PRIORITY_AUTO <- 0 		  //   ?? ? ?   (? ?,  -> ? 
STATE_PRIORITY_USER <- 1 		  //   ? ?   (, ? ??)
STATE_PRIORITY_HALF_FORCE <- 2 		  //  ??  ? ?, ?  ? . (  ??)
STATE_PRIORITY_FORCE <- 3 		  //     . (, ,   ??)
STATE_PRIORITY_IGNORE_FORCE <- 4 		  //  ?  ? . ( ??)

STATE_VIRTUAL_ATTACK <- 19 		  //   ? ->  ? ? ? STATE
STATE_ANTIAIR_UPPER <- 20 		  //  ?
STATE_DUCKING <- 21 		  //  
STATE_SWAY <- 22 		  //  
STATE_GIANT_SWING <- 23 		  //  ?
STATE_REPEATED_SMASH <- 24 		  //  ?
STATE_SMASHER <- 25 		  //  ??
STATE_QUAKE_AREA <- 26 		  //  
STATE_WILL_DRIVER <- 27 		  //  ?? ?̹?
STATE_DUCKING_SKILL <- 28 		  //   ?? 
STATE_LUCKY_STRAIGHT <- 29 		  //   ??
STATE_SECOND_UPPER <- 30 		  //  
STATE_HOLY_COUNTER <- 31 		  //   ??
STATE_GORGEOUS_COMBINATION <- 32 		  //   ??̼?
STATE_CHOPPING_HAMMER <- 33 		  //  ? 
STATE_HURRICANE_OF_JUDGEMENT <- 34 		  //   ??
STATE_HOME_RUN <- 35 		  //  
STATE_BLADE_OF_PURE_WHITE <- 36 		  //   
STATE_HURRICANE_ROLL <- 37 		  //   ??
STATE_THROW_WEAPON <- 38 		  //  ?
STATE_DEFLECT_WALL <- 39 		  //   ??
STATE_SPEAR_OF_VICTORY <- 40 		  //  ?? ?
STATE_HAMMER_OF_CONTRITION <- 41 		  //  ?? 
STATE_HEAVENLY_COMBINATION <- 42 		  //  ??̼?
STATE_DIVINE_CRUSH <- 43 		  //  ?
STATE_SIDEWIND <- 44 		  //  ?ε?
STATE_MACHINE_GUN_JAB <- 45 		  //  ? ??
STATE_THROW_TALISMAN <- 46 		  //  ?
STATE_APOCALYPSE <- 47 		  //  
STATE_GALE_SMASH <- 48 		  //  ?
STATE_ATOMIC_SMASH <- 49 		  //  ??
STATE_BIG_BANG_PUNCH <- 50 		  //  
STATE_BLUE_DRAGON <- 51 		  //  ?
STATE_HEAL_WIND <- 52 		  //  ?? ?
STATE_CUTTING_DARKNESS <- 53 		  //  ??Ұ??
STATE_MACHINE_GUN_JAB_EX <- 54 		  //   ? ??
STATE_HEAVENLY_COMBINATION_EX <- 55 		  //  ??̼?]
STATE_REPEATED_SMASH_EX <- 56 		  //   ?
STATE_DEFLECT_WALL_EX <- 57 		  //   ??[]

SKILL_ANTIAIR_UPPER <- 1 		  //  ??
SKILL_DUCKING <- 2 		  //   
SKILL_SWAY <- 3 		  //  
SKILL_HURRICANE_ROLL <- 4 		  //   ??
SKILL_GIANT_SWING <- 5 		  //  ?
SKILL_CANCEL_ANTIAIR_UPPER <- 6 		  //   ??
SKILL_STRIKING <- 7 		  //  ??
SKILL_SMASHER <- 8 		  //  ??
SKILL_CANCEL_SMASHER <- 9 		  //   ??
SKILL_CHANGE_HP_TO_MP <- 10 		  // 	 ??
SKILL_QUAKE_AREA <- 11 		  //  
SKILL_CANCEL_QUAKE_AREA <- 12 		  //   
SKILL_WILL_DRIVER <- 13 		  //  ?? ?̹?
SKILL_TECHNICAL_MASTERY <- 14 		  //  ? ?
SKILL_BATTLE_AURA_MASTERY <- 15 		  //   ? ?
SKILL_CORKSCREW_MASTERY <- 16 		  //  ?? ?
SKILL_COMBINATION_MASTERY <- 17 		  //  ??̼??
SKILL_HARD_PUNCH_MASTERY <- 18 		  //    ?
SKILL_HP_MAX_UP_PERSONAL <- 19 		  //  ?? ??ε?
SKILL_EMBLEM_OF_SAFEGUARD <- 20 		  //  ?? ??
SKILL_FOUNTAIN_OF_LIFE <- 21 		  //   
SKILL_DIVINE_LIGHT <- 22 		  //  ?? ??
SKILL_REVENGE_OF_LIGHT <- 23 		  //  ? ?
SKILL_HP_MAX_UP_PARTY <- 24 		  //  ?? ?
SKILL_SACRIFICE_OF_SOUL <- 25 		  //  ?? 
SKILL_HEAL_WIND <- 26 		  //  ?? ?
SKILL_DEFLECT_WALL <- 27 		  //   ??
SKILL_FLASH_GLOBE <- 28 		  //  ?? ?
SKILL_EXTENDED_PUNCH <- 29 		  //  
SKILL_HOLY_COUNTER <- 30 		  //   ??
SKILL_GORGEOUS_COMBINATION <- 31 		  //   ??̼?
SKILL_CANCEL_GORGEOUS_COMBINATION <- 32 		  //    ??̼?
SKILL_CHOPPING_HAMMER <- 33 		  //  ? 
SKILL_ARMOR_MASTERY_PLATE_CS <- 34 		  //    ?
SKILL_SHADOW_BOXER <- 35 		  //   
SKILL_DOUBLE_SHADOW_BOXER <- 36 		  //  ?  
SKILL_HURRICANE_OF_JUDGEMENT <- 37 		  //   ??
SKILL_ENTERING_NIRVANA <- 38 		  //  ?
SKILL_OPPRESSION_TALISMAN <- 39 		  //  ?? (??)
SKILL_THUNDERBOLT_TALISMAN <- 40 		  //  ?? (??)
SKILL_HOME_RUN <- 41 		  //  ?? ?? ??
SKILL_QUICK_PARRY <- 42 		  //  ?? 
SKILL_BLADE_OF_PURE_WHITE <- 43 		  //   
SKILL_CANCEL_BLADE_OF_PURE_WHITE <- 44 		  //    
SKILL_GLORIOUS_BLESS <- 45 		  //   ??
SKILL_CANCEL_HURRICANE_ROLL <- 46 		  //    ??
SKILL_CHAKRA_OF_PASSION <- 47 		  //   ?
SKILL_CHAKRA_OF_CALMNESS <- 48 		  //   ?
SKILL_REPEATED_SMASH <- 49 		  //  ?
SKILL_THROW_WEAPON <- 50 		  //  ?
SKILL_SLOW_HEAL <- 51 		  //  ?? ??
SKILL_CURE <- 52 		  //  
SKILL_BLESS <- 53 		  //   ??
SKILL_GRACE_OF_GOD <- 54 		  //  ? ?
SKILL_FAST_HEAL <- 55 		  //  ? ??
SKILL_DUCKING_STRAIGHT <- 56 		  //   ??
SKILL_DUCKING_BODYBLOW <- 57 		  //   
SKILL_DUCKING_UPPER <- 58 		  //   ?
SKILL_CANCEL_DUCKING <- 59 		  //   
SKILL_CANCEL_SWAY <- 60 		  //   
SKILL_LUCKY_STRAIGHT <- 61 		  //   ??
SKILL_CANCEL_LUCKY_STRAIGHT <- 62 		  //    ??
SKILL_SECOND_UPPER <- 63 		  //   ?
SKILL_GRASP_HAND_OF_ANGER <- 64 		  //  ?? 
SKILL_CANCEL_GRASP_HAND_OF_ANGER <- 65 		  //   ?? 
SKILL_CHARGE_WEAPON <- 66 		  //  
SKILL_FORCE_OF_EXORCISM <- 67 		  //  ? 
SKILL_ARMOR_MASTERY_CLOTH_EC <- 68 
SKILL_HYUN_MOO <- 69 		  //  ?  - ?
SKILL_BAEK_HO <- 70 		  //  ?  - 
SKILL_CANCEL_REPEATED_SMASH <- 71 		  //   ?
SKILL_CANCEL_HOME_RUN <- 72 		  //   
SKILL_SPEAR_OF_VICTORY <- 73 		  //  ?? ?
SKILL_HAMMER_OF_CONTRITION <- 74 		  //  ?? 
SKILL_HEAVENLY_COMBINATION <- 75 		  //  ??̼?
SKILL_DIVINE_CRUSH <- 76 		  //  ?
SKILL_SIDEWIND <- 77 		  //  ?ε?
SKILL_MACHINE_GUN_JAB <- 78 		  //  ? ??
SKILL_CANCEL_SIDEWIND <- 79 		  //   ?ε?
SKILL_CANCEL_MACHINE_GUN_JAB <- 80 		  //   ? ??
SKILL_JUDGEMENT <- 81 		  //   ?
SKILL_BIG_WEAPON_MASTERY <- 82 		  //  ? ?
SKILL_BATTLE_AXE_MASTERY <- 83 		  //   ?
SKILL_APOCALYPSE <- 84 		  //  
SKILL_GALE_SMASH <- 85 		  //  ?
SKILL_AURA_OF_FAITH <- 86 		  //  ?? ?
SKILL_DRYOUT <- 87 		  //  ?̾??
SKILL_ATOMIC_SMASH <- 88 		  //  ??
SKILL_RADIATE_FIGHTING_AURA <- 89 		  //  ? 
SKILL_BIG_BANG_PUNCH <- 90 		  //  
SKILL_ARMOR_MASTERY_LIGHT_IF <- 91 		  //  ?? ?:??
SKILL_ARMOR_MASTERY_PLATE_EC <- 92 		  //   ?:?
SKILL_BLUE_DRAGON <- 93 		  //  ?
SKILL_CANCEL_ENTERING_NIRVANA <- 94 		  //   ?
SKILL_CANCEL_GALE_SMASH <- 95 		  //   ?
SKILL_ARMOR_MASTERY_HEAVY_EC <- 96 		  //   ?:?
SKILL_GRACE_OF_COURAGE <- 97 		  //  
SKILL_GRACE_OF_PROTECTION <- 98 		  //  ?? ?
SKILL_RISING_AREA <- 99 		  //  ??
SKILL_CUTTING_DARKNESS <- 100 		  //  ??Ұ??
SKILL_SHIKIGAMI <- 101 		  //  ?? ??
SKILL_CANCEL_RISING_AREA <- 102 		  //   ??
SKILL_MACHINE_GUN_JAB_EX <- 103 		  //   ? ??
SKILL_HEAVENLY_COMBINATION_EX <- 104 		  //  ׹̼?]
SKILL_REPEATED_SMASH_EX <- 105 		  //   ?
SKILL_VERMILIONBIRD_TALISMAN <- 106 		  //  ??
SKILL_CROSS_CRASH <- 107 		  //  ? ??, ?? : ? ??, HotCross ??
SKILL_FLASH_GLOBE_EX <- 108 		  //  ?? ?[]
SKILL_DEFLECT_WALL_EX <- 109 		  //   ??[]
SKILL_HYUN_MOO_EX <- 110 		  //  ?[]
SKILL_GROUND_CRASH <- 111 		  //  ?? ??, ?? ox crash (??)
SKILL_CANCEL_GROUND_CRASH <- 112 		  //   ?? ??
SKILL_SLOW_HEAL_EX <- 140 		  //  ?? ?? ?
SKILL_LUCKY_STRAIGHT_EX <- 141 		  //   ?? ?
SKILL_QUAKE_AREA_EX <- 142 		  //   ?
SKILL_GRASP_HAND_OF_ANGER_EX <- 143 		  //  ?? 
SKILL_SPEAR_OF_VICTORY_EX <- 144 		  //  ?? ? ?
SKILL_REVENGE_OF_LIGHT_EX <- 145 		  //  ? ? ?
SKILL_DUCKING_STRAIGHT_EX <- 146 		  //   ?? ?
SKILL_WILL_DRIVER_EX <- 147 		  //  ?? ?̹??
SKILL_OPPRESSION_TALISMAN_EX <- 148 		  //  ?? ?
SKILL_THROW_WEAPON_EX <- 149 		  //  ? ?

CUSTOM_ANI_JUMP_PUNCH <- 0 		  //  ?  (  ??)
CUSTOM_ANI_ANTIAIR_UPPER <- 1 		  //  ?
CUSTOM_ANI_DUCKING <- 2 		  //  
CUSTOM_ANI_SWAY <- 3 		  //  
CUSTOM_ANI_GIANT_SWING_READY <- 4 		  //  ? : 
CUSTOM_ANI_GIANT_SWING <- 5 		  //  ? : 
CUSTOM_ANI_GIANT_SWING_FINAL <- 6 		  //  ? : 
CUSTOM_ANI_SMASHER_TRY_GRAB <- 7 		  //  ?? : ??
CUSTOM_ANI_SMASHER_SUCCESS_GRAB <- 8 		  //  ?? : ?
CUSTOM_ANI_SMASHER_DASH <- 9 		  //  ?? : ?? 
CUSTOM_ANI_DUCKING_BODYBLOW <- 10 		  //  
CUSTOM_ANI_QUAKE_AREA <- 11 		  //  
CUSTOM_ANI_WILL_DRIVER <- 12 		  //  ?? ?̹?
CUSTOM_ANI_WILL_DRIVER_SECOND <- 13 		  //  ?? ?̹?:  ? ?
CUSTOM_ANI_LUCKY_STRAIGHT <- 14 		  //  ??
CUSTOM_ANI_DUCKING_STRAIGHT <- 15 		  //   ??
CUSTOM_ANI_SECOND_UPPER <- 16 		  //   ?
CUSTOM_ANI_DUCKING_UPPER <- 17 		  //   ?
CUSTOM_ANI_HOLY_COUNTER_PRAY <- 18 		  //   ?? : ??
CUSTOM_ANI_HOLY_COUNTER_BODYBLOW <- 19 		  //   ?? : ??
CUSTOM_ANI_GORGEOUS_COMBINATION <- 20 		  //   ??̼?
CUSTOM_ANI_CHOPPING_HAMMER <- 21 		  //  ? 
CUSTOM_ANI_HURRICANE_OF_JUDGEMENT <- 22 		  //   ??
CUSTOM_ANI_HURRICANE_OF_JUDGEMENT2 <- 23 		  //   ?? 2?
CUSTOM_ANI_HOME_RUN_GRAB <- 24 		  //   : 
CUSTOM_ANI_HOME_RUN_CHARGE <- 25 		  //   : & ?
CUSTOM_ANI_HOME_RUN_SMASH <- 26 		  //   : ?
CUSTOM_ANI_BLADE_OF_PURE_WHITE <- 27 		  //   
CUSTOM_ANI_HURRICANE_ROLL_HOOK <- 28 		  //   ?? : ??
CUSTOM_ANI_HURRICANE_ROLL_UPPER <- 29 		  //   ?? : ?
CUSTOM_ANI_REPEATED_SMASH_START <- 30 		  //  ? : ??
CUSTOM_ANI_REPEATED_SMASH <- 31 		  //  ? : 
CUSTOM_ANI_REPEATED_SMASH_FINAL <- 32 		  //  ? : 
CUSTOM_ANI_THROW_WEAPON_READY <- 33 		  //  ? : 
CUSTOM_ANI_THROW_WEAPON_SWING <- 34 		  //  ? :  (? 1  
CUSTOM_ANI_THROW_WEAPON_THROW <- 35 		  //  ? :  (? ?  -> )
CUSTOM_ANI_DEFLECT_WALL <- 36 		  //   ??
CUSTOM_ANI_SPEAR_OF_VICTORY_READY <- 37 		  //  ?? ? : &?
CUSTOM_ANI_SPEAR_OF_VICTORY_THROW <- 38 		  //  ?? ? : 
CUSTOM_ANI_HAMMER_OF_CONTRITION <- 39 		  //  ?? 
CUSTOM_ANI_HEAVENLY_COMBINATION <- 40 		  //  ??̼?
CUSTOM_ANI_DIVINE_CRUSH <- 41 		  //  ?
CUSTOM_ANI_INFIGHTER_ATTACK12 <- 42 		  //  ??  1,2?
CUSTOM_ANI_INFIGHTER_ATTACK3 <- 43 		  //  ??  3?
CUSTOM_ANI_INFIGHTER_ATTACK4 <- 44 		  //  ??  4?
CUSTOM_ANI_INFIGHTER_ATTACK5 <- 45 		  //  ??  5?
CUSTOM_ANI_EXORCIST_ATTACK1 <- 46 		  //  ?  1?
CUSTOM_ANI_EXORCIST_ATTACK2 <- 47 		  //  ?  2?
CUSTOM_ANI_EXORCIST_ATTACK3 <- 48 		  //  ?  3?
CUSTOM_ANI_SIDEWIND <- 49 		  //  ?ε
CUSTOM_ANI_SIDEWIND_SECOND <- 50 		  //  ?ε??
CUSTOM_ANI_MACHINE_GUN_JAB <- 51 		  //  ? ?? : 
CUSTOM_ANI_MACHINE_GUN_JAB_FINISH <- 52 		  //  ? ?? : ?
CUSTOM_ANI_MACHINE_GUN_JAB_APPEND <- 53 		  //  ? ?? : ?
CUSTOM_ANI_THROW_TALISMAN1 <- 54 		  //  ? : 1
CUSTOM_ANI_THROW_TALISMAN2 <- 55 		  //  ? : 2
CUSTOM_ANI_APOCALYPSE <- 56 		  //  
CUSTOM_ANI_GALE_SMASH1 <- 57 		  //  ? : ??
CUSTOM_ANI_GALE_SMASH2 <- 58 		  //  ? : 
CUSTOM_ANI_ATOMIC_SMASH <- 59 		  //  ??
CUSTOM_ANI_BIG_BANG_PUNCH_READY <- 60 		  //   : 
CUSTOM_ANI_BIG_BANG_PUNCH1 <- 61 		  //   : 1?
CUSTOM_ANI_BIG_BANG_PUNCH2 <- 62 		  //   : 2?
CUSTOM_ANI_BIG_BANG_PUNCH3 <- 63 		  //   : 3?
CUSTOM_ANI_BIG_BANG_PUNCH4 <- 64 		  //   : 4?
CUSTOM_ANI_HEAL_WIND_CAST <- 65 		  //  ?? ? : ??
CUSTOM_ANI_HEAL_WIND_BLAST <- 66 		  //  ?? ? : 
CUSTOM_ANI_BLUE_DRAGON1 <- 67 		  //  ?: ?
CUSTOM_ANI_BLUE_DRAGON2 <- 68 		  //  ?: 
CUSTOM_ANI_BLUE_DRAGON3 <- 69 		  //  ?: 
CUSTOM_ANI_CUTTING_DARKNESS_CHARGE <- 70 		  //  ??Ұ??: ?
CUSTOM_ANI_CUTTING_DARKNESS_SMASH <- 71 		  //  ??Ұ??: 
CUSTOM_ANI_CUTTING_DARKNESS_FULL_SMASH <- 72 		  //   : ? 
CUSTOM_ANI_MACHINE_GUN_JAB_EX_LEFT <- 73 		  //   ? ??  ??
CUSTOM_ANI_MACHINE_GUN_JAB_EX_RIGHT <- 74 		  //   ? ??  ??
CUSTOM_ANI_MACHINE_GUN_JAB_EX_FINISH <- 75 		  //   ? ?? ?
CUSTOM_ANI_HEAVENLY_COMBINATION_EX <- 76 		  //  ??̼?]
CUSTOM_ANI_REPEATED_SMASH_EX_FINISH <- 77 		  //   ? 
CUSTOM_ANI_GROUND_CRASH <- 78 		  //  ?? ??

CUSTOM_ATTACKINFO_JUMP_PUNCH <- 0 		  //  ?  (?  ??)
CUSTOM_ATTACKINFO_DASH_ATTACK_SMASH <- 1 		  //  ? 2??
CUSTOM_ATTACKINFO_ANTIAIR_UPPER <- 2 		  //  ??
CUSTOM_ATTACKINFO_GIANT_SWING <- 3 		  //  ? : 
CUSTOM_ATTACKINFO_GIANT_SWING_FINAL <- 4 		  //  ? : 
CUSTOM_ATTACKINFO_SMASHER_TRY <- 5 		  //  ?? 
CUSTOM_ATTACKINFO_SMASHER_DASH <- 6 		  //  ?? 
CUSTOM_ATTACKINFO_SMASHER_THROW <- 7 		  //  ?? 
CUSTOM_ATTACKINFO_QUAKE_AREA <- 8 		  //  
CUSTOM_ATTACKINFO_LUCKY_STRAIGHT <- 9 		  //   ??
CUSTOM_ATTACKINFO_SECOND_UPPER <- 10 		  //   ?
CUSTOM_ATTACKINFO_DUCKING_STRAIGHT <- 11 		  //   ??
CUSTOM_ATTACKINFO_DUCKING_BODYBLOW <- 12 		  //   
CUSTOM_ATTACKINFO_DUCKING_UPPER <- 13 		  //   ?
CUSTOM_ATTACKINFO_HOLY_COUNTER <- 14 		  //   ??
CUSTOM_ATTACKINFO_GORGEOUS_COMBINATION1 <- 15 		  //   ??̼?: ??
CUSTOM_ATTACKINFO_GORGEOUS_COMBINATION2 <- 16 		  //   ??̼?: ??
CUSTOM_ATTACKINFO_GORGEOUS_COMBINATION3 <- 17 		  //   ??̼?: ??
CUSTOM_ATTACKINFO_CHOPPING_HAMMER <- 18 		  //  ? 
CUSTOM_ATTACKINFO_HURRICANE_OF_JUDGEMENT <- 19 		  //   ??
CUSTOM_ATTACKINFO_HOME_RUN_GRAB <- 20 		  //   : 
CUSTOM_ATTACKINFO_HOME_RUN_HIT <- 21 		  //   : ? ?? 1?
CUSTOM_ATTACKINFO_HOME_RUN_SMASH <- 22 		  //   : 
CUSTOM_ATTACKINFO_BLADE_OF_PURE_WHITE <- 23 		  //   
CUSTOM_ATTACKINFO_HURRICANE_ROLL_HOOK <- 24 		  //   ?? : ??
CUSTOM_ATTACKINFO_HURRICANE_ROLL_UPPER <- 25 		  //   ?? : ?
CUSTOM_ATTACKINFO_REPEATED_SMASH <- 26 		  //  ? : 
CUSTOM_ATTACKINFO_REPEATED_SMASH_FINAL <- 27 		  //  ? : 
CUSTOM_ATTACKINFO_THROW_WEAPON <- 28 		  //  ? : ? 
CUSTOM_ATTACKINFO_HAMMER_OF_CONTRITION <- 29 		  //  ?? 
CUSTOM_ATTACKINFO_HEAVENLY_COMBINATION1 <- 30 		  //  ??̼?: 1?
CUSTOM_ATTACKINFO_HEAVENLY_COMBINATION2 <- 31 		  //  ??̼?: 2?
CUSTOM_ATTACKINFO_HEAVENLY_COMBINATION3 <- 32 		  //  ??̼?: 3?
CUSTOM_ATTACKINFO_DIVINE_CRUSH <- 33 		  //  ?
CUSTOM_ATTACKINFO_INFIGHTER_ATTACK1 <- 34 		  //  ??  1?
CUSTOM_ATTACKINFO_INFIGHTER_ATTACK2 <- 35 		  //  ??  2?
CUSTOM_ATTACKINFO_INFIGHTER_ATTACK3 <- 36 		  //  ??  3?
CUSTOM_ATTACKINFO_INFIGHTER_ATTACK4 <- 37 		  //  ??  4?
CUSTOM_ATTACKINFO_INFIGHTER_ATTACK5 <- 38 		  //  ??  5?
CUSTOM_ATTACKINFO_EXORCIST_ATTACK1 <- 39 		  //  ?  1?
CUSTOM_ATTACKINFO_EXORCIST_ATTACK2 <- 40 		  //  ?  2?
CUSTOM_ATTACKINFO_EXORCIST_ATTACK3 <- 41 		  //  ?  3?
CUSTOM_ATTACKINFO_SIDEWIND <- 42 		  //  ?ε?
CUSTOM_ATTACKINFO_SIDEWIND_SECOND <- 43 		  //  ?ε??
CUSTOM_ATTACKINFO_MACHINE_GUN_JAB <- 44 		  //  ? ?? : 
CUSTOM_ATTACKINFO_MACHINE_GUN_JAB_FINISH <- 45 		  //  ? ?? : ?
CUSTOM_ATTACKINFO_MACHINE_GUN_JAB_APPEND <- 46 		  //  ? ?? : ?
CUSTOM_ATTACKINFO_THROW_TALISMAN1 <- 47 		  //  ? : 1
CUSTOM_ATTACKINFO_THROW_TALISMAN2 <- 48 		  //  ? : 2
CUSTOM_ATTACKINFO_GALE_SMASH1 <- 49 		  //  ? : ??
CUSTOM_ATTACKINFO_GALE_SMASH2 <- 50 		  //  ? : 
CUSTOM_ATTACKINFO_ATOMIC_SMASH_SWING <- 51 		  //  ?? : 
CUSTOM_ATTACKINFO_ATOMIC_SMASH_SMASH <- 52 		  //  ?? : ?
CUSTOM_ATTACKINFO_BIG_BANG_PUNCH_READY <- 53 		  //   : 
CUSTOM_ATTACKINFO_BIG_BANG_PUNCH1 <- 54 		  //   : 1?
CUSTOM_ATTACKINFO_BIG_BANG_PUNCH2 <- 55 		  //   : 2?
CUSTOM_ATTACKINFO_BIG_BANG_PUNCH3 <- 56 		  //   : 3?
CUSTOM_ATTACKINFO_BIG_BANG_PUNCH4 <- 57 		  //   : 4?
CUSTOM_ATTACKINFO_BLUE_DRAGON <- 58 		  //  ?
CUSTOM_ATTACKINFO_CUTTING_DARKNESS <- 59 		  //  ??Ұ??
CUSTOM_ATTACKINFO_MACHINE_GUN_JAB_EX <- 60 		  //   ? ?? : 
CUSTOM_ATTACKINFO_MACHINE_GUN_JAB_EX_FINISH <- 61 		  //   ? ?? : ?
CUSTOM_ATTACKINFO_HEAVENLY_COMBINATION_EX2 <- 62 		  //  ??̼?: 2?
CUSTOM_ATTACKINFO_HEAVENLY_COMBINATION_EX3 <- 63 		  //  ??̼?: 3?
CUSTOM_ATTACKINFO_HEAVENLY_COMBINATION_EX4 <- 64 		  //  ??̼?: 4?
CUSTOM_ATTACKINFO_HEAVENLY_COMBINATION_EX5 <- 65 		  //  ??̼?: 5?
CUSTOM_ATTACKINFO_REPEATED_SMASH_EX_LIFT <- 66 		  //   ? ?
CUSTOM_ATTACKINFO_REPEATED_SMASH_EX_FINAL <- 67 		  //   ? 
CUSTOM_ATTACKINFO_GROUND_CRASH1 <- 68 		  //  ?? ?? 1?
CUSTOM_ATTACKINFO_GROUND_CRASH2 <- 69 		  //  ?? ?? 2?


ATTACK_DIRECTION_UP <- 0 		  //  
ATTACK_DIRECTION_HORIZON <- 1 		  //  ?
ATTACK_DIRECTION_DOWN <- 2 		  //  ?
ATTACK_DIRECTION_MAX <- 3 

ATTACKTYPE_PHYSICAL <- 0 		  //  ? ? ?
ATTACKTYPE_MAGICAL <- 1 		  //  ? ? ?  
ATTACKTYPE_ABSOLUTE <- 2 		  //  ? ?
ATTACKTYPE_MAX <- 3 

ATTACKTARGET_OWN <- 0 		  //  
ATTACKTARGET_FRIEND <- 1 		  //  
ATTACKTARGET_ENEMY <- 2 		  //  (?  ??) ??

DAMAGEACT_NONE <- 0 		  //  ? ?
DAMAGEACT_DAMAGE <- 1 		  //   
DAMAGEACT_DOWN <- 2 		  //  
DAMAGEACT_DAMAGE_EXCEPT_HUMAN <- 3 		  //  ?? ,  ??

KNOCK_BACK_TYPE_NORMAL <- 0 		  //  
KNOCK_BACK_TYPE_KNOCK_BACK <- 1 		  //   ?  ()
KNOCK_BACK_TYPE_SHORT_KNOCK_BACK_ <- 2 		  //   ??  ()
KNOCK_BACK_TYPE_PIXEL_WITHOUT_DAMAGE_TIME <- 3 		  //  NORMAL_DAMAGE_BACK_TIME ?    , ??  ?? ?? ?
KNOCK_BACK_TYPE_NOT_BACK <- -1 		  //   ?

HIT_DIRECTION_AUTO <- 0 		  //   
HIT_DIRECTION_FRONT <- 1 		  //  
HIT_DIRECTION_BACK <- 2 		  //  
HIT_DIRECTION_OUTER <- 3 		  //  
HIT_DIRECTION_INNER <- 4 		  //  ??

WEAPON_SUBTYPE_CROSS <- 0 		  //  ??
WEAPON_SUBTYPE_ROSARY <- 1 		  //  ?
WEAPON_SUBTYPE_TOTEM <- 2 		  //  ?
WEAPON_SUBTYPE_SCYTHE <- 3 		  //  ??
WEAPON_SUBTYPE_BATTLE_AXE <- 4 		  //   
WEAPON_SUBTYPE_MAX <- 5 

GROW_TYPE_PRIEST <- 0 		  //  ?
GROW_TYPE_CRUSADER <- 1 		  //  
GROW_TYPE_INFIGHTER <- 2 		  //  ??
GROW_TYPE_EXORCIST <- 3 		  //  ?
GROW_TYPE_AVENGER <- 4 		  //  ?
GROW_TYPE_PRIEST_G <- 5 		  //  ?G

EXTENDED_PUNCH_MOTION_DASH_ATTACK <- 0 		  //  ?
EXTENDED_PUNCH_MOTION_SECOND_UPPER <- 1 		  //   ?
EXTENDED_PUNCH_MOTION_MAX <- 2 

BASE_ATTACK_TYPE_DEFAULT <- 0 		  //  ??
BASE_ATTACK_TYPE_INFIGHTER <- 1 		  //  ?? 
BASE_ATTACK_TYPE_EXORCIST <- 2 		  //  ? 

BATTLE_AURA_MOTION_ATTACK_12 <- 0 		  //  1,2 (??)
BATTLE_AURA_MOTION_ATTACK_3 <- 1 		  //  3 (??)
BATTLE_AURA_MOTION_ATTACK_4 <- 2 		  //  4 (?)
BATTLE_AURA_MOTION_ATTACK_5 <- 3 		  //  5 (?
BATTLE_AURA_MOTION_GORGEOUS_COMBINATION <- 4 		  //   ??̼?
BATTLE_AURA_MOTION_SIDEWIND <- 5 		  //  ?ε?
BATTLE_AURA_MOTION_SIDEWIND_SECOND <- 6 		  //  ?ε??
BATTLE_AURA_MOTION_MAX <- 7 



CHANGE_STATUS_TYPE_PHYSICAL_ATTACK <- 0 		  //  ? ?
CHANGE_STATUS_TYPE_MAGICAL_ATTACK <- 1 		  //  ? ?
CHANGE_STATUS_TYPE_MAGICAL_DEFENSE <- 2 		  //  ? ?
CHANGE_STATUS_TYPE_PHYSICAL_DEFENSE <- 3 		  //  ? 
CHANGE_STATUS_TYPE_EQUIPMENT_PHYSICAL_ATTACK <- 4 		  //  
CHANGE_STATUS_TYPE_EQUIPMENT_PHYSICAL_DEFENSE <- 5 		  //  ? 
CHANGE_STATUS_TYPE_PHYSICAL_ATTACK_BONUS <- 6 		  //  ? ? ??
CHANGE_STATUS_TYPE_MAGICAL_ATTACK_BONUS <- 7 		  //  ? ? ??
CHANGE_STATUS_TYPE_JUMP_POWER <- 8 		  //  
CHANGE_STATUS_TYPE_JUMP_SPEED_RATE <- 9 		  //  ? 
CHANGE_STATUS_TYPE_ATTACK_SPEED <- 10 		  //  ? 
CHANGE_STATUS_TYPE_MOVE_SPEED <- 11 		  //   
CHANGE_STATUS_TYPE_CAST_SPEED <- 12 		  //  ? 
CHANGE_STATUS_TYPE_HP_MAX <- 13 		  //  HP MAX
CHANGE_STATUS_TYPE_HP_REGEN_RATE <- 14 		  //  HP 
CHANGE_STATUS_TYPE_PHYSICAL_CRITICAL_HIT_RATE <- 15 		  //  ?   
CHANGE_STATUS_TYPE_MAGICAL_CRITICAL_HIT_RATE <- 16 		  //  ?   
CHANGE_STATUS_TYPE_PHYSICAL_BACK_ATTACK_CRITICAL <- 17 		  //  ??  
CHANGE_STATUS_TYPE_MAGICAL_BACK_ATTACK_CRITICAL <- 18 		  //  ??  
CHANGE_STATUS_TYPE_CRITICAL_TOLERANCE_RATE <- 19 		  //   ?
CHANGE_STATUS_TYPE_ELEMENT_TOLERANCE_FIRE <- 20 		  //  ??
CHANGE_STATUS_TYPE_ELEMENT_TOLERANCE_WATER <- 21 		  //  
CHANGE_STATUS_TYPE_ELEMENT_TOLERANCE_DARK <- 22 		  //  ??
CHANGE_STATUS_TYPE_ELEMENT_TOLERANCE_LIGHT <- 23 		  //  ??Ӽ??
CHANGE_STATUS_TYPE_ELEMENT_TOLERANCE_ALL <- 24 		  //  ?
CHANGE_STATUS_TYPE_ELEMENT_TOLERANCE_ZERO <- 25 		  //  ?? 0
CHANGE_STATUS_TYPE_ACTIVESTATUS_TOLERANCE_ALL <- 26 		  //  ?
CHANGE_STATUS_TYPE_ACTIVEPROPERTY_STUCK <- 27 		  //  ?()
CHANGE_STATUS_TYPE_BACK_ATTACK_STUCK_TOLERANCE <- 28 		  //   ? [? ] (% ?)
CHANGE_STATUS_TYPE_MP_REGEN_RATE <- 29 		  //  MP  
CHANGE_STATUS_TYPE_EXTRA_SPEED_RATE <- 30 		  //  ?? ?
CHANGE_STATUS_TYPE_EQUIPMENT_MAGICAL_ATTACK <- 31 		  //  ? ?
CHANGE_STATUS_TYPE_EQUIPMENT_MAGICAL_DEFENSE <- 32 		  //  ? 
CHANGE_STATUS_TYPE_STUCK <- 33 		  //  ? [? ](?)
CHANGE_STATUS_TYPE_HIT_RECOVERY <- 34 		  //   ?
CHANGE_STATUS_TYPE_MELEE_HIT_DELAY <- 35 		  //  ? ? ?? ??
CHANGE_STATUS_TYPE_EQUIPMENT_ALL_STAT <- 36 		  //  ?? ?? ??.
CHANGE_STATUS_TYPE_CUSTOM <- 37 
CHANGE_STATUS_TYPE_EXP_DOUBLE <- 38 		  //  ?? 2??
CHANGE_STATUS_TYPE_EVIL_UP <- 39 		  //  ?? ?
CHANGE_STATUS_TYPE_EVIL_DOWN <- 40 		  //  92 ?? ? 
CHANGE_STATUS_TYPE_RIGIDITY <- 41 		  //  
CHANGE_STATUS_TYPE_ELEMENT_ATTACK_FIRE <- 42 		  //  ? 
CHANGE_STATUS_TYPE_ELEMENT_ATTACK_WATER <- 43 		  //  ?? 
CHANGE_STATUS_TYPE_ELEMENT_ATTACK_DARK <- 44 		  //  ? 
CHANGE_STATUS_TYPE_ELEMENT_ATTACK_LIGHT <- 45 		  //  ??Ӽ?
CHANGE_STATUS_TYPE_ELEMENT_ATTACK_ALL <- 46 		  //   
CHANGE_STATUS_TYPE_DISEASE <- 47 		  //  ?
CHANGE_STATUS_TYPE_MP_MAX <- 48 		  //  MP MAX
CHANGE_STATUS_TYPE_COOLTIME_DECLINE <- 49 		  //   ??
CHANGE_STATUS_TYPE_PHYSICAL_CRITICAL_DAMAGE_RATE <- 50 		  //  ?   ? ?
CHANGE_STATUS_TYPE_MAGICAL_CRITICAL_DAMAGE_RATE <- 51 		  //  ?   ? ?
CHANGE_STATUS_TYPE_BLOODWAR_GROW_ABILITY <- 52 		  //  (?) ? 
CHANGE_STATUS_TYPE_ADDITIONAL_PHYSICAL_GENUINE_ATTACK <- 53 		  //  ?  ? ?? 
CHANGE_STATUS_TYPE_ADDITIONAL_MAGICAL_GENUINE_ATTACK <- 54 		  //  ?  ? ?? 
CHANGE_STATUS_TYPE_SUMMON_SKILL_POWER_BONUS_RATE <- 55 		  //   ?  ?? ?
CHANGE_STATUS_TYPE_ANTIEVIL <- 56 		  //  ? ??  ?
CHANGE_STATUS_TYPE_PHYSICAL_ABSOLUTE_DAMAGE <- 57 		  //  ? ?  or ? ????
CHANGE_STATUS_GHOST_TRAIN_NO_BREATH_TIME <- 58 		  //  ? ?  ?
CHANGE_STATUS_CHARACTER_LINK <- 59 		  //  ?? 
CHANGE_STATUS_GOLD_INCREASE <- 60 
CHANGE_STATUS_TYPE_MAX <- 60 

OBJECTTYPE_OBJECT <- 0 		  //  ?? ?
OBJECTTYPE_COLLISION <- 1 		  //  ?? ? (OBJECTTYPE_OBJECT ?)
OBJECTTYPE_ACTIVE <- 17 		  //   ? (OBJECTTYPE_COLLISION ?)
OBJECTTYPE_CHARACTER <- 273 		  //  ?? ? (OBJECTTYPE_ACTIVE ?)
OBJECTTYPE_MONSTER <- 529 		  //  ? ? (OBJECTTYPE_ACTIVE ?)
OBJECTTYPE_RIDABLEOBJECT <- 4625 		  //   ? ? (OBJECTTYPE_MONSTER ?)
OBJECTTYPE_PASSIVE <- 33 		  //  ? ? (OBJECTTYPE_COLLISION ?)
OBJECTTYPE_ITEM <- 289 		  //   ? (OBJECTTYPE_PASSIVE ?)
OBJECTTYPE_TRAP <- 545 		  //   ? (OBJECTTYPE_PASSIVE ?)
OBJECTTYPE_BREAKABLE <- 1057 		  //    ?(?? ?) (OBJECTTYPE_PASSIVE ?)
OBJECTTYPE_PET <- 65 		  //   (OBJCTTYPE_COLLISION ?)
OBJECTTYPE_CREATURE <- 129 		  //  ?? (OBJCTTYPE_COLLISION ?)
OBJECTTYPE_DRAWONLY <- 2 		  //  ?? ? ? (OBJECTTYPE_OBJECT ?)
OBJECTTYPE_VIRTUALCHARACTER <- 18 		  //  ? ? ? ?? (OBJECTTYPE_DRAWONLY ?)
OBJECTTYPE_NPC <- 34 		  //   NPC (OBJECTTYPE_DRAWONLY ?)
OBJECTTYPE_DONKEY <- 66 		  //   ? (OBJECTTYPE_DRAWONLY ?)
OBJECTTYPE_VIRTUALCREATURE <- 130 		  //  ? ? ? ??(OBJECTTYPE_DRAWONLY ?)
OBJECTTYPE_DISJOINTSHOP <- 258 		  //   ??  ?(OBJECTTYPE_DRAWONLY ?)
OBJECTTYPE_VIRTUALMONSTER <- 514 		  //  ? ? ? ? (OBJECTTYPE_DRAWONLEY ?)
OBJECTTYPE_NONE_DELETE <- 1026 		  //  ? ? ?? ??  ? (OBJECTTYPE_DRAWONLEY ?) 
OBJECTTYPE_DEFINE_END <- 61440 


CONVERT_TABLE_TYPE_DAMAGE <- 0 		  //  
CONVERT_TABLE_TYPE_DEFENSE <- 1 		  //  ?
CONVERT_TABLE_TYPE_HP <- 2 		  //  HP MAX
CONVERT_TABLE_TYPE_PHYSICAL_ATTACK <- 3 		  //  ??
CONVERT_TABLE_TYPE_PHYSICAL_DEFENSE <- 4 		  //  
CONVERT_TABLE_TYPE_MAGICAL_ATTACK <- 5 		  //  ?
CONVERT_TABLE_TYPE_MAGICAL_DEFENSE <- 6 		  //  ??
CONVERT_TABLE_TYPE_PHYSICAL_ABSOLUTE_DAMAGE <- 7 		  //  ? ? 
CONVERT_TABLE_TYPE_PHYSICAL_DAMAGE_REDUCE <- 8 		  //  ?  ?
CONVERT_TABLE_TYPE_MAGICAL_ABSOLUTE_DAMAGE <- 9 		  //  ? ? 
CONVERT_TABLE_TYPE_MAGICAL_DAMAGE_REDUCE <- 10 		  //  ?  ?
CONVERT_TABLE_TYPE_ACTIVESTATUS_DAMAGE_REDUCE <- 11 		  //  ?  ?.
CONVERT_TABLE_TYPE_MP <- 12 		  //  MP MAX
CONVERT_TABLE_TYPE_SKILL_POWER <- 13 		  //   ?
CONVERT_TABLE_TYPE_MAX <- 14 

ENUM_EQUIPMENTTYPE_AVATAR_HEADGEAR <- 0 		  //  ? ?
ENUM_EQUIPMENTTYPE_AVATAR_HAIR <- 1 		  //   ?
ENUM_EQUIPMENTTYPE_AVATAR_FACE <- 2 		  //  ?? ?
ENUM_EQUIPMENTTYPE_AVATAR_JACKET <- 3 		  //  ? ?
ENUM_EQUIPMENTTYPE_AVATAR_PANTS <- 4 		  //  ? ?
ENUM_EQUIPMENTTYPE_AVATAR_SHOES <- 5 		  //   ?
ENUM_EQUIPMENTTYPE_AVATAR_BREAST <- 6 		  //  ? ?
ENUM_EQUIPMENTTYPE_AVATAR_WAIST <- 7 		  //  ?? ?
ENUM_EQUIPMENTTYPE_AVATAR_SKIN <- 8 		  //   ?
ENUM_EQUIPMENTTYPE_AVATAR_AURORA <- 9 		  //  ?? ?
ENUM_EQUIPMENTTYPE_WEAPON <- 10 		  //  ?
ENUM_EQUIPMENTTYPE_TITLE <- 11 		  //  ??
ENUM_EQUIPMENTTYPE_JACKET <- 12 		  //  ?
ENUM_EQUIPMENTTYPE_SHOULDER <- 13 		  //  
ENUM_EQUIPMENTTYPE_PANTS <- 14 		  //  ?
ENUM_EQUIPMENTTYPE_SHOES <- 15 		  //  
ENUM_EQUIPMENTTYPE_WAIST <- 16 		  //  ??
ENUM_EQUIPMENTTYPE_AMULET <- 17 		  //  ??
ENUM_EQUIPMENTTYPE_WRIST <- 18 		  //  ?
ENUM_EQUIPMENTTYPE_RING <- 19 		  //  ?
ENUM_EQUIPMENTTYPE_SUPPORT <- 20 		  //  ?
ENUM_EQUIPMENTTYPE_MAGIC_STONE <- 21 		  //  
ENUM_EQUIPMENTTYPE_MAX <- 22 
ENUM_EQUIPMENTTYPE_AVATAR_START <- 0 		  //  ? ?
ENUM_EQUIPMENTTYPE_AVATAR_END <- 8 		  //  ? ??
ENUM_EQUIPMENTTYPE_AVATAR_SELL_END <- 8 		  //  ?  ? ??
ENUM_EQUIPMENTTYPE_AVATAR_MAX <- 9 		  //  ? ?
ENUM_EQUIPMENTTYPE_ITEM_START <- 10 		  //  ( )  ?
ENUM_EQUIPMENTTYPE_VISIBLE_END <- 11 		  //  ?  ??
ENUM_EQUIPMENTTYPE_CREATURE <- 22 		  //  ??
ENUM_EQUIPMENTTYPE_ARTIFACT_RED <- 23 		  //   ? ?
ENUM_EQUIPMENTTYPE_ARTIFACT_BLUE <- 24 		  //   ? ?
ENUM_EQUIPMENTTYPE_ARTIFACT_GREEN <- 25 		  //   ?? ?
ENUM_EQUIPMENTTYPE_ARTIFACT_END <- 26 
ENUM_EQUIPMENTTYPE_CREATURE_END <- 25 
ENUM_EQUIPMENTTYPE_CREATURE_MAX <- 24 
ENUM_EQUIPMENTTYPE_ARTIFACT <- 0 		  //   ??
ENUM_EQUIPMENTTYPE_TOTAL_MAX <- 24 
ENUM_EQUIPMENTTYPE_VISIBLE_MAX <- 13 		  //  ?  ?
ENUM_EQUIPMENTTYPE_ARMOR_START <- 12 
ENUM_EQUIPMENTTYPE_ARMOR_END <- 21 
ENUM_EQUIPMENTTYPE_ARMOR_NUM <- 10 
ENUM_EQUIPMENTTYPE_EXPAND_EQUIPSLOT_REVISE <- 10 		  //  ? ?? ?? ? ??

SKILL_BACK_STEP <- 169 		  //  ?
SKILL_CANCEL_BACK_STEP <- 170 		  //   ?
SKILL_CANCEL_THROW_ITEM <- 171 		  //    
SKILL_ARMOR_MASTERY_LIGHT <- 172 		  //  ?? ?
SKILL_ARMOR_MASTERY_HEAVY <- 173 		  //   ?
SKILL_BASIC_ATTACK_UP <- 174 		  //  
SKILL_JUMP_POWER_UP <- 175 		  //  ?
SKILL_MAGICAL_ATTACK_UP <- 176 		  //  ??
SKILL_THROW_MASTERY <- 177 		  //   ?
SKILL_PHYSICAL_BACK_ATTACK_CRITICAL <- 178 		  //  ? ?? ?
SKILL_DISJOINT_ITEM <- 179 		  //   
SKILL_SUPER_ARMOR_ON_CAST <- 180 		  //  ?? ?
SKILL_COMPOUND_CRAFT <- 181 		  //  ?:?
SKILL_COMPOUND_WEAVING <- 182 		  //  ?:?
SKILL_COMPOUND_MACHINE <- 183 		  //  ?:
SKILL_COMPOUND_CHEMISTRY <- 184 		  //  ?:
SKILL_ARMOR_MASTERY_LEATHER <- 185 		  //  ? ? ?
SKILL_PHYSICAL_CRITICAL_HIT_UP <- 186 		  //  ?  
SKILL_ARMOR_MASTERY_CLOTH <- 187 		  //  ? ?
SKILL_MAGICAL_CRITICAL_HIT_UP <- 188 		  //  ?  
SKILL_MAGICAL_BACK_ATTACK_CRITICAL <- 189 		  //  ? ?? ?
SKILL_QUICK_STANDING <- 190 		  //  ?? ??
SKILL_BASIC_HP_MAX_UP <- 195 		  //    ?  - 
SKILL_ARMOR_MASTERY_PLATE <- 196 		  //   ?
SKILL_GUILD_STATUS_UP <- 200 		  //  
SKILL_FEATURE_STAT_PHYSICAL_ATTACK_UP <- 210 		  //  ?? 
SKILL_FEATURE_STAT_PHYSICAL_DEFENCE_UP <- 211 		  //   
SKILL_FEATURE_STAT_MAGICAL_ATTACK_UP <- 212 		  //  ? 
SKILL_FEATURE_STAT_MAGICAL_DEFENCE_UP <- 213 		  //  ? 
SKILL_FEATURE_STAT_STUCK_UP <- 214 		  //  ?? 
SKILL_FEATURE_STAT_ACTIVEPROPERTY_STUCK_UP <- 215 		  //  ?? 
SKILL_FEATURE_STAT_HP_REGEN_RATE_UP <- 216 		  //  HP ? 
SKILL_FEATURE_STAT_MP_REGEN_RATE_UP <- 217 		  //  MP ? 
SKILL_FEATURE_STAT_ELEMENT_ATTACK_ALL_UP <- 218 		  // 	 
SKILL_FEATURE_STAT_ELEMENT_TOLERANCE_ALL_UP <- 219 		  //   ?
SKILL_MAX <- 220 
SKILL_FEATURE_STAT_START <- 210 
SKILL_FEATURE_STAT_MAX <- 10 		  // ?  ?


ACTIVESTATUS_SLOW <- 0 		  //  ??
ACTIVESTATUS_FREEZE <- 1 		  //  
ACTIVESTATUS_POISON <- 2 		  //  
ACTIVESTATUS_STUN <- 3 		  //  ?
ACTIVESTATUS_CURSE <- 4 		  //  
ACTIVESTATUS_BLIND <- 5 		  //  ?ε?
ACTIVESTATUS_LIGHTNING <- 6 		  //  ?
ACTIVESTATUS_STONE <- 7 		  //  ?
ACTIVESTATUS_SLEEP <- 8 		  //  ?
ACTIVESTATUS_BURN <- 9 		  //  
ACTIVESTATUS_WEAPON_BREAK <- 10 		  //  ? 
ACTIVESTATUS_BLEEDING <- 11 		  //  ??
ACTIVESTATUS_HASTE <- 12 		  //  
ACTIVESTATUS_BLESS <- 13 		  //  ??
ACTIVESTATUS_ELEMENT <- 14 		  //  ?
ACTIVESTATUS_CONFUSE <- 15 		  //  
ACTIVESTATUS_HOLD <- 16 		  //  
ACTIVESTATUS_ARMOR_BREAK <- 17 		  //  ? 
ACTIVESTATUS_MAX <- 18 


GROW_TYPE_PRIEST <- 0		/// ?
GROW_TYPE_CRUSADER <- 1		/// 
GROW_TYPE_INFIGHTER <- 2	/// ??
GROW_TYPE_EXORCIST <- 3		/// ?
GROW_TYPE_AVENGER <- 4		/// ?


ENUM_CHARACTERJOB_SWORDMAN <- 0     /// 
ENUM_CHARACTERJOB_FIGHTER <- 1      /// 
ENUM_CHARACTERJOB_GUNNER <- 2       /// 
ENUM_CHARACTERJOB_MAGE <- 3			/// 
ENUM_CHARACTERJOB_PRIEST <- 4		/// ?
ENUM_CHARACTERJOB_AT_GUNNER <- 5	/// ? 
ENUM_CHARACTERJOB_THIEF <- 6		/// ?
ENUM_CHARACTERJOB_AT_FIGHTER <- 7	/// ? 
ENUM_CHARACTERJOB_AT_MAGE <- 8		/// ? 
ENUM_CHARACTERJOB_DEMONIC_SWORDMAN <- 9	/// ??
ENUM_CHARACTERJOB_AT_PRIEST <- 9
ENUM_CHARACTERJOB_CREATOR_MAGE <- 10
ENUM_CHARACTERJOB_AT_SWORDMAN <- 10/// 
ENUM_CHARACTERJOB_MAX <- 11	/// 


ENUM_IS_REVERSE <- 0
ENUM_IS_START <- 1
ENUM_IS_PAUSE <- 2
ENUM_IS_END <- 3
ENUM_IS_INTERPOLATE_ATTACKBOX <- 4
ENUM_NEVER_APPLY_ANOTHER_PLAYERS_EFFECT_ALPHA_RATE <- 5
ENUM_IS_APPLY_ANOTHER_PLAYERS_EFFECT_ALPHA_RATE <- 6
ENUM_ANIMATION_BOOL_MAX <- 7


MODULE_TYPE_NONE <- -1
MODULE_TYPE_ENTRANCE <- 0
MODULE_TYPE_ROOM_LIST <- 1	// ?
MODULE_TYPE_SELECT_DUNGEON <- 2				// ? ?
MODULE_TYPE_MAIN_GAME <- 3					// ( ?)
MODULE_TYPE_PVP <- 4						// ?
MODULE_TYPE_FAIR_PVP <- 5					// ?
//MODULE_TYPE_LABYRINTH <- 7				// ??
MODULE_TYPE_SELECT_CHANNEL <- 6             
MODULE_TYPE_WARROOM <- 7					// ??
//MODULE_TYPE_CHAOS <- 8					
MODULE_TYPE_LOGIN <- 8
MODULE_TYPE_ASSAULT <- 9					// ??
MODULE_TYPE_DEAD_TOWER <- 10					// 
MODULE_TYPE_BLOOD_SYSTEM <- 11				//  ?
MODULE_TYPE_DESPAIR_TOWER <- 12			//?

//  
MODULE_TYPE_BOSS_TOWER <- 13			//?? 
MODULE_TYPE_ADVANCE_ALTAR <- 14			// ?

MODULE_TYPE_LOAD <- 15
MODULE_TYPE_TOURNAMENT <- 16
MODULE_TYPE_MAX <- 17
MODULE_TYPE_PVP_TYPE <- 18			// , ??, ? ? 
MODULE_TYPE_DUNGEON_TYPE <- 19		// ?, ,  ? 
MODULE_TYPE_ALL <- 20			

//MODULE_TYPE_LOAD <- 13
//MODULE_TYPE_TOURNAMENT <- 14
//MODULE_TYPE_MAX <- 15
//MODULE_TYPE_PVP_TYPE <- 16			// , ??, ? ? 
//MODULE_TYPE_DUNGEON_TYPE <- 17		// ?, ,  ? 
//MODULE_TYPE_ALL <- 18				// ??


ATTACKTYPE_PHYSICAL <- 0		/// ? ? ?
ATTACKTYPE_MAGICAL  <- 1       /// ? ? ?  
ATTACKTYPE_ABSOLUTE <- 2      /// ? ?
ATTACKTYPE_LIGHT	<- 3
ATTACKTYPE_DARK		<- 4
ATTACKTYPE_WATER	<- 5
ATTACKTYPE_FIRE		<- 6
ATTACKTYPE_MAX		<- 7

BUFF_CAUSE_NORMAL <- 0//  ?? 
BUFF_CAUSE_ACTIVE_STATUS <- 1// ?
BUFF_CAUSE_SKILL <- 2		// 
BUFF_CAUSE_EXCEPTIONAL <- 3	//  ?(? ? ?  ? ??)
BUFF_NONE <- 4				// ?? ? ?
BUFF_CAUSE_MAX <- 5



PAUSETYPE_NONE		<- 0	/// ? ?
PAUSETYPE_OBJECT	<- 1	///  ? (Appendage, ? , ? ??,  )
PAUSETYPE_WORLD		<- 2	/// ?? ? ? (Appendage, ? , ? ?)

ENUM_ELEMENT_FIRE	<- 0	/// ?
ENUM_ELEMENT_WATER	<- 1	/// ??
ENUM_ELEMENT_DARK	<- 2	/// ??
ENUM_ELEMENT_LIGHT	<- 3	/// ??
ENUM_ELEMENT_NONE	<- 4	/// ??
ENUM_ELEMENT_MAX	<- 4	/// == ENUM_ELEMENT_NONE


//   ??
THROW_TYPE_SKILL	<- 0	/// 
THROW_TYPE_ITEM		<- 1	///  
SETUP_TYPE_ITEM		<- 2	///  

SPEED_TYPE_CONST						<- 0	/// ?? ? setStaticSpeedInfo?? ?? ?? ? 
SPEED_TYPE_MOVE_SPEED					<- 1	///  
SPEED_TYPE_ATTACK_SPEED					<- 2	/// ? 
SPEED_TYPE_EXCEPT_WEAPON_ATTACK_SPEED	<- 3	/// ? ? ? 
SPEED_TYPE_CAST_SPEED					<- 4	/// ? 

Z_ACCEL_TYPE_CONST				<- 0	///  
Z_ACCEL_TYPE_GRAVITY_WORLD		<- 1	///  :  ? 
Z_ACCEL_TYPE_GRAVITY_OBJECT		<- 2	///  :  
Z_ACCEL_TYPE_ANTIGRAVITY_OBJECT	<- 3	/// ?? : ? ?.  

STATICINFO_DEPTH				<- 4	/// Static Info??  ? ?. (?? -> ? ->  ? -> ,  ?)
X_NORMALMOVE_VELOCITY			<- 143	/// ? ?? ?? 1??   ??
X_SLANTMOVE_VELOCITY			<- 119	/// ? ?? ?? 1??   ??
Y_NORMALMOVE_VELOCITY			<- 114	/// ? ?? ?? 1??   ??
Y_SLANTMOVE_VELOCITY			<- 95	/// ? ?? ?? 1??   ??
FORCE_TO_VELOCITY_CONST			<- 4000	/// ? ? ?? ?ϴ?  = * ?? / ?
SPEED_VALUE_DEFAULT				<- 1000	///  , ? ? ?? . ?? ?? 100%??.
LIGHT_OBJECT_MAX_WEIGHT			<- 60000	///    ??
MIDDLE_OBJECT_MAX_WEIGHT		<- 100000	///    ??
DEFAULT_GRAVITY_ACCEL			<- -1500	/// ??  ??


OBJECT_MESSAGE_INVINCIBLE		<- 0
OBJECT_MESSAGE_GHOST			<- 1
OBJECT_MESSAGE_SUPERARMOR		<- 2
OBJECT_MESSAGE_UNBREAKABLE		<- 3
OBJECT_MESSAGE_END				<- 4

RECOVER_TYPE_HP					<- 0
RECOVER_TYPE_MP					<- 1
RECOVER_TYPE_HP_MP				<- 2
RECOVER_TYPE_MAX				<- 3

REASON_NONE						<- 0
REASON_DEATH					<- 1
REASON_MOVING_VILLAGE			<- 2
REASON_LOGIN					<- 3
REASON_ALL						<- 4

OPTION_HOTKEY_MOVE_UP 	<- 0
OPTION_HOTKEY_MOVE_DOWN <- 2
OPTION_HOTKEY_MOVE_LEFT <- 1
OPTION_HOTKEY_MOVE_RIGHT <- 3
ENUM_SUBKEY_TYPE_ALL <- 7


GROW_TYPE_AT_MAGE			<- 0	//  
GROW_TYPE_ELEMENTAL_BOMBER	<- 1	//  ? 
GROW_TYPE_GRACIAL_MASTER	<- 2	//  ??

PARTICLE_CREATER_LARGE_HIT			<- 0
PARTICLE_CREATER_SMALL_HIT			<- 1
PARTICLE_CREATER_FIRE_HIT			<- 2
PARTICLE_CREATER_FIRE_HIT_LIGHT		<- 3
PARTICLE_CREATER_WATER_HIT			<- 4
PARTICLE_CREATER_WATER_HIT_LIGHT	<- 5
PARTICLE_CREATER_WATER_HIT_ICE		<- 6

OPTION_HOTKEY__UNDEFINED <- -1 		  //  ? ?
OPTION_HOTKEY_MOVE_UP <- 0 		  //  (Up arrow)
OPTION_HOTKEY_MOVE_LEFT <- 1 		  //  (Left arrow)
OPTION_HOTKEY_MOVE_DOWN <- 2 		  //  (Down arrow)
OPTION_HOTKEY_MOVE_RIGHT <- 3 		  //  (Right arrow)
OPTION_HOTKEY_ATTACK <- 4 		  //  (X)
OPTION_HOTKEY_JUMP <- 5 		  //  (C)
OPTION_HOTKEY_SKILL <- 6 		  //  (Z)
OPTION_HOTKEY_SKILL2 <- 7 		  //  buff?? ?(space)
OPTION_HOTKEY_CREATURE_SKILL <- 8 		  //  (V)
OPTION_HOTKEY_STATUS_WINDOW <- 9 		  //  (M)
OPTION_HOTKEY_SKILL_WINDOW <- 10 		  //  (K)
OPTION_HOTKEY_ITEM_INVENTORY <- 11 		  //  (I)
OPTION_HOTKEY_OPTION_WINDOW <- 12 		  //  (O)
OPTION_HOTKEY_NORMAL_QUEST_WINDOW <- 13 		  //  (Q)
OPTION_HOTKEY_AVATAR_INVENTORY <- 14 		  //  (U)
OPTION_HOTKEY_CERASHOP <- 15 		  //  (T)
OPTION_HOTKEY_MINIMAP <- 16 		  // ? ?(N)
OPTION_HOTKEY_CREATURE_WINDOW <- 17 		  //  (Y)
OPTION_HOTKEY_TOOLTIP_ <- 18 		  //  ?(R)
OPTION_HOTKEY_EPIC_QUEST_WINDOW <- 19 		  //  (W)
OPTION_HOTKEY_QUICK_SKILL1 <- 20 		  //   ?(A, S, D, F, G, H)
OPTION_HOTKEY_QUICK_SKILL2 <- 21 
OPTION_HOTKEY_QUICK_SKILL3 <- 22 
OPTION_HOTKEY_QUICK_SKILL4 <- 23 
OPTION_HOTKEY_QUICK_SKILL5 <- 24 
OPTION_HOTKEY_QUICK_SKILL6 <- 25 
OPTION_HOTKEY_EXSKILL1 <- 26 		  //  ? ?(F1 - F6)
OPTION_HOTKEY_EXSKILL2 <- 27 
OPTION_HOTKEY_EXSKILL3 <- 28 
OPTION_HOTKEY_EXSKILL4 <- 29 
OPTION_HOTKEY_EXSKILL5 <- 30 
OPTION_HOTKEY_EXSKILL6 <- 31 
OPTION_HOTKEY_ITEM_QUICKSLOT1 <- 32 		  //   ?? ?(1 - 6)
OPTION_HOTKEY_ITEM_QUICKSLOT2 <- 33 
OPTION_HOTKEY_ITEM_QUICKSLOT3 <- 34 
OPTION_HOTKEY_ITEM_QUICKSLOT4 <- 35 
OPTION_HOTKEY_ITEM_QUICKSLOT5 <- 36 
OPTION_HOTKEY_ITEM_QUICKSLOT6 <- 37 
OPTION_HOTKEY_TOGGLE_ITEM_NAME_IN_DUNGEON <- 38 		  //  ??  ?(ctrl)
OPTION_HOTKEY_HIDE_MAIN_HUD <- 39 		  //   ??Tab)
OPTION_HOTKEY_TOGGLE_TITLE_ANIMATION <- 40 		  //  ?? ? (E)
OPTION_HOTKEY_TOGGLE_SKILL_INFORMATION <- 41 		  //   ? ? (F7)
OPTION_HOTKEY_PAUSE_IN_TOWER <- 42 		  //   ?
OPTION_HOTKEY_CAPTURE_MOVING_PICTURE <- 43 		  //   (Pause)
OPTION_HOTKEY_MENU_MY_INFO <- 44 		  //  ?? (7)
OPTION_HOTKEY_MENU_COMMUNITY <- 45 		  //  ?? (8)
OPTION_HOTKEY_MENU_CONTENTS <- 46 		  //   (9)
OPTION_HOTKEY_MENU_SERVICE <- 47 		  //  ? (0)
OPTION_HOTKEY_MENU_SYSTEM__CLOSE_ALL_WINDOW <- 48 		  // ??ݱ?Esc)
OPTION_HOTKEY_PVP <- 49 		  //  (P)
OPTION_HOTKEY_RECOMMEND_USER <- 50 		  //  ?([)
OPTION_HOTKEY_PARTY_MATCHING <- 51 		  //  (])
OPTION_HOTKEY_FRIEND <- 52 		  //  (L)
OPTION_HOTKEY_GUILD <- 53 		  //  ;)
OPTION_HOTKEY_MEMBER <- 54 		  //  ')
OPTION_HOTKEY_BLACKLIST <- 55 		  //  ?
OPTION_HOTKEY_PVP_BUDDY <- 56 		  //  ?
OPTION_HOTKEY_WAR_AREA_LIST <- 57 		  //  ,)
OPTION_HOTKEY_AUCTION_WINDOW <- 58 		  //  ??B)
OPTION_HOTKEY_GOBLIN_PAD <- 59 		  //  ?
OPTION_HOTKEY_HOTKEY_SETTING_WINDOW <- 60 		  //  ?? ??
OPTION_HOTKEY_WAR_AREA_INFORMATION <- 61 		  //  ?? ??(End)
OPTION_HOTKEY_HELLMODE_INFORMATION <- 62 		  //  ??   ?
OPTION_HOTKEY_FAVOR_CHECK_WINDOW <- 63 		  //  ??   ?
OPTION_HOTKEY_EXPERT_JOB <- 64 		  //  ?? 
OPTION_HOTKEY_EMOTION_EXPRESSION <- 65 		  //  ? 
OPTION_HOTKEY_EVENT <- 66 		  //  ??(shift)
OPTION_HOTKEY_PVP_MSSION <- 67 		  //  
OPTION_HOTKEY_PVP_RECORD <- 68 		  //  
OPTION_HOTKEY_QUICK_CHAT_0 <- 69 
OPTION_HOTKEY_QUICK_CHAT_1 <- 70 
OPTION_HOTKEY_QUICK_CHAT_2 <- 71 
OPTION_HOTKEY_QUICK_CHAT_3 <- 72 
OPTION_HOTKEY_QUICK_CHAT_4 <- 73 
OPTION_HOTKEY_QUICK_CHAT_5 <- 74 
OPTION_HOTKEY_QUICK_CHAT_6 <- 75 
OPTION_HOTKEY_QUICK_CHAT_7 <- 76 
OPTION_HOTKEY_QUICK_CHAT_8 <- 77 
OPTION_HOTKEY_QUICK_CHAT_9 <- 78 
OPTION_HOTKEY_TOGGLE_ITEMINFO_COMPARE <- 79 		  //    ? (Default: F8)
OPTION_HOTKEY_TITLEBOOK <- 80 
OPTION_HOTKEY_THIS_DUNGEON <- 81 
OPTION_HOTKEY_ANOTHER_DUNGEON <- 82 
OPTION_HOTKEY_RETURN_TO_TOWN <- 83 
OPTION_HOTKEY_MERCENARY_SYSTEM <- 84 
OPTION_HOTKEY_ITEM_DICTIONARY <- 85 
OPTION_HOTKEY_QUICK_PARTY_REGISTER <- 86 


STATE_BURSTER				<- 114
SKILL_BURSTER				<- 114

ture <- true
True <- true
False <- false

GLOBAL_CURRENT_DUNGEON_ID <- -1
GLOBAL_CURRENT_MAP_ID <- -1
GLOBAL_CURRENT_DUNGEON_FLAG <- 0
GLOBAL_DAMAGE_FONT_NUMBER_GRBA_ALPHA <- 255
GLOBAL_IS_LOCK_SHAKE_EFFECT <- 0
FLAG_ENEMY <- 0


CHECK_VAR <- 1
DUMMY_CHAR_THE_FRIST_ANIMATION <- null
DUMMY_DAMAGER_OBJ <- null

DUMMY_GOLBAL_ATTACK_TARGET <- null

getroottable()["GlobalCenterUIFlagEffect"] <- {};
getroottable()["GlobalCenterUIFlagEffect"] = [0,0,0,0,0,0];

//5

SET_FRIST_ANIMATION_FLAG <- 0
SET_FRIST_ANIMATION_MONSTER_FLAG <- 1

// global content
GLOBAL_DAMAGE_FONT_ID <- 0
//

//mouse Parameter

//ui1
GLOBAL_MOUSE_OFFSET_X_UI1 <- 0
GLOBAL_MOUSE_OFFSET_Y_UI1 <- 0
GLOBAL_IS_JUDGE_MOUSE_POS_UI1 <- 0

GLOBAL_MOUSE_OFFSET_X_UI2 <- 0
GLOBAL_MOUSE_OFFSET_Y_UI2 <- 0
GLOBAL_IS_JUDGE_MOUSE_POS_UI2 <- 0

GLOBAL_MOUSE_OFFSET_X_UI3 <- 0
GLOBAL_MOUSE_OFFSET_Y_UI3 <- 0
GLOBAL_IS_JUDGE_MOUSE_POS_UI3 <- 0

//ui1 end
getroottable()["GlobalMonsterDieSoundList"] <- {};
getroottable()["GlobalMonsterFlashScreenList"] <- {};
getroottable()["GlobalMonsterPlayAnimationList"] <- {};
getroottable()["GlobalMonsterPlaySoundList"] <- {};
getroottable()["GlobalMonsterFristReadAniList"] <- {};
getroottable()["GlobalMonsterCreateCirclePassiveobjectList"] <- {};
getroottable()["GlobalMonsterStringList"] <- {};
getroottable()["GlobalMonsterStringCastingEXList"] <- {};

getroottable()["GlobalDungeonFristReadAniList"] <- {};
getroottable()["GlobalSkillFristReadAniList"] <- {};

//
