
//////////////////////////////////////////////////////
STATE_PRAYOFRORACLE <- 107
STATE_CURE <- 233
STATE_BLESS_OF_COURAGE <- 133
STATE_SPEAR_OF_VICTORY <- 120
STATE_PROTECTION_OF_URIEL <- 104
STATE_MIRACLE_CHINE <- 106
STATE_BRIONAC <- 230
STATE_HANDAWAKENTOSIN  <- 116
STATE_DEPRAVITYSEVENSINS  <- 121
STATE_DUALSLASH  <- 122
STATE_GUILLOTINE  <- 123
STATE_ROLLINGRUSH  <- 124
STATE_LUSTHAND  <- 125
STATE_PRIDEACCEL  <- 126
STATE_SLOTHBODY  <- 127
STATE_GREEDTHELURKER  <- 128
STATE_SCYTHEMSSACRE  <- 129
STATE_SCUDTHEWRATH  <- 130
STATE_THIRDRIB  <- 131
STATE_SECONDSOUL  <- 132
STATE_FLOWEROFPURIFICATION  <- 134
STATE_LASTGENESIS  <- 136
STATE_ENVIOUSKISS  <- 137
STATE_GLUTTONYVOMIT  <- 138
STATE_THESEVENDEADLYSINS  <- 139
STATE_BLESS_OF_PROTECTION <- 140
STATE_LIGHT_OF_HAPTISM <- 141
STATE_HOLY_LIGHT <- 142
STATE_ARIA_OF_COURAGE <- 143
STATE_SAINT_FLASH <- 144
STATE_HOLY_CIRCLET <- 145
STATE_EDIFICATION <- 146
STATE_THUNDER_OF_CLEANS <- 147
STATE_REVIVE <- 148
STATE_GRAND_CROSS_CRASH <- 101
STATE_ARIA_OF_REGENERATION <- 150
STATE_CRUX_OF_VICTORIA <- 151
STATE_REPENTENCE_SMASH <- 153
STATE_BLESS_OF_ANGEL <- 154
STATE_SHINE_CROSS <- 155
STATE_BURSTER <- 198
STATE_RISING_SLASH <- 220
STATE_VIOLENT_ASSAULT <- 221
STATE_PRAYER_OF_HEAL <- 222
STATE_WEAPON_GUARD <- 223
STATE_HOLY_SMASH <- 225
STATE_HEAVY_SIN <- 226
STATE_NECK_UP_SCYTHE <- 227
STATE_TALISMAN_OF_LIGHTNING <- 228
STATE_CUT_IN_DASH <- 229
STATE_CROSS_OF_PUNISHMENT <- 231
STATE_HOLY_FLASH <- 232
STATE_ROSARYSHOOTING <- 234
STATE_ROSARYSTRIKE <- 235
STATE_CONTRACTSPACEBYMAGIC <- 236
STATE_TALISMANOFOPPRESSION <- 237
STATE_EXORCISMUS <- 238
STATE_EFFORTSPHERE <- 239
STATE_TALISMANOFSOULSTEAL <- 240
STATE_DRAGONWRATH <- 241
STATE_ROSARYOF108BEADS <- 242
STATE_IMMOBILITYMAGICLINE <- 243
STATE_RITUALFORDRAGON <- 244
STATE_TALISMANOFTIMEBOMB <- 245
STATE_LIFEDEPRIVEDISPOSITION <- 246
STATE_ROSARYWILDSHOT <- 247
STATE_BIGROSARY <- 248
STATE_WRATHOFGODDRAGON <- 249

STATE_BURNATTHESTAKE <- 250	//ûýúý
STATE_DECOLLATION <- 210	//ú¼úý
STATE_ESSENCEOFPHLEGE <- 218	//ûýæûïñü¤
STATE_FANATICISM <- 217	//ÎÊæðãáäæ
STATE_FLAMEOFBAPTISM <- 216	//ãêæûá©ÖÉ
STATE_HOLYFLAME <- 215	//ãêæû
STATE_JUDGMENTBLOW <- 214	//ãû÷÷ñìÌª
STATE_PATROLBOMB <- 213	//ïäûùûýæû?
STATE_PUNISHMENTBLOW <- 212	//î®Ì½ñýÌª
STATE_SUMMARYTIRAL <- 211	//ãêæûóÖ
STATE_VIRTUOUSFURY <- 253	//ãêæûÒÁûý
STATE_VORTEXOFHELLFIRE <- 252	//ãêæûàÁè¾
STATE_WHEELOFPUNISHMENT <- 251	//ó³×Çúý
STATE_DISMEMBER <- 163
STATE_PURIFICATION <- 162
STATE_INFERNO <- 164

//========================================

SKILL_PRAYOFRORACLE <- 10
SKILL_MIKOMASTERY <- 9
SKILL_CINTAMANI <- 18
SKILL_POWEROFDRAGON <- 20
SKILL_ARMORMASTERYCLOTHSORCERESS <- 187
SKILL_GRACE_OF_DEVINE <- 77
SKILL_BLESS_OF_COURAGE <- 78
SKILL_ARIA <- 80
SKILL_CURE <- 33
SKILL_CRUSADE <- 82
SKILL_SPEAR_OF_VICTORY <- 83
SKILL_BLESS_OF_PROTECTION <- 140
SKILL_LIGHT_OF_HAPTISM <- 141
SKILL_HOLY_LIGHT <- 142
SKILL_ARIA_OF_COURAGE <- 143
SKILL_SAINT_FLASH <- 144
SKILL_HOLY_CIRCLET <- 145
SKILL_EDIFICATION <- 146
SKILL_THUNDER_OF_CLEANS <- 147
SKILL_REVIVE <- 148
SKILL_GRAND_CROSS_CRASH <- 149
SKILL_ARIA_OF_REGENERATION <- 150
SKILL_CRUX_OF_VICTORIA <- 151
SKILL_ZEAL_OF_FAITH <- 152
SKILL_REPENTENCE_SMASH <- 153
SKILL_BLESS_OF_ANGEL <- 154
SKILL_SHINE_CROSS <- 155
SKILL_BLESS_OF_RAPHAEL <- 100
SKILL_PROTECTION_OF_URIEL <- 104
SKILL_MIRACLE_CHINE <- 106
SKILL_BRIONAC <- 113
SKILL_HANDAWAKENTOSIN  <- 116
SKILL_SCYTHEMASTERY  <- 120
SKILL_DEPRAVITYSEVENSINS  <- 121
SKILL_DUALSLASH  <- 122
SKILL_GUILLOTINE  <- 123
SKILL_ROLLINGRUSH  <- 124
SKILL_LUSTHAND  <- 125
SKILL_PRIDEACCEL  <- 126
SKILL_SLOTHBODY  <- 127
SKILL_GREEDTHELURKER  <- 128
SKILL_SCYTHEMSSACRE  <- 129
SKILL_SCUDTHEWRATH  <- 130
SKILL_THIRDRIB  <- 131
SKILL_SECONDSOUL  <- 132
SKILL_BODYPRESSEDSIN  <- 133
SKILL_FLOWEROFPURIFICATION  <- 134
SKILL_FIRSTPRANA  <- 135
SKILL_LASTGENESIS  <- 136
SKILL_ENVIOUSKISS  <- 137
SKILL_GLUTTONYVOMIT  <- 138
SKILL_THESEVENDEADLYSINS  <- 139
SKILL_RISING_SLASH <- 220
SKILL_VIOLENT_ASSAULT <- 221
SKILL_PRAYER_OF_HEAL <- 222
SKILL_WEAPON_GUARD <- 223
SKILL_FLAGELLANTS <- 43
SKILL_HOLY_SMASH <- 225
SKILL_HEAVY_SIN <- 226
SKILL_NECK_UP_SCYTHE <- 227
SKILL_TALISMAN_OF_LIGHTNING <- 228
SKILL_CUT_IN_DASH <- 229
SKILL_CROSS_MASTERY <- 230
SKILL_CROSS_OF_PUNISHMENT <- 231
SKILL_HOLY_FLASH <- 232
SKILL_SINSAYER <- 233
SKILL_ROSARYSHOOTING <- 234
SKILL_ROSARYSTRIKE <- 235
SKILL_CONTRACTSPACEBYMAGIC <- 236
SKILL_TALISMANOFOPPRESSION <- 237
SKILL_EXORCISMUS <- 238
SKILL_EFFORTSPHERE <- 239
SKILL_TALISMANOFSOULSTEAL <- 240
SKILL_DRAGONWRATH <- 241
SKILL_ROSARYOF108BEADS <- 242
SKILL_IMMOBILITYMAGICLINE <- 243
SKILL_RITUALFORDRAGON <- 244
SKILL_TALISMANOFTIMEBOMB <- 245
SKILL_LIFEDEPRIVEDISPOSITION <- 246
SKILL_ROSARYWILDSHOT <- 247
SKILL_BIGROSARY <- 248
SKILL_WRATHOFGODDRAGON <- 249

SKILL_BATTLEAXEMASTERY <- 6	//îúÝ¨ïñ÷×
SKILL_BRANDOFHERESY <- 8	//ì¶Ó®Õ§ìÔ
SKILL_BURNATTHESTAKE <- 250	//ûýúý
SKILL_DECOLLATION <- 210	//ú¼úý
SKILL_ESSENCEOFPHLEGE <- 218	//ûýæûïñü¤
SKILL_FANATICISM <- 217	//ÎÊæðãáäæ
SKILL_FLAMEOFBAPTISM <- 216	//ãêæûá©ÖÉ
SKILL_HOLYFLAME <- 215	//ãêæû
SKILL_JUDGMENTBLOW <- 214	//ãû÷÷ñìÌª
SKILL_PATROLBOMB <- 213	//ïäûùûýæû?
SKILL_PUNISHMENTBLOW <- 212	//î®Ì½ñýÌª
SKILL_SUMMARYTIRAL <- 211	//ãêæûóÖ
SKILL_VIRTUOUSFURY <- 253	//ãêæûÒÁûý
SKILL_VORTEXOFHELLFIRE <- 252	//ãêæûàÁè¾
SKILL_WHEELOFPUNISHMENT <- 251	//ó³×Çúý
SKILL_WILLOFINQUISITOR <- 209	//ãû÷÷íºîÜî®Ì½
SKILL_POURESSENCE <- 62	
SKILL_DISMEMBER <- 163
SKILL_MALLEUSMALEFICARUM <- 73
SKILL_POURESSENCE <- 62
SKILL_PURIFICATION <- 162
SKILL_INFERNO <- 164

//////////////////////////////////////////////////////
CUSTOM_ANI_WEAPON_GUARD_STAND_BODY				<- 0
CUSTOM_ANI_RISING_SLASH_BODY					<- 1
CUSTOM_ANI_VIOLENT_ASSAULT_START_BODY			<- 2
CUSTOM_ANI_VIOLENT_ASSAULT_LOOP_BODY			<- 3
CUSTOM_ANI_VIOLENT_ASSAULT_END_BODY				<- 4
CUSTOM_ANI_PRAYER_OFHEAL_BODY					<- 5
CUSTOM_ANI_WEAPON_GUARD_ATTACKED_BODY			<- 6
CUSTOM_ANI_HOLY_SMASH_BODY						<- 7
CUSTOM_ANI_HEAVY_SIN_READY_BODY					<- 8
CUSTOM_ANI_HEAVY_SIN_ATTACK_BODY				<- 9
CUSTOM_ANI_NECKUPSCYTHE_ATTACK1_AWAKE_BODY		<- 10
CUSTOM_ANI_NECKUPSCYTHE_ATTACK1_BODY			<- 11
CUSTOM_ANI_NECKUPSCYTHE_ATTACK2_BODY			<- 12
CUSTOM_ANI_NECKUPSCYTHE_ATTACK2_FRONT_BODY		<- 13
CUSTOM_ANI_TALISMAN_OF_LIGHTNING_CAST_BODY		<- 14
CUSTOM_ANI_TALISMAN_OF_LIGHTNING_SHOT_BODY		<- 15
CUSTOM_ANI_AT_CUTIN_DASH_FRONT_DASH_BODY		<- 16
CUSTOM_ANI_AT_CUTIN_DASH_FRONT_REDASH_BODY		<- 17
CUSTOM_ANI_AT_CUTIN_DASH_BACK_DASH_BODY			<- 18
CUSTOM_ANI_AT_CUTIN_DASH_ATT_BODY				<- 19
CUSTOM_ANI_CROSS_OF_PUNISHMENT_A_BODY			<- 20
CUSTOM_ANI_CROSS_OF_PUNISHMENT_B_BODY			<- 21
CUSTOM_ANI_HOLY_FLASH_BODY						<- 22
CUSTOM_ANI_ATLIGHT_OF_HAPTISM_CASTING_BOD		<- 23
CUSTOM_ANI_ATLIGHT_OF_HAPTISM_SHOOT_BODY		<- 24
CUSTOM_ANI_SPEAR_OF_VICTORY_BODY_READY			<- 25
CUSTOM_ANI_SPEAR_OF_VICTORY_BODY_CHARGELOOP		<- 26
CUSTOM_ANI_SPEAR_OF_VICTORY_BODYSHOT_02			<- 27
CUSTOM_ANI_CRUSADE_ATTACK1_BODY					<- 28
CUSTOM_ANI_CRUSADE_ATTACK2_BODY					<- 29
CUSTOM_ANI_CRUSADE_ATTACK3_BODY					<- 30
CUSTOM_ANI_CRUSADE_JUMP_ATTACK_BODY				<- 31
CUSTOM_ANI_CRUSADE_DASH_ATTACK_BODY				<- 32
CUSTOM_ANI_CRUSADE_RISING_SLASH_BODY			<- 33
CUSTOM_ANI_SC_BODY_A							<- 34
CUSTOM_ANI_SC_BODY_B							<- 35
CUSTOM_ANI_SC_BODY_C							<- 36
CUSTOM_ANI_ATGRAND_CROSS_CRASH_READY_BODY		<- 37
CUSTOM_ANI_ATGRAND_CROSS_CRASH_SMASH_BODY		<- 38
CUSTOM_ANI_SAINTFLASH_CAST_BODY					<- 39
CUSTOM_ANI_SAINTFLASH_SHOOT_BODY				<- 40
CUSTOM_ANI_SAINT_WALL_READY_BODY				<- 41
CUSTOM_ANI_SAINT_WALL_ATTACK_BODY				<- 42
CUSTOM_ANI_HOLY_CIRCLET_A_BODY					<- 43
CUSTOM_ANI_HOLY_CIRCLET_B_BODY					<- 44
CUSTOM_ANI_ATTHUNDER_OF_CLEANS_CASTING_BODY		<- 45
CUSTOM_ANI_ATTHUNDER_OF_CLEANS_START_BODY		<- 46
CUSTOM_ANI_ARIA_OF_COURAGE_START_BODY			<- 47
CUSTOM_ANI_ARIA_OF_COURAGE_LOOP_BODY			<- 48
CUSTOM_ANI_ARIA_OF_COURAGE_END_BODY				<- 49
CUSTOM_ANI_COV_READY_BODY_BODY					<- 50
CUSTOM_ANI_COV_FLY_BODY_BODY					<- 51
CUSTOM_ANI_COV_SETUP_BODY_BODY					<- 52
CUSTOM_ANI_COV_BUFF_FINISH_BODY_BODY			<- 53
CUSTOM_ANI_COV_BATTLE_FINISH_BODY				<- 54
CUSTOM_ANI_ATREPENTENCE_SMASH_READY_BODY		<- 55
CUSTOM_ANI_ATREPENTENCE_SMASH_SMASH01_BODY		<- 56
CUSTOM_ANI_ATREPENTENCE_SMASH_SMASH02_BODY		<- 57
CUSTOM_ANI_ATREPENTENCE_SMASH_END_BODY			<- 58
CUSTOM_ANI_PROTECTION_OF_URIEL_CAST_BODY		<- 59
CUSTOM_ANI_BRIONAC_BODY_BODY					<- 60
CUSTOM_ANI_BRIONAC_ADD_BODY04					<- 61
CUSTOM_ANI_BRIONAC_NEW_BODY_BODY				<- 62
CUSTOM_ANI_CURE_CAST_BODY						<- 63
CUSTOM_ANI_CURE_START_BODY						<- 64
CUSTOM_ANI_BLESS_OF_PROTECTION_CAST_BODY		<- 65
CUSTOM_ANI_BLESS_OF_PROTECTION_START_BODY		<- 66
CUSTOM_ANI_BLESS_OF_COURAGE_CAST_BODY			<- 67
CUSTOM_ANI_BLESS_OF_COURAGE_START_BODY			<- 68
CUSTOM_ANI_EDIFICATION_CAST_BODY				<- 69
CUSTOM_ANI_EDIFICATION_START_BODY				<- 70
CUSTOM_ANI_REVIVE_CAST_BODY						<- 71
CUSTOM_ANI_REVIVE_THROW_BODY					<- 72
CUSTOM_ANI_ARIA_OF_REGENERATION_START_BODY		<- 73
CUSTOM_ANI_ARIA_OF_REGENERATION_LOOP_BODY		<- 74
CUSTOM_ANI_ARIA_OF_REGENERATION_END_BODY		<- 75
CUSTOM_ANI_BLESS_OF_ANGEL_PHASE1_BODY			<- 76
CUSTOM_ANI_HOLY_LIGHT_CAST_BODY					<- 77
CUSTOM_ANI_HOLY_LIGHT_START_BODY				<- 78

CUSTOM_ANI_CRUX_OF_SHAPIEL_READY_BODY				<- 79
CUSTOM_ANI_LAUS_DE_ANGELUS_START_BODY_BODY				<- 80
CUSTOM_ANI_LAUS_DE_ANGELUS_FALLING_BODY_BODY				<- 81
CUSTOM_ANI_LAUS_DE_ANGELUS_SONG_D_BODY_BODY				<- 82
CUSTOM_ANI_LAUS_DE_ANGELUS_END_BODY_BODY				<- 83
CUSTOM_ANI_LAUS_DE_ANGELUS_PARTY_BODY				<- 84
//////////////////////////////////////////////////////
CUSTOM_ATTACK_RISING_SLASH						<- 0
CUSTOM_ATTACK_VIOLENT_ASSAULT					<- 1
CUSTOM_ATTACK_HOLY_SMASH						<- 2
CUSTOM_ATTACK_NECK_UP_SCYTHE_POKE				<- 3
CUSTOM_ATTACK_NECK_UP_SCYTHE_BACK_THROW			<- 4
CUSTOM_ATTACK_NECK_UP_SCYTHE_FRONT_THROW		<- 5
CUSTOM_ATTACK_CUT_IN_DASH_ATTACK				<- 6
CUSTOM_ATTACK_CROSS_OF_PUNISHMENT_A				<- 7
CUSTOM_ATTACK_CROSS_OF_PUNISHMENT_B				<- 8
CUSTOM_ATTACK_CRUSADE_ATTACK1					<- 9
CUSTOM_ATTACK_CRUSADE_ATTACK2					<- 10
CUSTOM_ATTACK_CRUSADE_ATTACK3					<- 11
CUSTOM_ATTACK_CRUSADE_JUMP_ATTACK				<- 12
CUSTOM_ATTACK_CRUSADE_DASH_ATTACK				<- 13
CUSTOM_ATTACK_SHINECROSSATK1					<- 14
CUSTOM_ATTACK_SHINECROSSATK2					<- 15
CUSTOM_ATTACK_SHINECROSSATK3					<- 16
CUSTOM_ATTACK_GRANDCROSSCRASHATTACK				<- 17
CUSTOM_ATTACK_SAINT_WALL_CAST					<- 18
CUSTOM_ATTACK_ARIA_OF_COURAGE_ATTACK			<- 19
CUSTOM_ATTACK_CRUX_OF_VICTORIA_MULTI_HIT		<- 20
CUSTOM_ATTACK_CRUX_OF_VICTORIA_FINISH			<- 21
CUSTOM_ATTACK_REPENTENCE_SMASHATK1				<- 22
CUSTOM_ATTACK_REPENTENCE_SMASHATK2				<- 23
//////////////////////////////////////////////////////
INTELLIGENCE_VALUE <- 0
//////////////////////////////////////////////////////

CUSTOM_ANI_DEPRAVITYSEVENSINS_CHANGEON_BODY <- 86
CUSTOM_ANI_DEMONIZATION_STAY <- 87
CUSTOM_ANI_DEMONIZATION_SIT <- 88
CUSTOM_ANI_DEMONIZATION_MOVE <- 89
CUSTOM_ANI_DEMONIZATION_DASH <- 90
CUSTOM_ANI_DEMONIZATION_JUMP <- 91
CUSTOM_ANI_DEMONIZATION_DOWN <- 92
CUSTOM_ANI_DEMONIZATION_DAMAGE1 <- 93
CUSTOM_ANI_DEMONIZATION_DAMAGE2 <- 94
CUSTOM_ANI_DEMONIZATIONATTACK_BASIC_A_BODY <- 95
CUSTOM_ANI_DEMONIZATIONATTACK_BASIC_B_BODY <- 96
CUSTOM_ANI_DEMONIZATIONATTACK_BASIC_C_BODY <- 97
CUSTOM_ANI_DEMONIZATIONATTACK_DASH_BODY <- 98
CUSTOM_ANI_DEMONIZATIONATTACK_JUMP_BODY <- 99
CUSTOM_ANI_DEMONIZATION_THROW1 <- 100
CUSTOM_ANI_DEMONIZATION_THROW2 <- 101
CUSTOM_ANI_DEMONIZATION_BUFF <- 102
CUSTOM_ANI_MISTRESS_ATTACK1 <- 103
CUSTOM_ANI_MISTRESS_ATTACK2 <- 104
CUSTOM_ANI_MISTRESS_ATTACK3 <- 105
CUSTOM_ANI_MISTRESS_DASHATTACK <- 106
CUSTOM_ANI_MISTRESS_JUMPATTACK <- 107
CUSTOM_ANI_DUALSLASH_BODY <- 108
CUSTOM_ANI_DUALSLASH_DEMONIZATION <- 109
CUSTOM_ANI_GUILLOTINE_READY_DEMONIZATION <- 110
CUSTOM_ANI_GUILLOTINE_GRAB_DEMONIZATION <- 111
CUSTOM_ANI_GUILLOTINE_SMASH_DEMONIZATION <- 112
CUSTOM_ANI_GUILLOTINE_READY_BODY <- 113
CUSTOM_ANI_GUILLOTINE_GRAB <- 278
CUSTOM_ANI_GUILLOTINE_SMASH <- 115
CUSTOM_ANI_ATROLLINGRUSH_READY_BODY <- 116
CUSTOM_ANI_ATROLLINGRUSH_HIT_01_BODY <- 117
CUSTOM_ANI_ATROLLINGRUSH_HIT_02_BODY <- 118
CUSTOM_ANI_ATROLLINGRUSH_LANDING_BODY <- 119
CUSTOM_ANI_ATROLLINGRUSH_FINISH_BODY <- 120
CUSTOM_ANI_ATROLLINGRUSH_D_READY_BODY <- 121
CUSTOM_ANI_ATROLLINGRUSH_D_HIT_01_BODY <- 122
CUSTOM_ANI_ATROLLINGRUSH_D_HIT_02_BODY <- 123
CUSTOM_ANI_ATROLLINGRUSH_D_LANDING_BODY <- 124
CUSTOM_ANI_ATROLLINGRUSH_D_FINISH_BODY <- 125
CUSTOM_ANI_ATROLLINGRUSH_SPIN_END_BODY <- 126
CUSTOM_ANI_ATROLLINGRUSH_D_SPIN_END_BODY <- 127
CUSTOM_ANI_LUSTHANDATK01_DEMON <- 128
CUSTOM_ANI_LUSTHANDATK03EFFA_DEMON <- 129
CUSTOM_ANI_LUSTHANDATK01_BODY <- 130
CUSTOM_ANI_LUSTHANDEND_BODY <- 131
CUSTOM_ANI_LUSTHANDATK02_BODY <- 132
CUSTOM_ANI_LUSTHANDATK03BODY_BODY <- 133
CUSTOM_ANI_PRIDEACCEL_START_BOBY <- 134
CUSTOM_ANI_PRIDEACCELMOVE01_BOBY <- 135
CUSTOM_ANI_PRIDEACCELMOVE01_AIR_BOBY <- 136
CUSTOM_ANI_PRIDEACCELMOVE02_BOBY <- 137
CUSTOM_ANI_PRIDEACCEL_END_BOBY <- 138
CUSTOM_ANI_SLOTHBODYSTEP1_BODY <- 139
CUSTOM_ANI_SLOTHBODYFINISH_BODY <- 140
CUSTOM_ANI_GREEDREADY_BODY <- 141
CUSTOM_ANI_GREEDREADYDEMON_BODY <- 142
CUSTOM_ANI_ATSCYTHEMSSACRE_STEP1_BODY <- 143
CUSTOM_ANI_ATSCYTHEMSSACRE_LOOP_BODY <- 144
CUSTOM_ANI_ATSCYTHEMSSACRE_STEP2_BODY <- 145
CUSTOM_ANI_ATSCYTHEMSSACRE_DEMONSTEP1_BODY <- 146
CUSTOM_ANI_ATSCYTHEMSSACRE_DEMONLOOP_BODY <- 147
CUSTOM_ANI_ATSCYTHEMSSACRE_DEMONSTEP2_BODY <- 148
CUSTOM_ANI_ATSLOTHBODYLV95ATORIGINALSINATTACKBODY_LAST <- 149
CUSTOM_ANI_ATSCUDTHEWRATH_TRANSFORM_BODY <- 150
CUSTOM_ANI_ATSCUDTHEWRATH_DASH_01 <- 151
CUSTOM_ANI_ATSCUDTHEWRATH_STOP_01 <- 152
CUSTOM_ANI_ATSCUDTHEWRATH_END_BODY <- 153
CUSTOM_ANI_THIRDRIB_TRANS_START_BODY <- 154
CUSTOM_ANI_THIRDRIB_A_BODY <- 155
CUSTOM_ANI_THIRDRIB_B_BODY <- 156
CUSTOM_ANI_THIRDRIB_C_BODY <- 157
CUSTOM_ANI_THIRDRIB_TRANS_END_BODY <- 158
CUSTOM_ANI_SECONDSOULATTACK1_03 <- 159
CUSTOM_ANI_SECONDSOULATTACK2_03 <- 160
CUSTOM_ANI_SECONDSOULATTACK3_02 <- 161
CUSTOM_ANI_SECONDSOULATTACK4_03 <- 162
CUSTOM_ANI_SECONDSOULATTACK5_03 <- 163
CUSTOM_ANI_SECONDSOULATTACK6_02 <- 164
CUSTOM_ANI_SECONDSOULATTACK2_03_TALISMAN <- 165
CUSTOM_ANI_SECONDSOULATTACK6_02_TALISMAN <- 166
CUSTOM_ANI_DEMONSECONDSOULATTACK1_03 <- 167
CUSTOM_ANI_DEMONSECONDSOULATTACK2_03 <- 168
CUSTOM_ANI_DEMONSECONDSOULATTACK3_03 <- 169
CUSTOM_ANI_DEMONSECONDSOULATTACK4_03 <- 170
CUSTOM_ANI_DEMONSECONDSOULATTACK5_03 <- 171
CUSTOM_ANI_DEMONSECONDSOULATTACK6_02 <- 172
CUSTOM_ANI_DEMONSECONDSOULATTACK2_03_TALISMAN <- 173
CUSTOM_ANI_DEMONSECONDSOULATTACK6_02_TALISMAN <- 174
CUSTOM_ANI_DEMONIZATIONATTACK_BASIC_Z_BODY <- 175
CUSTOM_ANI_DELIGHTFLOWER_CASTBODY <- 176
CUSTOM_ANI_ATLASTGENESIS_TRANSFORMATION1_BODY1 <- 177
CUSTOM_ANI_ATLASTGENESIS_CASTING_BODY1 <- 178
CUSTOM_ANI_ATLASTGENESIS_ATT1_BODY <- 179
CUSTOM_ANI_ATLASTGENESIS_FINISH1_BODY <- 180
CUSTOM_ANI_ATLASTGENESIS_FINISH2_BODY <- 181
CUSTOM_ANI_ATLASTGENESIS_TRANSFORMATION2_BODY1 <- 182
CUSTOM_ANI_ENVIOUSKISSTHROW <- 183
CUSTOM_ANI_ENVIOUSKISSTHROWHUMAN <- 184
CUSTOM_ANI_ENVIOUSKISSDASH <- 185
CUSTOM_ANI_ENVIOUSKISSHOLD <- 186
CUSTOM_ANI_ENVIOUSKISSFINISH <- 187
CUSTOM_ANI_ENVIOUSKISSFINISHHUMAN <- 188
CUSTOM_ANI_ATGLUTTONYVOMIT_CASTING_BODY <- 189
CUSTOM_ANI_ATGLUTTONYVOMIT_ATT_BODY <- 190
CUSTOM_ANI_ATGLUTTONYVOMIT_TRANSFORM1_BODY <- 191
CUSTOM_ANI_ATGLUTTONYVOMIT_TRANSFORM2_BODY <- 192
CUSTOM_ANI_ATGLUTTONYVOMIT_CAST_HUMAN_INSTALLATION_BODY <- 193
CUSTOM_ANI_ATGLUTTONYVOMIT_TRANSFORM_INSTALLATION_BODY <- 194
CUSTOM_ANI_ATGLUTTONYVOMIT_CAST_INSTALLATION_BODY <- 195
CUSTOM_ANI_ATGLUTTONYVOMIT_ATTACK_INSTALLATION_BODY <- 196
CUSTOM_ANI_THEDEADLYSINS_CAST <- 197
CUSTOM_ANI_THEDEADLYSINSDEMON_05 <- 198
CUSTOM_ANI_HANDAWAKENTOSIN_HUMAN2DEVIL_BODY <- 199
CUSTOM_ANI_HANDAWAKENTOSIN_SKILL_BODY_A <- 200
CUSTOM_ANI_HANDAWAKENTOSIN_SKILL_BODY_B <- 201
CUSTOM_ANI_HANDAWAKENTOSIN_DEVIL2HUMAN_BODY <- 202
CUSTOM_ANI_ATCARDINALEXECUTIONREADY_BODY <- 203
CUSTOM_ANI_ATCARDINALEXECUTIONATTACK1_BODY <- 204
CUSTOM_ANI_ATCARDINALEXECUTIONATTACK2_BODY <- 205
CUSTOM_ANI_ATCARDINALEXECUTIONATTACK3_BODY <- 206
CUSTOM_ANI_ATCARDINALEXECUTIONATTACK4_BODY <- 207
CUSTOM_ANI_ATCARDINALEXECUTIONATTACK5_BODY <- 208
CUSTOM_ANI_ATCARDINALEXECUTIONATTACK6_BODY <- 209
CUSTOM_ANI_ATCARDINALEXECUTIONATTACK7_BODY <- 210
CUSTOM_ANI_ATCARDINALEXECUTIONEND_BODY <- 211
CUSTOM_ANI_WINGSOFRESTPHASE1_MAINBODY <- 212
CUSTOM_ANI_WINGSOFRESTPHASE2FRONT_MAINBODY <- 213
CUSTOM_ANI_WINGSOFRESTPHASE3_MAINBODY <- 214
CUSTOM_ANI_WINGSOFRESTPHASE1PARTY_MAINBODY <- 215
CUSTOM_ANI_WINGSOFRESTPHASE2FRONTPARTY_13 <- 216
CUSTOM_ANI_WINGSOFRESTPHASE3PARTY_MAINBODY <- 217
CUSTOM_ANI_WINGSOFRESTPHASE1DEMON_MAINBODY <- 218
CUSTOM_ANI_WINGSOFRESTPHASE3DEMON_MAINBODY <- 219
CUSTOM_ANI_WINGSOFRESTPHASE1DEMONPARTY_MAINBODY <- 220
CUSTOM_ANI_WINGSOFRESTPHASE3DEMONPARTY_MAINBODY <- 221
CUSTOM_ANI_WINGSOFRESTEND_MAINBODY <- 222
CUSTOM_ANI_WINGSOFRESTENDDEMON_MAINBODY <- 223
CUSTOM_ANI_THEDEADLYSINS_START <- 224
CUSTOM_ANI_HEAVYSIN_DEMONIZATION <- 225
CUSTOM_ANI_NECKUPSCYTHE_ATTACK1_DEMON <- 226
CUSTOM_ANI_NECKUPSCYTHE_ATTACK2_DEMON <- 227
CUSTOM_ANI_ATCUTINDASH_FRONT_DASH_DEMONIZATION <- 228
CUSTOM_ANI_ATCUTINDASH_BACK_DASH_DEMONIZATION <- 229
CUSTOM_ANI_ATCUTINDASH_ATT_DEMONIZATION_FRONT <- 230
CUSTOM_ANI_ATCUTINDASH_ATT_DEMONIZATION_BACK <- 231


CUSTOM_ATTACK_ATDEPRAVITYSEVENSINS <- 25	//ï¿½ï¿½ï¿½Û?¿½ï¿?ï¿½ï¿½
CUSTOM_ATTACK_DEMONIZATION_ATTACK1 <- 26	//Ü¨ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_DEMONIZATION_ATTACK2 <- 27	//Ü¨ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_DEMONIZATION_ATTACK3 <- 28	//Ü¨ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_DEMONIZATION_JUMPATTACK <- 29	//Ü¨ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_DEMONIZATION_DASHATTACK <- 30	//Ü¨ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_DUALSLASH_FIRST <- 31	//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_DUALSLASH_SECOND <- 32	//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_GUILLOTINE_GRABTRY <- 33	//Ó¨ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_GUILLOTINE_GRAB_FIRST <- 34	//Ó¨ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_GUILLOTINE_GRAB_SECOND <- 35	//Ó¨ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_GUILLOTINE_SMASH <- 36	//Ó¨ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_ROLLONGRUSH <- 37	//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_ROLLONGRUSHFINSH <- 38	//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_ROLLONGRUSH_FRONT <- 39	//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_ROLLONGRUSHFINSH_FRONT <- 40	//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_LUSTHANDSWINGCUT <- 41	//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_SLOTHBODYATTACK <- 42	//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_SCYTHEMSSACRE_LOOP <- 43	//ß¯ï¿½ï¿½ï¿½ï¿½?
CUSTOM_ATTACK_SCYTHEMSSACRE_END <- 44	//ß¯ï¿½ï¿½ï¿½ï¿½?
CUSTOM_ATTACK_SCYTHEMSSACRE_LASTATTACK <- 45	//ß¯ï¿½ï¿½ï¿½ï¿½?
CUSTOM_ATTACK_SCUDTHEWRATHTRY <- 46	//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿?
CUSTOM_ATTACK_THIRDRIB <- 47	//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿?: ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_THIRDRIBFINSH <- 48	//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿?: ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_SECONDSOUL <- 49	//ï¿½ï¿½ï¿½ï¿½Õ§ï¿½ï¿½ : ï¿½ï¿½ï¿½ï¿½Ìª
CUSTOM_ATTACK_SECONDSOULTALISMAN <- 50	//ï¿½ï¿½ï¿½ï¿½Õ§ï¿½ï¿½ : ï¿½ï¿½ï¿½ï¿½Ìª
CUSTOM_ATTACK_LASTGENESISSWING <- 51	//ï¿½ï¿½ï¿½ï¿½ï¿?
CUSTOM_ATTACK_LASTGENESISSMASH <- 52	//ï¿½ï¿½ï¿½ï¿½ï¿?
CUSTOM_ATTACK_LASTGENESISFINSH <- 53	//ï¿½ï¿½ï¿½ï¿½ï¿?
CUSTOM_ATTACK_ENBIOUSKISS <- 54	//ï¿½ï¿½?ï¿½ï¿½ï¿½ï¿½
CUSTOM_ATTACK_ATGLUTTONYVOMITCAST <- 55	//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½?
CUSTOM_ATTACK_HANDAWAKENTOSIN <- 56	//ï¿½Øªï¿½ï¿½ï¿½
CUSTOM_ATTACK_HANDAWAKENTOSINEXPLOSION <- 57	//ï¿½Øªï¿½ï¿½ï¿½
CUSTOM_ATTACK_CARDINALEXECUTIONATTACK <- 58	//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿?
CUSTOM_ATTACK_CARDINALEXECUTIONFINISH <- 59	//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿?
CUSTOM_ATTACK_DEMONIZATIONRISINGSLASH <- 60	//ï¿½ï¿½ï¿½ï¿½ï¿½Øªï¿½ï¿?
CUSTOM_ATTACK_FIRSTPRANA <- 61	//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿?

//////////////////////////////////////////////////////

CUSTOM_ANI_ROSARYBEAD1<- 232
CUSTOM_ANI_ROSARYBEAD2<- 233
CUSTOM_ANI_ROSARYBEAD3<- 234
CUSTOM_ANI_ROSARYBEAD4<- 235
CUSTOM_ANI_ROSARYBEAD5<- 236
CUSTOM_ANI_ROSARYBEAD6<- 237
CUSTOM_ANI_PRAY1<- 238
CUSTOM_ANI_PRAY2<- 239
CUSTOM_ANI_ROSARYSHOOTING1<- 240
CUSTOM_ANI_ROSARYSHOOTING2<- 241
CUSTOM_ANI_ROSARYSTRIKE<- 242
CUSTOM_ANI_CONTRACTSPACEBYMAGIC1	<- 243
CUSTOM_ANI_CONTRACTSPACEBYMAGIC2	<- 244
CUSTOM_ANI_TALISMANOFOPPRESSION<- 245
CUSTOM_ANI_EXORCISMUS1<- 246
CUSTOM_ANI_EXORCISMUS2<- 247
CUSTOM_ANI_EXORCISMUS3<- 248
CUSTOM_ANI_EFFORTSPHERE1<- 249
CUSTOM_ANI_EFFORTSPHERE2<- 250
CUSTOM_ANI_TALISMANOFSOULSTEAL<- 251
CUSTOM_ANI_DRAGONWRATH1<- 252
CUSTOM_ANI_DRAGONWRATH2<- 253
CUSTOM_ANI_DRAGONWRATH3<- 254
CUSTOM_ANI_ROSARYOF108BEADS<- 255
CUSTOM_ANI_IMMOBILITYMAGICLINE1<- 256
CUSTOM_ANI_IMMOBILITYMAGICLINE2<- 257
CUSTOM_ANI_IMMOBILITYMAGICLINE3<- 258
CUSTOM_ANI_RITUALFORDRAGON1<- 259
CUSTOM_ANI_RITUALFORDRAGON2<- 260
CUSTOM_ANI_RITUALFORDRAGON3<- 261
CUSTOM_ANI_RITUALFORDRAGON4<- 262
CUSTOM_ANI_TALISMANOFTIMEBOMB<- 263
CUSTOM_ANI_LIFEDEPRIVEDISPOSITION1	<- 264
CUSTOM_ANI_LIFEDEPRIVEDISPOSITION2	<- 265
CUSTOM_ANI_LIFEDEPRIVEDISPOSITION3	<- 266
CUSTOM_ANI_ROSARYWILDSHOT1<- 267
CUSTOM_ANI_ROSARYWILDSHOT2<- 268
CUSTOM_ANI_BIGROSARY1<- 269
CUSTOM_ANI_BIGROSARY2<- 270
CUSTOM_ANI_WRATHOFGODDRAGON<- 271
CUSTOM_ANI_SWALLOWSKYDRAGON<- 272
CUSTOM_ANI_SKYSORCERESSUNITE1<- 273
CUSTOM_ANI_SKYSORCERESSUNITE2<- 274
CUSTOM_ANI_SKYSORCERESSUNITE3<- 275
CUSTOM_ANI_SKYSORCERESSUNITE4<- 276
CUSTOM_ANI_SKYSORCERESSUNITE5<- 277


CUSTOM_ATTACK_INFO_RITUALFORDRAGON1	<- 62
CUSTOM_ATTACK_INFO_RITUALFORDRAGON2	<- 63
CUSTOM_ATTACK_INFO_ROSARYWILDSHOT<- 64
CUSTOM_ATTACK_INFO_WRATHOFGODDRAGON	<- 65

//////////////////////////////////////////////////////

ANI_CrossOfPunishment_A_Body	<- 280	//ó¤Ìüä¨í®
ANI_CrossOfPunishment_B_Body	<- 281	
ANI_PunishmentBlow_Body_A	<- 282	//î®Ì½ñýÌª
ANI_PunishmentBlow_Body_B	<- 283	
ANI_PunishmentBlow_Body_Attack	<- 284	
ANI_AtJudgmentBlow_Body	<- 285	//ãû÷÷ñìÌª
ANI_AtJudgmentBlow_Att_Body	<- 286	
ANI_HolyFlame_Body	<- 287	//ãêæû ïÇûý
ANI_HolyFlame_Front_Body	<- 288	//ãêæû õúí©óÖ
ANI_HolyFlame_JudgmentBlow	<- 289	//ãêæû ãû÷÷ñìÌªÜÅÍôð¯ì£Ìª
ANI_VirtuousFury_HolyFlame_Body	<- 290	//ãêæû ÒÁûý
ANI_SummaryTiral_Body_Pierce_Atk1	<- 291	//ãêæû óÖ
ANI_SummaryTiral_Body_Nomal_Attack2	<- 292	//
ANI_SummaryTiral_Body_IncinerAtion_Attack2	<- 293	//
ANI_FlameOfBaptism_Body	<- 294	//ãêæûá©ÖÉ
ANI_PatrolBomb	<- 295	//ïäûùûýæû?
ANI_EssenceOfPhlege_Body	<- 296	//ûýæûïñü¤
ANI_EssenceOfPhlegeAir_Body	<- 297	
ANI_VirtuousFury_Normal_Body	<- 298	//ãêæû ÒÁûý
ANI_DecollAtionNormal_Body	<- 299	//ú¼úý
ANI_DecollAtionFireBody_Body	<- 300	
ANI_Inquisitor_Attack1	<- 301	//ãû÷÷Î¯îÜîú?âú
ANI_Inquisitor_Attack2	<- 302	
ANI_Inquisitor_Attack3	<- 303	
ANI_HolyFlameRest	<- 304	//ãêæûïÇûýý­îÜí¬á§
ANI_HolyFlameDash	<- 305	
ANI_HolyFlameJump	<- 306	
ANI_HolyFlameMove	<- 307	
ANI_HolyFlameStay	<- 308	
ANI_HolyFlameDamage1	<- 309	
ANI_HolyFlameDamage2	<- 310	
ANI_HolyFlameSit	<- 311	
ANI_HolyFlameJumpAttack	<- 312	
ANI_HolyFlameDashAttack	<- 313	
ANI_PunishmentBlow_Body_Attack_B	<- 314	//î®Ì½ñýÌª ð¯ì£ÌªîÜÜÅÌª
ANI_BurnAtThestake_A_Start_Body	<- 315	//ûýúý
ANI_BurnAtThestake_B_Move_Body	<- 316	
ANI_BurnAtThestake_C_Jump_Body	<- 317	
ANI_BurnAtThestake_D_Slowjump_Body	<- 318	
ANI_BurnAtThestake_E_Fall_Body	<- 319	
ANI_BurnAtThestake_F_Moveback_Body	<- 320	
ANI_BurnAtThestake_Cast_Body	<- 321	
ANI_BurnAtThestake_Finish_Body	<- 322	
ANI_NormalInquisitor_Attack1	<- 323	//ãû÷÷íºÜôÓáá¡æûîÜÜÅÌª
ANI_NormalInquisitor_Attack2	<- 324	
ANI_NormalInquisitor_Attack3	<- 325	
ANI_VortExOfHellFireThrowBody	<- 326	//ãêæûàÁè¾
ANI_VortExOfHellFireBodyReady_00	<- 327	
ANI_VortExOfHellFireBodyLoop_00	<- 328	
ANI_VortExOfHellFireBodyLoop_00_HolyFrame	<- 329	
ANI_VortExOfHellFireBodyEnd_00	<- 330	
ANI_VortExOfHellFireBodyEnd_00_HolyFrame	<- 331	
ANI_WheelOfPunishment_Ready	<- 332	//ó³×Çúý
ANI_WheelOfPunishment_Start	<- 333	
CUSTOM_ANI_INQUISITOR_DASHATTACK	<- 334
CUSTOM_ANI_INQUISITOR_JUMPATTACK	<- 335
CUSTOM_ANI_DISMEMBER_1_UPPERHIT_READYBODY	<- 336
CUSTOM_ANI_DISMEMBER_2_UPPERHIT_JUMPBODY	<- 337
CUSTOM_ANI_DISMEMBER_3_BACKSTEP_BODYSPIN	<- 338
CUSTOM_ANI_DISMEMBER_3_SPINHIT_SPINBODY	<- 339
CUSTOM_ANI_DISMEMBER_4_BACKSTEP_BODYDROP	<- 340
CUSTOM_ANI_DISMEMBER_4_SPINHIT_DROPBODY	<- 341
CUSTOM_ANI_DISMEMBER_5_DOWNHIT_BODY	<- 342
CUSTOM_ANI_DISMEMBER_6_FINISHHIT_BODY	<- 343
CUSTOM_ANI_DISMEMBERHOLYFRAME_1_UPPERHIT_READYBODY	<- 344
CUSTOM_ANI_DISMEMBERHOLYFRAME_2_UPPERHIT_JUMPBODY	<- 345
CUSTOM_ANI_DISMEMBERHOLYFRAME_3_BACKSTEP_BODYSPIN	<- 346
CUSTOM_ANI_DISMEMBERHOLYFRAME_3_SPINHIT_SPINBODY	<- 347
CUSTOM_ANI_DISMEMBERHOLYFRAME_4_BACKSTEP_BODYDROP	<- 348
CUSTOM_ANI_DISMEMBERHOLYFRAME_4_SPINHIT_DROPBODY	<- 349
CUSTOM_ANI_DISMEMBERHOLYFRAME_5_DOWNHIT_BODY	<- 350
CUSTOM_ANI_DISMEMBERHOLYFRAME_6_FINISHHIT_BODY	<- 351
CUSTOM_ANI_INFERNO_START1_BODY	<- 352
CUSTOM_ANI_INFERNO_ATTACK3_BODY	<- 353
CUSTOM_ANI_INFERNO_FINISH3_BODY	<- 354
CUSTOM_ANI_INFERNO_LANDING_BODY	<- 355
CUSTOM_ANI_FANATICISM_BODY	<- 356
CUSTOM_ANI_PETROLBOMB_BACKSTEP_BODY	<- 357
CUSTOM_ANI_HOLYFLAMEBUFF	<- 358
CUSTOM_ANI_HOLYFLAME_THROW1 <- 359
CUSTOM_ANI_HOLYFLAME_THROW2 <- 360
CUSTOM_ANI_HOLYFLAME_PRAY1 <- 361
CUSTOM_ANI_HOLYFLAME_PRAY2 <- 362
CUSTOM_ANI_HOLYFLAME_DELIVER1 <- 363
CUSTOM_ANI_HOLYFLAME_DELIVER2 <- 364
CUSTOM_ANI_HOLYFLAME_OVERTURN <- 365
CUSTOM_ANI_HOLYFLAME_FANATICISM_BODY	<- 366
CUSTOM_ANI_WRATHOFGODDRAGON_READYBODY	<- 367
CUSTOM_ANI_ROSARYSHOOTING_JUMP	<- 368
CUSTOM_ANI_ROSARYSHOOTING_JUMP2	<- 369
CUSTOM_ANI_TALISMANOFOPPRESSION_JUMP	<- 370
CUSTOM_ANI_TALISMANOFTIMEBOMB_JUMP	<- 371
CUSTOM_ANI_BIGROSARY_JUMP1<- 372
CUSTOM_ANI_BIGROSARY_JUMP2<- 373
CUSTOM_ANI_MALLEUSMALEFICARUM<- 374


ATK_PunishmentBlow_Attack <- 66	//î®Ì½ñýÌª
ATK_PunishmentBlow_Push <- 67	
ATK_JudgmentBlow <- 68	//ãû÷÷ñìÌª
ATK_HolyFlame_Normal <- 69	//ãêæû ïÇûý
ATK_HolyFlame_Front <- 70	
ATK_HolyFlame_JudgmentBlow <- 71	//ãêæû ãû÷÷ñìÌª
ATK_VirtuouSfury_HolyFlame <- 72	//ãêæû ÒÁûý
ATK_VirtuouSfury_Last_HolyFlame <- 73	
ATK_SummaryTiralPierce <- 74	//ãêæû óÖ
ATK_SummaryTiralNomalSwing <- 75	
ATK_SummaryTiralIncinerAtionSwing <- 76	
ATK_AtFlameOfBaptism <- 77	//ãêæûá©ÖÉ
ATK_EssenceOfPhlege_Exp <- 78	//ûýæûïñü¤
ATK_VirtuousFury_Normal <- 79	//ãêæû ÒÁûý
ATK_VirtuousFury_Last_Normal <- 80	
ATK_DecollAtion <- 81	//ú¼úý
ATK_DecollAtion_Push <- 82	
ATK_Inquisitor_Attack1 <- 83	//ãû÷÷Î¯îÜîú?âú
ATK_Inquisitor_Attack2 <- 84	
ATK_Inquisitor_Attack3 <- 85	
ATK_BurnAtThestake_First <- 86	//ûýúý
ATK_BurnAtThestake_Down <- 87	
ATK_VortExOfHellFireLoop <- 88	//ãêæûàÁè¾
ATK_VortExOfHellFireLoop_holyframe <- 89	
ATK_VortExOfHellFireEnd <- 90	
ATK_VortExOfHellFireEnd_holyframe <- 91	
ATK_WheelOfPunishment <- 92	//ó³×Çúý
CUSTOM_ATTACK_INFO_DISMEMBER_UPPER	<- 93
CUSTOM_ATTACK_INFO_DISMEMBER_SPINATTACK	<- 94
CUSTOM_ATTACK_INFO_DISMEMBER_DOWNBLOW	<- 95
CUSTOM_ATTACK_INFO_DISMEMBER_FINISHBLOW	<- 96
CUSTOM_ATTACK_INFO_HOLYFLAME_ATTACK1	<- 97
CUSTOM_ATTACK_INFO_HOLYFLAME_ATTACK2	<- 98
CUSTOM_ATTACK_INFO_HOLYFLAME_ATTACK3	<- 99
CUSTOM_ATTACK_INFO_HOLYFLAME_JUMP_ATTACK	<- 100
CUSTOM_ATTACK_INFO_HOLYFLAME_DASH_ATTACK	<- 101
CUSTOM_ATTACK_INFO_HOLYFLAME_DEBUFF	<- 102
CUSTOM_ATTACK_INFO_ATBURNATTHESTAKE	<- 103
CUSTOM_ATTACK_INFO_ATINFERNO_ATK	<- 104
CUSTOM_ATTACK_INFO_TEMPTRESS_ATTACK1	<- 105
CUSTOM_ATTACK_INFO_TEMPTRESS_ATTACK2	<- 106
CUSTOM_ATTACK_INFO_TEMPTRESS_ATTACK3	<- 107
CUSTOM_ATTACK_INFO_TEMPTRESS_DASHATTACK	<- 108
CUSTOM_ATTACK_INFO_TEMPTRESS_JUMPATTACK	<- 109


