

 
STATE_CHAKRAWEPAON_STEP		<- 101		//???????? ???
STATE_FIREHIDE				<- 102		//???? ?? ???
STATE_FLAMEBALL				<- 103		//???? ?? ?????????
STATE_ILUSIONSHURIKEN		<- 104		//??????????????
STATE_WOODMOVE				<- 105		//???? : ?????????
STATE_FLAMETORNADO			<- 106		//???? ?? ju???
STATE_BIGKUNAI				<- 107		//???? ?? ????????
STATE_MIGAWARI				<- 108		//???? : ??????
STATE_LEAVETRACE			<- 109		//???? : ?????
STATE_SKYROADS				<- 110		//???? ?? ????
STATE_DEITIESREBIRTH		<- 111		//???? : ??????
STATE_GASOLINEFIRE			<- 112		//???? ?? ??chu??????
STATE_FLAMEFLOWER			<- 113		//???? ?? ???????
STATE_DOOMFIELD				<- 114		//???? ?? ?????????
STATE_FLYINGSWALLOW			<- 115		//???? : ????????
STATE_YAMATAOROCHI			<- 116		//????????
STATE_FUUMASHURIKEN			<- 117		//???? ?? ????????
STATE_AMATERAS				<- 118		//???
STATE_SWORDOFKUSANAGI		<- 119		//???????? : ??????
STATE_THIEF_EXOTICRAMPANT         <- 220    
STATE_THIEF_DISTRIBUTION         <- 221    
STATE_THIEF_NOVAREMNANT          <- 222    
STATE_THIEF_EXECUTIONERSLASH        <- 223    
STATE_THIEF_NICOLASBLACKARACHNIA       <- 224    
STATE_THIEF_BALLACREADVENT         <- 225    
STATE_THIEF_LIVINGDEAD				<- 226 
STATE_CARDIOHEART <- 	229
STATE_WUQI				<- 230	
STATE_CUTNECK <- 	231
STATE_GOTOHELL <- 	232
STATE_HOLDUP <- 	233
STATE_BEHINDCUT <- 	234
STATE_SHAOWAREA <- 	235
STATE_SHAOWSLASH <- 	236
STATE_SHAOWSTAY <- 	237
STATE_SPEEDSLADE <- 	238
STATE_ASSASSINOFCREED <- 	239
STATE_BLOODSHAOWSLASH <- 	241
STATE_ASSASSINATION <- 	242
STATE_BLOODANDSHAOW <- 	243
STATE_SHADOW_WIPE <- 	244
//STATE_SEVER_SHADOW_SLASH <- 	245
//STATE_BLOOD_SHADOW_DANCE <- 	246
//STATE_BREAK_HEART <- 	247
//STATE_SHADOW_SOUL <- 	248


SKILL_POINTEDKNIFE		<- 10
SKILL_DEATH_HURRICANE	<- 11
SKILL_RINGOFDARKNESS	<- 32
SKILL_DIE_JI				<- 93
SKILL_HUI_XIE_JING_TONG			<- 94
SKILL_FIREHIDE						<- 78		//???? ?? ???
SKILL_EQUIPCHAKRAWEAPON				<- 79		//????????
SKILL_NINJUTSU						<- 80		//????????
SKILL_FLAMEBALL						<- 81		//???? ?? ?????????
SKILL_ILUSIONSHURIKEN				<- 82		//??????????????
SKILL_WOODMOVE						<- 83		//???? : ?????????
SKILL_SHURIKENIMPROVE				<- 84		//????????
SKILL_FLAMETORNADO					<- 85		//???? ?? ju???
SKILL_BIGKUNAI						<- 86		//???? ?? ????????
SKILL_MIGAWARI						<- 87		//???? : ??????
SKILL_LEAVETRACE					<- 88		//???? : ?????
SKILL_SKYROADS						<- 89		//???? ?? ????
SKILL_DEITIESREBIRTH				<- 90		//???? : ??????
SKILL_GASOLINEFIRE					<- 91		//???? ?? ??chu??????
SKILL_FLAMEFLOWER					<- 92		//???? ?? ???????
SKILL_KUROKAGENOJUTSU				<- 102		//????????
SKILL_DOOMFIELD						<- 103		//???? ?? ?????????
SKILL_FIREMARK						<- 95		//???????
SKILL_FLYINGSWALLOW					<- 96		//???? : ????????
SKILL_YAMATAOROCHI					<- 97		//????????
SKILL_FUUMASHURIKEN					<- 98		//???? ?? ????????
SKILL_AMATERAS						<- 99		//???
SKILL_SWORDOFKUSANAGI				<- 100		//???????? : ??????
SKILL_THIEF_EXOTICRAMPANT         <- 220    
SKILL_THIEF_DISTRIBUTION         <- 221    
SKILL_THIEF_NOVAREMNANT          <- 222    
SKILL_THIEF_EXECUTIONERSLASH        <- 223    
SKILL_THIEF_NICOLASBLACKARACHNIA       <- 224    
SKILL_THIEF_BALLACREADVENT         <- 225    
SKILL_THIEF_LIVINGDEAD				<- 226 	
SKILL_CARDIOHEART <- 229
SKILL_WUQI				<- 230	
SKILL_CUTNECK <- 	231
SKILL_GOTOHELL <- 	232
SKILL_HOLDUP <- 	233
SKILL_BEHINDCUT <- 	234
SKILL_SHAOWAREA <- 	235
SKILL_SHAOWSLASH <- 	236
SKILL_SHAOWSTAY <- 	237
SKILL_SPEEDSLADE <- 	238
SKILL_ASSASSINOFCREED <- 	239
SKILL_ASSASSIN <- 	240
SKILL_BLOODSHAOWSLASH <- 	241
SKILL_ASSASSINATION <- 	242
SKILL_BLOODANDSHAOW <- 	243
SKILL_SHADOW_WIPE <- 	244
//SKILL_SEVER_SHADOW_SLASH <- 	245
//SKILL_BLOOD_SHADOW_DANCE <- 	246
//SKILL_BREAK_HEART <- 	247
//SKILL_SHADOW_SOUL <- 	248
SKILL_LATENTABILITY				<- 254


CUSTOM_ANI_ACCELLINKSA_BODY	<- 103  
CUSTOM_ANI_THIEF_EXOTICRAMPANTATTACK      <- 120    		
CUSTOM_ANI_THIEF_EXOTICRAMPANTATTACKSHADOW     <- 121    		
CUSTOM_ANI_THIEF_EXOTICRAMPANTFINALATTACK     <- 122   		
CUSTOM_ANI_THIEF_EXOTICRAMPANTFINALATTACKSHADOW    <- 123    		
CUSTOM_ANI_THIEF_EXOTICRAMPANTATTACKHITEND     <- 124    		
CUSTOM_ANI_THIEF_DISTRIBUTION_ATTACKA_BODY     		<- 125
CUSTOM_ANI_THIEF_DISTRIBUTION_ATTACKB_BODY     		<- 126
CUSTOM_ANI_THIEF_DISTRIBUTION_ATTACKC_BODY    		<- 127
CUSTOM_ANI_THIEF_NOVAREMNANTJUMPCASTING_03    		<- 128
CUSTOM_ANI_THIEF_NOVAREMNANT_CASTING_BODY    		<- 129
CUSTOM_ANI_THIEF_NOVAREMNANT_JUMP_BODY    		<- 130
CUSTOM_ANI_THIEF_NOVAREMNANT_FINISH_BODY    		<- 131
CUSTOM_ANI_THIEF_NOVAREMNANT_HITEND_BODY     		<- 132
CUSTOM_ANI_THIEF_EXCS_BODY    		<- 133
CUSTOM_ANI_THIEF_CASTING01_BODY    		<- 134
CUSTOM_ANI_SHAOWAREA_BODY		<- 135
CUSTOM_ANI_THIEF_LIVINGDEAD 		<- 136
CUSTOM_ANI_ADESPHANTOMSTART_BODY		<- 137
CUSTOM_ANI_ADESPHANTOM1ST_BODY		<- 138
CUSTOM_ANI_ADESPHANTOM2ST_BODY		<- 139
CUSTOM_ANI_ADESPHANTOM3ST_BODY		<- 140
CUSTOM_ANI_ADESPHANTOM4ST_BODY		<- 141
CUSTOM_ANI_ADESPHANTOMEND_BODY		<- 142
CUSTOM_ANI_MOROSATTACKBODY_BODY		<- 143
CUSTOM_ANI_COCOONOFUNDEADSTART_BODY		<- 144
CUSTOM_ANI_GROWTYPE_KUNOICH		<- 145
CUSTOM_ANI_CHAKRAWEAPON_BACKSTEP		<- 146
CUSTOM_ANI_FIREHIDE		<- 147
CUSTOM_ANI_FLAMEBALL1		<- 148
CUSTOM_ANI_FLAMEBALL2		<- 149
CUSTOM_ANI_ILUSIONSHURIKEN1		<- 150
CUSTOM_ANI_ILUSIONSHURIKEN2		<- 151
CUSTOM_ANI_WOODMOVE1		<- 152
CUSTOM_ANI_WOODMOVE2		<- 153
CUSTOM_ANI_FLAMETORNADO		<- 154
CUSTOM_ANI_BIGKUNAI1		<- 155
CUSTOM_ANI_BIGKUNAI2		<- 156
CUSTOM_ANI_MIGAWARI1		<- 157
CUSTOM_ANI_MIGAWARI2		<- 158
CUSTOM_ANI_SKYROADS1		<- 159
CUSTOM_ANI_SKYROADS2		<- 160
CUSTOM_ANI_GASOLINEFIRE		<- 161
CUSTOM_ANI_FLAMEFLOWER		<- 162
CUSTOM_ANI_DOOMFIELD		<- 163
CUSTOM_ANI_FLYINGSWALLOW1		<- 164
CUSTOM_ANI_FLYINGSWALLOW2		<- 165
CUSTOM_ANI_YAMATAOROCHI		<- 166
CUSTOM_ANI_FUUMASHURIKEN1		<- 167
CUSTOM_ANI_FUUMASHURIKEN2		<- 168
CUSTOM_ANI_AMATERAS		<- 169
CUSTOM_ANI_SWORDOFKUSANAGI		<- 170
CUSTOM_ANI_SWORDOFKUSANAGI_STAY		<- 171
CUSTOM_ANI_SWORDOFKUSANAGI_MOVE		<- 172
CUSTOM_ANI_SWORDOFKUSANAGI_DASH		<- 173
CUSTOM_ANI_SWORDOFKUSANAGI_DASHATTACK		<- 174
CUSTOM_ANI_SWORDOFKUSANAGI_JUMP 		<- 175
CUSTOM_ANI_SWORDOFKUSANAGI_JUMPATTACK		<- 176
CUSTOM_ANI_SWORDOFKUSANAGI_ATTACK1		<- 177
CUSTOM_ANI_SWORDOFKUSANAGI_ATTACK2		<- 178
CUSTOM_ANI_ASSASSIN_NORMALATTACK		<- 179
//180		
//181		
//182		
CUSTOM_ANI_CRADIOHEART_PUSH		<- 183
CUSTOM_ANI_CRADIOHEART_PULL		<- 184
CUSTOM_ANI_CUTNECK_DOWN		<- 185
CUSTOM_ANI_CUTNECK_CUT		<- 186
CUSTOM_ANI_GOTOHELL_STANDREADYGRAB_BODY		<- 187
CUSTOM_ANI_GOTOHELL_STANDREADYJUMP_BODY		<- 188
CUSTOM_ANI_GOTOHELL_STANDJUMP_BODY		<- 189
CUSTOM_ANI_GOTOHELL_STANDFINISHGRAB_BODY		<- 190
CUSTOM_ANI_GOTOHELL_STANDFALL_BODY		<- 191
CUSTOM_ANI_GOTOHELL_JUMPTOROLLING_BODY		<- 192
CUSTOM_ANI_GOTOHELL_JUMPGRABROLLING_BODY		<- 193
CUSTOM_ANI_GOTOHELL_JUMPFINISHGRAB_BODY		<- 194
CUSTOM_ANI_GOTOHELL_JUMPGRABFAIL_BODY		<- 195
CUSTOM_ANI_SHAOWSTAY		<- 196
CUSTOM_ANI_HOLDUP		<- 197
CUSTOM_ANI_SPEEDSLADE_START		<- 198
CUSTOM_ANI_SPEEDSLADE_LOOPS		<- 199
CUSTOM_ANI_SPEEDLSADE_TLAST		<- 200
CUSTOM_ANI_SHAOWSLASH_FRIST		<- 201
CUSTOM_ANI_SHAOWSLASH_SECOND_A		<- 202
CUSTOM_ANI_SHAOWSLASH_SECOND_AA		<- 203
CUSTOM_ANI_SHAOWSLASH_FINISH_A		<- 204
CUSTOM_ANI_SHAOWSLASH_FINISH_B		<- 205
CUSTOM_ANI_SHAOWSLASH_FINISH_C		<- 206
CUSTOM_ANI_SHAOWAREA_BODY		<- 207
CUSTOM_ANI_SHAOWAREA_BODY2		<- 208
CUSTOM_ANI_SHAOWAREA_NORMALATTACK		<- 209
//210		
//211		
//212		
//213		
CUSTOM_ANI_ASSASSINOFCREED_BODY		<- 214
CUSTOM_ANI_BLOODSHAOWSLASH_CASTING		<- 215
CUSTOM_ANI_BLOODSHAOWSLASH_CASTING_SLASH		<- 216
CUSTOM_ANI_BLOODSHAOWSLASH_SLASH2		<- 217
CUSTOM_ANI_BLOODSHAOWSLASH_SLASH3		<- 218
CUSTOM_ANI_BLOODSHAOWSLASH_SLASH4		<- 219
CUSTOM_ANI_BLOODSHAOWSLASH_SLASH5		<- 220
CUSTOM_ANI_BLOODSHAOWSLASH_SLASH6		<- 221
CUSTOM_ANI_BLOODSHAOWSLASH_SLASH7		<- 222
CUSTOM_ANI_ASSASSINATION_READY		<- 223
CUSTOM_ANI_ASSASSINATION_SUCCESSFINDTARGET		<- 224
CUSTOM_ANI_ASSASSINATION_ASSAINSUCCESS		<- 225
CUSTOM_ANI_ASSASSINATION_FAIL		<- 226
CUSTOM_ANI_BLOODANDSHAOW_READY		<- 227
CUSTOM_ANI_BLOODANDSHAOW_LOOP		<- 228
CUSTOM_ANI_BLOODANDSHAOW_FINISH		<- 229
CUSTOM_ANI_SHADOW_WIPE_LAND_THROW		<- 230
CUSTOM_ANI_SHADOW_WIPE_MOVE		<- 231
CUSTOM_ANI_SHADOW_WIPE_LAST_0		<- 232
CUSTOM_ANI_SHADOW_WIPE_LAST_1		<- 233
CUSTOM_ANI_SHADOW_WIPE_JUMP_THROW		<- 234
CUSTOM_ANI_SHADOW_WIPE_JUMP_MOVE		<- 235
 
 
 
CUSTOM_ATTACK_THIEF_EXOTICRAMPANTATTACK      <- 44    
CUSTOM_ATTACK_THIEF_EXOTICRAMPANTFINALATTACK    <- 45    
CUSTOM_ATTACK_THIEF_EXOTICRAMPANTHITENDATTACK    <- 46    
CUSTOM_ATTACK_THIEF_NOVAREMNANTDASHATK      <- 47    
ATTACKINFO_ASSASSIN_NORMALATTACK <- 48
//49
//50
//51
ATTACKINFO_CRADIOHEART_PUSH <- 52
ATTACKINFO_CRADIOHEART_PULL <- 53
ATTACKINFO_CUTNECK_DOWN <- 54
ATTACKINFO_CUTNECK_CUT <- 55
ATTACKINFO_GOTOHELL_TRY <- 56
ATTACKINFO_HOLDUP <- 57
ATTACKINFO_SPEEDSLADE_LOOPS <- 58
ATTACKINFO_SPEEDLSADE_TLAST <- 59
ATTACKINFO_SHAOWSLASH_FRIST <- 60
ATTACKINFO_SHAOWSLASH_SECOND <- 61
ATTACKINFO_SHAOWSLASH_FINISH <- 62
ATTACKINFO_BLOODSHAOWSLASH_CASTING <- 63
ATTACKINFO_BLOODSHAOWSLASH_LOOP <- 64
ATTACKINFO_BLOODSHAOWSLASH_FINISH <- 65
ATTACKINFO_ASSASSINATION_READY <- 66
ATTACKINFO_ASSASSINATION_ASSASSINSUCCESS <- 67
ATTACKINFO_ASSASSINATION_FAIL <- 68
ATTACKINFO_BLOODANDSHAOW_LOOP <- 69
ATTACKINFO_SHAOWAREA <- 70
ATTACKINFO_SHADOW_WIPE_THROW <- 71
ATTACKINFO_SHADOW_WIPE_FINSIH_0 <- 72
ATTACKINFO_SHADOW_WIPE_FINSIH_1 <- 73


 
PASSIVEOBJ_SUB_STATE_0          <- 10
PASSIVEOBJ_SUB_STATE_1          <- 11
PASSIVEOBJ_SUB_STATE_2          <- 12
PASSIVEOBJ_SUB_STATE_3          <- 13
PASSIVEOBJ_SUB_STATE_4          <- 14
PASSIVEOBJ_SUB_STATE_5          <- 15
PASSIVEOBJ_SUB_STATE_6          <- 16
PASSIVEOBJ_SUB_STATE_7          <- 17
PASSIVEOBJ_SUB_STATE_8          <- 18
PASSIVEOBJ_SUB_STATE_9          <- 19
PASSIVEOBJ_SUB_STATE_10          <- 20
 

 
MONSTER_INDEX_THIEF_NICOLAS         <- 61531  
MONSTER_ZPOS_THIEF_NICOLASBLACKARACHNIA      <- 1111  


APID_FIREHIDE									<- 101		//???? ?? ???
APID_LEAVETRACE									<- 109		//???? : ?????
APID_DEITIESREBIRTH								<- 111		//???? : ??????
APID_SWORDOFKUSANAGI							<- 119		//???????? : ??????

SKILL_BLOOD_SHADOW_DANCE <- 246
STATE_BLOOD_SHADOW_DANCE <- 246
SKILL_SHADOW_SOUL <- 	247
STATE_SHADOW_SOUL <- 	247
SKILL_BREAK_HEART <- 	228
STATE_BREAK_HEART <- 	228
SKILL_SEVER_SHADOW_SLASH <- 	227
STATE_SEVER_SHADOW_SLASH <- 	227


ENUM_CUSTOM_ANI_BLOOD_SHADOW_DANCE_START <-  236
ENUM_CUSTOM_ANI_BLOOD_SHADOW_DANCE_A_BODY <- 237
ENUM_CUSTOM_ANI_BLOOD_SHADOW_DANCE_B_MOVE_BODY <- 238
ENUM_CUSTOM_ANI_BLOOD_SHADOW_DANCE_B_END <- 239
ENUM_CUSTOM_ANI_BLOOD_SHADOW_DANCE_C_BODY <- 240
ENUM_CUSTOM_ANI_BLOOD_SHADOW_DANCE_D_MOVE <- 241
ENUM_CUSTOM_ANI_BLOOD_SHADOW_DANCE_D_END <- 242
ENUM_CUSTOM_ANI_BLOOD_SHADOW_DANCE_E_BODY <- 243
ENUM_CUSTOM_ANI_BLOOD_SHADOW_DANCE_F_BODY <- 244
ENUM_CUSTOM_ANI_BLOOD_SHADOW_DANCE_G_BACK_ATTACK <- 245
ENUM_CUSTOM_ANI_BLOOD_SHADOW_DANCE_G_HOLD_SLASH <- 246
ENUM_CUSTOM_ANI_CHAIN_REACTION_BUFF <- 247
ENUM_CUSTOM_ANI_CHAIN_REACTION_SHOOT <- 248
ENUM_CUSTOM_ANI_CHAIN_REACTION_PULL <- 249
ENUM_CUSTOM_ANI_CHAIN_REACTION_SNATCH <- 250
ENUM_CUSTOM_ANI_CHAIN_REACTION_MOVE <- 251
ENUM_CUSTOM_ANI_CHAIN_REACTION_ATTACK <- 252
ENUM_CUSTOM_ANI_CHAIN_REACTION_BACK_ATTACK <- 253
ENUM_CUSTOM_ANI_CHAIN_REACTION_SUPERHOLD <- 254
ENUM_CUSTOM_ANI_CHAIN_REACTION_SHOOT_J <- 255
ENUM_CUSTOM_ANI_CHAIN_REACTION_PULL_J <- 256
ENUM_CUSTOM_ANI_CHAIN_REACTION_SNATCH_J <- 257
ENUM_CUSTOM_ANI_CHAIN_REACTION_MOVE_J <- 258
ENUM_CUSTOM_ANI_CHAIN_REACTION_ATTACK_J <- 259
ENUM_CUSTOM_ANI_CHAIN_REACTION_BACK_ATTACK_J <- 260
ENUM_CUSTOM_ANI_CHAIN_REACTION_SUPERHOLD_J <- 261
ENUM_CUSTOM_ANI_CHAIN_REACTION_FINISH <-262
CUSTOM_EXTRAIN_HEART_START <- 263
CUSTOM_EXTRAIN_HEART_ATTACK <- 264
ENUM_CUSTOM_ANI_SEVER_SHADOW_SLASH_START_ATTACK <- 265
ENUM_CUSTOM_ANI_SEVER_SHADOW_SLASH_ATTACK <- 266
ENUM_CUSTOM_ANI_SEVER_SHADOW_SLASH_START_FINISH_ <- 267
ENUM_CUSTOM_ANI_SEVER_SHADOW_SLASH_FINISH <- 268
ENUM_CUSTOM_ANI_SEVER_SHADOW_SLASH_FACE_0 <- 269
ENUM_CUSTOM_ANI_SEVER_SHADOW_SLASH_FACE_1 <- 270
ENUM_CUSTOM_ANI_SEVER_SHADOW_SLASH_FACE_2 <- 271
ENUM_CUSTOM_ANI_SEVER_SHADOW_SLASH_FACE_3 <- 272
ENUM_CUSTOM_ANI_SEVER_SHADOW_SLASH_FACE_4 <- 273
ENUM_CUSTOM_ANI_SEVER_SHADOW_SLASH_FACE_5 <- 274
ENUM_CUSTOM_ANI_SEVER_SHADOW_SLASH_FACE_6 <- 275

ATTACKINFO_SHADOWSLASH_DANCE_GRAB <- 74
ATTACKINFO_SHADOWSLASH_DANCE_FRIST_ATTACK <- 75
ATTACKINFO_SHADOWSLASH_DANCE_ATTACK <- 76
ATTACKINFo_SHADOWSLASH_DANCE_BACK_ATTACK <- 77
ATTACKINFO_SHADOWSLASH_DANCE_FINISH_ATTACK <- 78
ATTACKINFO_CHAIN_REACTION_SHOOT <- 79
ATTACKINFO_CHAIN_REACTION_PULL <- 80
ATTACKINFO_CHAIN_REACTION_SNATCH <- 81
ATTACKINFO_CHAIN_REACTION_ATTACK <- 82
ATTACKINFO_CHAIN_REACTION_BACK_ATTACK <- 83
ATTACKINFO_CHAIN_REACTION_NORMAL_FINISH <- 84
ATTACKINFO_CHAIN_REACTION_LAST_FINISH <- 85
ATTACKINFO_EXTARIN_HEART_START <- 86
ATTACKINFO_EXTRAIN_HEART_ATTACK <- 87
ATTACKINFO_SEVER_SHADOW_SLASH_1 <- 88
ATTACKINFO_SEVER_SHADOW_SLASH_2 <- 89
ATTACKINFO_SEVER_SHADOW_SLASH_3 <- 90
